
    /**
     * @file NRE_WindowsKeyTranslater.hpp
     * @brief Declaration of Event's API's Object : KeyTranslater
     * @author Louis ABEL
     * @date 12/05/2019
     * @copyright CC-BY-NC-SA
     */

    #pragma once

    #include "../../../../../System/Event/Input/Keys/NRE_Keys.hpp"
    #include <Windows.h>

    /**
     * @namespace NRE
     * @brief The NearlyRealEngine's global namespace
     */
    namespace NRE {
        /**
         * @namespace Event
         * @brief Event's API
         */
        namespace Event {

            /**
             * @class KeyTranslater
             * @brief Manage the translation of native key
             */
            class KeyTranslater {
                public :    // Methods
                    //## Methods ##//
                        /**
                         * Translate a native key code into an NRE key
                         * @param  wParam additionnal message-specific information
                         * @param  lParam additionnal message-specific information
                         * @return        the translated key
                         */
                        KeyCode translateKey(WPARAM wParam, LPARAM lParam) const;


                private :   // Static
                    /**
                     * Store the map used to translate native key,
                     * Derived from : https://docs.microsoft.com/en-us/windows/desktop/inputdev/virtual-key-codes
                     */
                    static constexpr KeyCode translationMap[] = {
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::BACKSPACE,
                        KeyCode::TAB,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::CLEAR,
                        KeyCode::ENTER,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::SHIFT,
                        KeyCode::CONTROL,
                        KeyCode::ALT,
                        KeyCode::PAUSE,
                        KeyCode::CAPS_LOCK,
                        KeyCode::LANG_1,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::LANG_2,
                        KeyCode::NONE,
                        KeyCode::ESCAPE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::SPACE,
                        KeyCode::PAGE_UP,
                        KeyCode::PAGE_DOWN,
                        KeyCode::END,
                        KeyCode::HOME,
                        KeyCode::LEFT,
                        KeyCode::UP,
                        KeyCode::RIGHT,
                        KeyCode::DOWN,
                        KeyCode::NONE,
                        KeyCode::PRINT_SCREEN,
                        KeyCode::OPEN,
                        KeyCode::PRINT_SCREEN,
                        KeyCode::INSERT,
                        KeyCode::DELETE_KEY,
                        KeyCode::HELP,
                        KeyCode::NUM_0,
                        KeyCode::NUM_1,
                        KeyCode::NUM_2,
                        KeyCode::NUM_3,
                        KeyCode::NUM_4,
                        KeyCode::NUM_5,
                        KeyCode::NUM_6,
                        KeyCode::NUM_7,
                        KeyCode::NUM_8,
                        KeyCode::NUM_9,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::A,
                        KeyCode::B,
                        KeyCode::C,
                        KeyCode::D,
                        KeyCode::E,
                        KeyCode::F,
                        KeyCode::G,
                        KeyCode::H,
                        KeyCode::I,
                        KeyCode::J,
                        KeyCode::K,
                        KeyCode::L,
                        KeyCode::M,
                        KeyCode::N,
                        KeyCode::O,
                        KeyCode::P,
                        KeyCode::Q,
                        KeyCode::R,
                        KeyCode::S,
                        KeyCode::T,
                        KeyCode::U,
                        KeyCode::V,
                        KeyCode::W,
                        KeyCode::X,
                        KeyCode::Y,
                        KeyCode::Z,
                        KeyCode::LEFT_META,
                        KeyCode::RIGHT_META,
                        KeyCode::OPEN,
                        KeyCode::NONE,
                        KeyCode::MEDIA_SLEEP,
                        KeyCode::KEYPAD_0,
                        KeyCode::KEYPAD_1,
                        KeyCode::KEYPAD_2,
                        KeyCode::KEYPAD_3,
                        KeyCode::KEYPAD_4,
                        KeyCode::KEYPAD_5,
                        KeyCode::KEYPAD_6,
                        KeyCode::KEYPAD_7,
                        KeyCode::KEYPAD_8,
                        KeyCode::KEYPAD_9,
                        KeyCode::KEYPAD_ASTERISK,
                        KeyCode::KEYPAD_PLUS,
                        KeyCode::SEPARATOR,
                        KeyCode::KEYPAD_MINUS,
                        KeyCode::KEYPAD_DECIMAL,
                        KeyCode::KEYPAD_SLASH,
                        KeyCode::F1,
                        KeyCode::F2,
                        KeyCode::F3,
                        KeyCode::F4,
                        KeyCode::F5,
                        KeyCode::F6,
                        KeyCode::F7,
                        KeyCode::F8,
                        KeyCode::F9,
                        KeyCode::F10,
                        KeyCode::F11,
                        KeyCode::F12,
                        KeyCode::F13,
                        KeyCode::F14,
                        KeyCode::F15,
                        KeyCode::F16,
                        KeyCode::F17,
                        KeyCode::F18,
                        KeyCode::F19,
                        KeyCode::F20,
                        KeyCode::F21,
                        KeyCode::F22,
                        KeyCode::F23,
                        KeyCode::F24,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NUM_LOCK,
                        KeyCode::SCROLL_LOCK,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::LEFT_SHIFT,
                        KeyCode::RIGHT_SHIFT,
                        KeyCode::LEFT_CONTROL,
                        KeyCode::RIGHT_CONTROL,
                        KeyCode::OPEN,
                        KeyCode::OPEN,
                        KeyCode::MEDIA_BACK,
                        KeyCode::MEDIA_FORWARD,
                        KeyCode::MEDIA_REFRESH,
                        KeyCode::MEDIA_STOP,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::MUTE,
                        KeyCode::VOLUME_DOWN,
                        KeyCode::VOLUME_UP,
                        KeyCode::MEDIA_NEXT_SONG,
                        KeyCode::MEDIA_PREVIOUS_SONG,
                        KeyCode::MEDIA_STOP,
                        KeyCode::MEDIA_PLAY_PAUSE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::SEMICOLON,
                        KeyCode::KEYPAD_EQUALS,
                        KeyCode::COMMA,
                        KeyCode::MINUS,
                        KeyCode::DOT,
                        KeyCode::SLASH,
                        KeyCode::NON_US_HASH_TILDE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::LEFT_BRACE,
                        KeyCode::BACKSLASH,
                        KeyCode::RIGHT_BRACE,
                        KeyCode::APOSTROPHE,
                        KeyCode::KEYPAD_EXCLAMATION,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NON_US_BACKSLASH,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::PAUSE,
                        KeyCode::CR_SEL_PROPS,
                        KeyCode::EX_SEL,
                        KeyCode::KEYPAD_CLEAR_ENTRY,
                        KeyCode::MEDIA_PLAY_PAUSE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::NONE,
                        KeyCode::KEYPAD_CLEAR_ENTRY
                    };
            };
        }
    }

    #include "NRE_WindowsKeyTranslater.tpp"
