
    /**
     * @file NRE_WindowsKeyTranslater.hpp
     * @brief Declaration of Event's API's Object : KeyTranslater
     * @author Louis ABEL
     * @date 12/05/2019
     * @copyright CC-BY-NC-SA
     */

    #pragma once

    #include "../../../../../System/Event/Input/Keys/NRE_Keys.hpp"
    #include <Windows.h>

    /**
     * @namespace NRE
     * @brief The NearlyRealEngine's global namespace
     */
    namespace NRE {
        /**
         * @namespace Event
         * @brief Event's API
         */
        namespace Event {

            /**
             * @class KeyTranslater
             * @brief Manage the translation of native key
             */
            class KeyTranslater {
                public :    // Methods
                    //## Methods ##//
                        /**
                         * Translate a native key code into an NRE key
                         * @param  wParam additionnal message-specific information
                         * @param  lParam additionnal message-specific information
                         * @return        the translated key
                         */
                        Key translateKey(WPARAM wParam, LPARAM lParam) const;


                private :   // Static
                    static constexpr Key translationMap[] = {
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::BACKSPACE,
                        Key::TAB,
                        Key::NONE,
                        Key::NONE,
                        Key::CLEAR,
                        Key::ENTER,
                        Key::NONE,
                        Key::NONE,
                        Key::SHIFT,
                        Key::CONTROL,
                        Key::ALT,
                        Key::PAUSE,
                        Key::CAPS_LOCK,
                        Key::LANG_1,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::LANG_2,
                        Key::NONE,
                        Key::ESCAPE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::SPACE,
                        Key::PAGE_UP,
                        Key::PAGE_DOWN,
                        Key::END,
                        Key::HOME,
                        Key::LEFT,
                        Key::UP,
                        Key::RIGHT,
                        Key::DOWN,
                        Key::NONE,
                        Key::PRINT_SCREEN,
                        Key::OPEN,
                        Key::PRINT_SCREEN,
                        Key::INSERT,
                        Key::DELETE_KEY,
                        Key::HELP,
                        Key::NUM_0,
                        Key::NUM_1,
                        Key::NUM_2,
                        Key::NUM_3,
                        Key::NUM_4,
                        Key::NUM_5,
                        Key::NUM_6,
                        Key::NUM_7,
                        Key::NUM_8,
                        Key::NUM_9,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::A,
                        Key::B,
                        Key::C,
                        Key::D,
                        Key::E,
                        Key::F,
                        Key::G,
                        Key::H,
                        Key::I,
                        Key::J,
                        Key::K,
                        Key::L,
                        Key::M,
                        Key::N,
                        Key::O,
                        Key::P,
                        Key::Q,
                        Key::R,
                        Key::S,
                        Key::T,
                        Key::U,
                        Key::V,
                        Key::W,
                        Key::X,
                        Key::Y,
                        Key::Z,
                        Key::LEFT_META,
                        Key::RIGHT_META,
                        Key::OPEN,
                        Key::NONE,
                        Key::MEDIA_SLEEP,
                        Key::KEYPAD_0,
                        Key::KEYPAD_1,
                        Key::KEYPAD_2,
                        Key::KEYPAD_3,
                        Key::KEYPAD_4,
                        Key::KEYPAD_5,
                        Key::KEYPAD_6,
                        Key::KEYPAD_7,
                        Key::KEYPAD_8,
                        Key::KEYPAD_9,
                        Key::KEYPAD_ASTERISK,
                        Key::KEYPAD_PLUS,
                        Key::SEPARATOR,
                        Key::KEYPAD_MINUS,
                        Key::KEYPAD_DECIMAL,
                        Key::KEYPAD_SLASH,
                        Key::F1,
                        Key::F2,
                        Key::F3,
                        Key::F4,
                        Key::F5,
                        Key::F6,
                        Key::F7,
                        Key::F8,
                        Key::F9,
                        Key::F10,
                        Key::F11,
                        Key::F12,
                        Key::F13,
                        Key::F14,
                        Key::F15,
                        Key::F16,
                        Key::F17,
                        Key::F18,
                        Key::F19,
                        Key::F20,
                        Key::F21,
                        Key::F22,
                        Key::F23,
                        Key::F24,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NUM_LOCK,
                        Key::SCROLL_LOCK,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::LEFT_SHIFT,
                        Key::RIGHT_SHIFT,
                        Key::LEFT_CONTROL,
                        Key::RIGHT_CONTROL,
                        Key::OPEN,
                        Key::OPEN,
                        Key::MEDIA_BACK,
                        Key::MEDIA_FORWARD,
                        Key::MEDIA_REFRESH,
                        Key::MEDIA_STOP,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::MUTE,
                        Key::VOLUME_DOWN,
                        Key::VOLUME_UP,
                        Key::MEDIA_NEXT_SONG,
                        Key::MEDIA_PREVIOUS_SONG,
                        Key::MEDIA_STOP,
                        Key::MEDIA_PLAY_PAUSE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::SEMICOLON,
                        Key::KEYPAD_EQUALS,
                        Key::COMMA,
                        Key::MINUS,
                        Key::DOT,
                        Key::SLASH,
                        Key::NON_US_HASH_TILDE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::LEFT_BRACE,
                        Key::BACKSLASH,
                        Key::RIGHT_BRACE,
                        Key::APOSTROPHE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NON_US_BACKSLASH,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::PAUSE,
                        Key::CR_SEL_PROPS,
                        Key::EX_SEL,
                        Key::KEYPAD_CLEAR_ENTRY,
                        Key::MEDIA_PLAY_PAUSE,
                        Key::NONE,
                        Key::NONE,
                        Key::NONE,
                        Key::KEYPAD_CLEAR_ENTRY,
                    };
            };
        }
    }
