<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: /mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Graphics/Window/Internal/NRE_InternalWindow.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_ef68f1e1f5148ff8ef7fb1c955106c3c.php">System</a></li><li class="navelem"><a class="el" href="dir_13c1ecb482d2b1153b2c0856159b065a.php">Graphics</a></li><li class="navelem"><a class="el" href="dir_4f86bd3a8a8cc0a9216ad2e14aa5b93d.php">Window</a></li><li class="navelem"><a class="el" href="dir_6de62d501958d67bdab66e9e8d9daf24.php">Internal</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_InternalWindow.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___internal_window_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">     #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">     #include &lt;Header/NRE_Math.hpp&gt;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;<span class="preprocessor">     #include &lt;Utility/String/NRE_String.hpp&gt;</span></div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;<span class="preprocessor">     #include &lt;Utility/Singleton/NRE_Singleton.hpp&gt;</span></div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;</div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;<span class="preprocessor">     #include &quot;../Style/NRE_WindowStyle.hpp&quot;</span></div><div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;<span class="preprocessor">     #include &quot;../../Driver/NRE_GraphicsDriver.hpp&quot;</span></div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;</div><div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;     <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00028"></a><span class="lineno">   28</span>&#160;         <span class="keyword">namespace </span><a class="code" href="namespace_graphics.php">Graphics</a> {</div><div class="line"><a name="l00029"></a><span class="lineno">   29</span>&#160;</div><div class="line"><a name="l00034"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_graphics_1_1_internal_window.php">   34</a></span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_1_1_graphics_1_1_internal_window.php">InternalWindow</a> {</div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;                <span class="keyword">private</span> :   <span class="comment">// Fields</span></div><div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;                    NativeWindowType <span class="keyword">internal</span>;    </div><div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;                    Id id;                        </div><div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;<span class="preprocessor">                    #ifdef WIN32                // Windows</span></div><div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;                        HDC device;                 </div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;                        LONG_PTR savedStyle;        </div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;                        LONG_PTR savedExStyle;      </div><div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;                        <span class="keywordtype">bool</span> savedInFullscreen;     </div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;                        RECT savedRect;             </div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;<span class="preprocessor">                    #elif __linux__             // Linux</span></div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;                        <span class="keywordtype">int</span> xId;                    </div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;<span class="preprocessor">                    #endif</span></div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;</div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;                <span class="keyword">public</span> :    <span class="comment">// Methods</span></div><div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00053"></a><span class="lineno">   53</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_graphics_1_1_internal_window.php#a09412c723df75e0e2880508fefa9ee42">InternalWindow</a>() = <span class="keyword">delete</span>;</div><div class="line"><a name="l00062"></a><span class="lineno">   62</span>&#160;                        <a class="code" href="class_n_r_e_1_1_graphics_1_1_internal_window.php#a09412c723df75e0e2880508fefa9ee42">InternalWindow</a>(Id i, Utility::String <span class="keyword">const</span>&amp; title, Math::Point2D&lt;unsigned int&gt; <span class="keyword">const</span>&amp; position, Math::Vector2D&lt;unsigned int&gt; <span class="keyword">const</span>&amp; size, <a class="code" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a> <span class="keyword">const</span>&amp; style);</div><div class="line"><a name="l00070"></a><span class="lineno">   70</span>&#160;                        <a class="code" href="class_n_r_e_1_1_graphics_1_1_internal_window.php#a09412c723df75e0e2880508fefa9ee42">InternalWindow</a>(Id i, Utility::String <span class="keyword">const</span>&amp; title, Math::Vector2D&lt;unsigned int&gt; <span class="keyword">const</span>&amp; size, <a class="code" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a> <span class="keyword">const</span>&amp; style);</div><div class="line"><a name="l00071"></a><span class="lineno">   71</span>&#160;</div><div class="line"><a name="l00072"></a><span class="lineno">   72</span>&#160;                    <span class="comment">//## Copy Constructor ##//</span></div><div class="line"><a name="l00077"></a><span class="lineno">   77</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_graphics_1_1_internal_window.php#a09412c723df75e0e2880508fefa9ee42">InternalWindow</a>(<a class="code" href="class_n_r_e_1_1_graphics_1_1_internal_window.php">InternalWindow</a> <span class="keyword">const</span>&amp; inl) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00078"></a><span class="lineno">   78</span>&#160;</div><div class="line"><a name="l00079"></a><span class="lineno">   79</span>&#160;                    <span class="comment">//## Move Constructor ##//</span></div><div class="line"><a name="l00084"></a><span class="lineno">   84</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_graphics_1_1_internal_window.php#a09412c723df75e0e2880508fefa9ee42">InternalWindow</a>(<a class="code" href="class_n_r_e_1_1_graphics_1_1_internal_window.php">InternalWindow</a> &amp;&amp; inl) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00085"></a><span class="lineno">   85</span>&#160;</div><div class="line"><a name="l00086"></a><span class="lineno">   86</span>&#160;                    <span class="comment">//## Deconstructor ##//</span></div><div class="line"><a name="l00090"></a><span class="lineno">   90</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_graphics_1_1_internal_window.php#a3d3b2f97a886a89af1212aad0388de8e">~InternalWindow</a>() = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00091"></a><span class="lineno">   91</span>&#160;</div><div class="line"><a name="l00092"></a><span class="lineno">   92</span>&#160;                    <span class="comment">//## Getter ##//</span></div><div class="line"><a name="l00096"></a><span class="lineno">   96</span>&#160;<span class="comment"></span>                        Math::Point2D&lt;unsigned int&gt; <a class="code" href="class_n_r_e_1_1_graphics_1_1_internal_window.php#aa67ab3f27e5e59f59af9dc27fcd6143b">getPosition</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00097"></a><span class="lineno">   97</span>&#160;<span class="preprocessor">                        #ifdef _WIN32</span></div><div class="line"><a name="l00098"></a><span class="lineno">   98</span>&#160;</div><div class="line"><a name="l00101"></a><span class="lineno">  101</span>&#160;                            HDC&amp; getDevice();</div><div class="line"><a name="l00102"></a><span class="lineno">  102</span>&#160;<span class="preprocessor">                        #elif __linux__</span></div><div class="line"><a name="l00103"></a><span class="lineno">  103</span>&#160;</div><div class="line"><a name="l00106"></a><span class="lineno">  106</span>&#160;                            <span class="keywordtype">int</span> getXId() <span class="keyword">const</span>;</div><div class="line"><a name="l00107"></a><span class="lineno">  107</span>&#160;<span class="preprocessor">                        #endif</span></div><div class="line"><a name="l00108"></a><span class="lineno">  108</span>&#160;</div><div class="line"><a name="l00109"></a><span class="lineno">  109</span>&#160;                    <span class="comment">//## Methods ##//</span></div><div class="line"><a name="l00113"></a><span class="lineno">  113</span>&#160;<span class="comment"></span>                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_graphics_1_1_internal_window.php#a0fa836b27b2b03d6d21fb0b3f74d4ad6">close</a>();</div><div class="line"><a name="l00117"></a><span class="lineno">  117</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_graphics_1_1_internal_window.php#a9fc19becfaf28bfac2932bbf46df293b">toggleFullscreen</a>(<span class="keywordtype">bool</span> inFullscreen);</div><div class="line"><a name="l00121"></a><span class="lineno">  121</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_graphics_1_1_internal_window.php#adb9d577cf68a3f203b2269b6db2dd461">refresh</a>();</div><div class="line"><a name="l00122"></a><span class="lineno">  122</span>&#160;</div><div class="line"><a name="l00123"></a><span class="lineno">  123</span>&#160;                    <span class="comment">//## Assignment Operator ##//</span></div><div class="line"><a name="l00129"></a><span class="lineno">  129</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_graphics_1_1_internal_window.php">InternalWindow</a>&amp; <a class="code" href="class_n_r_e_1_1_graphics_1_1_internal_window.php#a01f7b7a02ae1fa7c5915ebf31097896a">operator =</a>(<a class="code" href="class_n_r_e_1_1_graphics_1_1_internal_window.php">InternalWindow</a> <span class="keyword">const</span>&amp; inl) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00135"></a><span class="lineno">  135</span>&#160;                        <a class="code" href="class_n_r_e_1_1_graphics_1_1_internal_window.php">InternalWindow</a>&amp; <a class="code" href="class_n_r_e_1_1_graphics_1_1_internal_window.php#a01f7b7a02ae1fa7c5915ebf31097896a">operator =</a>(<a class="code" href="class_n_r_e_1_1_graphics_1_1_internal_window.php">InternalWindow</a> &amp;&amp; inl) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00136"></a><span class="lineno">  136</span>&#160;</div><div class="line"><a name="l00137"></a><span class="lineno">  137</span>&#160;                <span class="keyword">private</span> :   <span class="comment">// Methods</span></div><div class="line"><a name="l00138"></a><span class="lineno">  138</span>&#160;<span class="preprocessor">                    #ifdef _WIN32               // Windows</span></div><div class="line"><a name="l00139"></a><span class="lineno">  139</span>&#160;</div><div class="line"><a name="l00147"></a><span class="lineno">  147</span>&#160;                        <span class="keyword">static</span> LRESULT CALLBACK internalDispatcher(HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam);</div><div class="line"><a name="l00153"></a><span class="lineno">  153</span>&#160;                        <span class="keyword">static</span> Math::Point2D&lt;unsigned int&gt; computeCenteredPosition(Math::Vector2D&lt;unsigned int&gt; size);</div><div class="line"><a name="l00154"></a><span class="lineno">  154</span>&#160;<span class="preprocessor">                    #elif __linux__                         // Linux</span></div><div class="line"><a name="l00155"></a><span class="lineno">  155</span>&#160;</div><div class="line"><a name="l00159"></a><span class="lineno">  159</span>&#160;                        <span class="keywordtype">void</span> updateStyle(<a class="code" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a> <span class="keyword">const</span>&amp; style);</div><div class="line"><a name="l00165"></a><span class="lineno">  165</span>&#160;                        <span class="keywordtype">void</span> finishCreation(<a class="code" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a> <span class="keyword">const</span>&amp; style, Utility::String <span class="keyword">const</span>&amp; title);</div><div class="line"><a name="l00166"></a><span class="lineno">  166</span>&#160;<span class="preprocessor">                    #endif</span></div><div class="line"><a name="l00167"></a><span class="lineno">  167</span>&#160;            };</div><div class="line"><a name="l00168"></a><span class="lineno">  168</span>&#160;        }</div><div class="line"><a name="l00169"></a><span class="lineno">  169</span>&#160;    }</div><div class="line"><a name="l00170"></a><span class="lineno">  170</span>&#160;</div><div class="line"><a name="l00171"></a><span class="lineno">  171</span>&#160;<span class="preprocessor">    #ifdef _WIN32               // Windows</span></div><div class="line"><a name="l00172"></a><span class="lineno">  172</span>&#160;<span class="preprocessor">        #include &quot;../../../../OS/Windows/Graphics/Window/Internal/NRE_WindowsInternalWindow.tpp&quot;</span></div><div class="line"><a name="l00173"></a><span class="lineno">  173</span>&#160;<span class="preprocessor">    #elif __linux__             // Linux</span></div><div class="line"><a name="l00174"></a><span class="lineno">  174</span>&#160;<span class="preprocessor">        #include &quot;../../../../OS/Linux/Graphics/Window/Internal/NRE_LinuxInternalWindow.tpp&quot;</span></div><div class="line"><a name="l00175"></a><span class="lineno">  175</span>&#160;<span class="preprocessor">    #endif</span></div><div class="ttc" id="class_n_r_e_1_1_graphics_1_1_window_style_php"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_window_style.php">NRE::Graphics::WindowStyle</a></div><div class="ttdoc">Manage a window style. </div><div class="ttdef"><b>Definition:</b> NRE_WindowStyle.hpp:37</div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_internal_window_php_a3d3b2f97a886a89af1212aad0388de8e"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_internal_window.php#a3d3b2f97a886a89af1212aad0388de8e">NRE::Graphics::InternalWindow::~InternalWindow</a></div><div class="ttdeci">~InternalWindow()=default</div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_internal_window_php_adb9d577cf68a3f203b2269b6db2dd461"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_internal_window.php#adb9d577cf68a3f203b2269b6db2dd461">NRE::Graphics::InternalWindow::refresh</a></div><div class="ttdeci">void refresh()</div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_internal_window_php_a01f7b7a02ae1fa7c5915ebf31097896a"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_internal_window.php#a01f7b7a02ae1fa7c5915ebf31097896a">NRE::Graphics::InternalWindow::operator=</a></div><div class="ttdeci">InternalWindow &amp; operator=(InternalWindow const &amp;inl)=delete</div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_internal_window_php_aa67ab3f27e5e59f59af9dc27fcd6143b"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_internal_window.php#aa67ab3f27e5e59f59af9dc27fcd6143b">NRE::Graphics::InternalWindow::getPosition</a></div><div class="ttdeci">Math::Point2D&lt; unsigned int &gt; getPosition() const </div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_internal_window_php_a09412c723df75e0e2880508fefa9ee42"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_internal_window.php#a09412c723df75e0e2880508fefa9ee42">NRE::Graphics::InternalWindow::InternalWindow</a></div><div class="ttdeci">InternalWindow()=delete</div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_internal_window_php_a9fc19becfaf28bfac2932bbf46df293b"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_internal_window.php#a9fc19becfaf28bfac2932bbf46df293b">NRE::Graphics::InternalWindow::toggleFullscreen</a></div><div class="ttdeci">void toggleFullscreen(bool inFullscreen)</div><div class="ttdef"><b>Definition:</b> NRE_LinuxInternalWindow.cpp:87</div></div>
<div class="ttc" id="namespace_graphics_php"><div class="ttname"><a href="namespace_graphics.php">Graphics</a></div><div class="ttdoc">Graphics&amp;#39; API. </div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_internal_window_php"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_internal_window.php">NRE::Graphics::InternalWindow</a></div><div class="ttdoc">Manage the internal os-dependant graphics window. </div><div class="ttdef"><b>Definition:</b> NRE_InternalWindow.hpp:34</div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_internal_window_php_a0fa836b27b2b03d6d21fb0b3f74d4ad6"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_internal_window.php#a0fa836b27b2b03d6d21fb0b3f74d4ad6">NRE::Graphics::InternalWindow::close</a></div><div class="ttdeci">void close()</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
