<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: /mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Event/Input/Keys/NRE_Keys.hpp File Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_ef68f1e1f5148ff8ef7fb1c955106c3c.php">System</a></li><li class="navelem"><a class="el" href="dir_c60d7283d11d7ab0b1fc187569b1f175.php">Event</a></li><li class="navelem"><a class="el" href="dir_d92417724dfd51f842fe3a3ba51d06cc.php">Input</a></li><li class="navelem"><a class="el" href="dir_fc71b3565a9ab3ec7d5755aac9480c0e.php">Keys</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#namespaces">Namespaces</a> &#124;
<a href="#enum-members">Enumerations</a>  </div>
  <div class="headertitle">
<div class="title">NRE_Keys.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Declaration of <a class="el" href="namespace_event.php" title="Event&#39;s API. ">Event</a>'s API's Object : Key mapping.  
<a href="#details">More...</a></p>

<p><a href="_n_r_e___keys_8hpp_source.php">Go to the source code of this file.</a></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="namespaces"></a>
Namespaces</h2></td></tr>
<tr class="memitem:namespace_n_r_e"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespace_n_r_e.php">NRE</a></td></tr>
<tr class="memdesc:namespace_n_r_e"><td class="mdescLeft">&#160;</td><td class="mdescRight">The NearlyRealEngine's global namespace. <br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:namespace_event"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespace_event.php">Event</a></td></tr>
<tr class="memdesc:namespace_event"><td class="mdescLeft">&#160;</td><td class="mdescRight"><a class="el" href="namespace_event.php" title="Event&#39;s API. ">Event</a>'s API. <br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="enum-members"></a>
Enumerations</h2></td></tr>
<tr class="memitem:aad0b5de9f5c32805861bae5dda36d501"><td class="memItemLeft" align="right" valign="top">enum &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="_n_r_e___keys_8hpp.php#aad0b5de9f5c32805861bae5dda36d501">NRE::Event::KeyCode</a> : unsigned char { <br />
&#160;&#160;<b>NONE</b> = 0x00, 
<b>ERR_ROV</b> = 0x01, 
<b>ERR_POST</b> = 0x02, 
<b>ERR_UDF</b> = 0x03, 
<br />
&#160;&#160;<b>A</b> = 0x04, 
<b>B</b> = 0x05, 
<b>C</b> = 0x06, 
<b>D</b> = 0x07, 
<br />
&#160;&#160;<b>E</b> = 0x08, 
<b>F</b> = 0x09, 
<b>G</b> = 0x0a, 
<b>H</b> = 0x0b, 
<br />
&#160;&#160;<b>I</b> = 0x0c, 
<b>J</b> = 0x0d, 
<b>K</b> = 0x0e, 
<b>L</b> = 0x0f, 
<br />
&#160;&#160;<b>M</b> = 0x10, 
<b>N</b> = 0x11, 
<b>O</b> = 0x12, 
<b>P</b> = 0x13, 
<br />
&#160;&#160;<b>Q</b> = 0x14, 
<b>R</b> = 0x15, 
<b>S</b> = 0x16, 
<b>T</b> = 0x17, 
<br />
&#160;&#160;<b>U</b> = 0x18, 
<b>V</b> = 0x19, 
<b>W</b> = 0x1a, 
<b>X</b> = 0x1b, 
<br />
&#160;&#160;<b>Y</b> = 0x1c, 
<b>Z</b> = 0x1d, 
<b>NUM_1</b> = 0x1e, 
<b>NUM_2</b> = 0x1f, 
<br />
&#160;&#160;<b>NUM_3</b> = 0x20, 
<b>NUM_4</b> = 0x21, 
<b>NUM_5</b> = 0x22, 
<b>NUM_6</b> = 0x23, 
<br />
&#160;&#160;<b>NUM_7</b> = 0x24, 
<b>NUM_8</b> = 0x25, 
<b>NUM_9</b> = 0x26, 
<b>NUM_0</b> = 0x27, 
<br />
&#160;&#160;<b>ENTER</b> = 0x28, 
<b>ESCAPE</b> = 0x29, 
<b>BACKSPACE</b> = 0x2a, 
<b>TAB</b> = 0x2b, 
<br />
&#160;&#160;<b>SPACE</b> = 0x2c, 
<b>MINUS</b> = 0x2d, 
<b>EQUAL</b> = 0x2e, 
<b>LEFT_BRACE</b> = 0x2f, 
<br />
&#160;&#160;<b>RIGHT_BRACE</b> = 0x30, 
<b>BACKSLASH</b> = 0x31, 
<b>NON_US_HASH_TILDE</b> = 0x32, 
<b>SEMICOLON</b> = 0x33, 
<br />
&#160;&#160;<b>APOSTROPHE</b> = 0x34, 
<b>GRAVE</b> = 0x35, 
<b>COMMA</b> = 0x36, 
<b>DOT</b> = 0x37, 
<br />
&#160;&#160;<b>SLASH</b> = 0x38, 
<b>CAPS_LOCK</b> = 0x39, 
<b>F1</b> = 0x3a, 
<b>F2</b> = 0x3b, 
<br />
&#160;&#160;<b>F3</b> = 0x3c, 
<b>F4</b> = 0x3d, 
<b>F5</b> = 0x3e, 
<b>F6</b> = 0x3f, 
<br />
&#160;&#160;<b>F7</b> = 0x40, 
<b>F8</b> = 0x41, 
<b>F9</b> = 0x42, 
<b>F10</b> = 0x43, 
<br />
&#160;&#160;<b>F11</b> = 0x44, 
<b>F12</b> = 0x45, 
<b>PRINT_SCREEN</b> = 0x46, 
<b>SCROLL_LOCK</b> = 0x47, 
<br />
&#160;&#160;<b>PAUSE</b> = 0x48, 
<b>INSERT</b> = 0x49, 
<b>HOME</b> = 0x4a, 
<b>PAGE_UP</b> = 0x4b, 
<br />
&#160;&#160;<b>DELETE_KEY</b> = 0x4c, 
<b>END</b> = 0x4d, 
<b>PAGE_DOWN</b> = 0x4e, 
<b>RIGHT</b> = 0x4f, 
<br />
&#160;&#160;<b>LEFT</b> = 0x50, 
<b>DOWN</b> = 0x51, 
<b>UP</b> = 0x52, 
<b>NUM_LOCK</b> = 0x53, 
<br />
&#160;&#160;<b>KEYPAD_SLASH</b> = 0x54, 
<b>KEYPAD_ASTERISK</b> = 0x55, 
<b>KEYPAD_MINUS</b> = 0x56, 
<b>KEYPAD_PLUS</b> = 0x57, 
<br />
&#160;&#160;<b>KEYPAD_ENTER</b> = 0x58, 
<b>KEYPAD_1</b> = 0x59, 
<b>KEYPAD_2</b> = 0x5a, 
<b>KEYPAD_3</b> = 0x5b, 
<br />
&#160;&#160;<b>KEYPAD_4</b> = 0x5c, 
<b>KEYPAD_5</b> = 0x5d, 
<b>KEYPAD_6</b> = 0x5e, 
<b>KEYPAD_7</b> = 0x5f, 
<br />
&#160;&#160;<b>KEYPAD_8</b> = 0x60, 
<b>KEYPAD_9</b> = 0x61, 
<b>KEYPAD_0</b> = 0x62, 
<b>KEYPAD_DOT</b> = 0x63, 
<br />
&#160;&#160;<b>NON_US_BACKSLASH</b> = 0x64, 
<b>APPLICATION</b> = 0x65, 
<b>POWER</b> = 0x66, 
<b>KEYPAD_EQUALS</b> = 0x67, 
<br />
&#160;&#160;<b>F13</b> = 0x68, 
<b>F14</b> = 0x69, 
<b>F15</b> = 0x6a, 
<b>F16</b> = 0x6b, 
<br />
&#160;&#160;<b>F17</b> = 0x6c, 
<b>F18</b> = 0x6d, 
<b>F19</b> = 0x6e, 
<b>F20</b> = 0x6f, 
<br />
&#160;&#160;<b>F21</b> = 0x70, 
<b>F22</b> = 0x71, 
<b>F23</b> = 0x72, 
<b>F24</b> = 0x73, 
<br />
&#160;&#160;<b>OPEN</b> = 0x74, 
<b>HELP</b> = 0x75, 
<b>PROPS</b> = 0x76, 
<b>FRONT</b> = 0x77, 
<br />
&#160;&#160;<b>STOP</b> = 0x78, 
<b>AGAIN</b> = 0x79, 
<b>UNDO</b> = 0x7a, 
<b>CUT</b> = 0x7b, 
<br />
&#160;&#160;<b>COPY</b> = 0x7c, 
<b>PASTE</b> = 0x7d, 
<b>FIND</b> = 0x7e, 
<b>MUTE</b> = 0x7f, 
<br />
&#160;&#160;<b>VOLUME_UP</b> = 0x80, 
<b>VOLUME_DOWN</b> = 0x81, 
<b>LOCKING_CAPS_LOCK</b> = 0x82, 
<b>LOCKING_NUM_LOCK</b> = 0x83, 
<br />
&#160;&#160;<b>LOCKING_SCROLL_LOCK</b> = 0x84, 
<b>KEYPAD_COMMA</b> = 0x85, 
<b>KEYPAD_EQUALS_SIGN</b> = 0x86, 
<b>INTERNATIONAL_1</b> = 0x87, 
<br />
&#160;&#160;<b>INTERNATIONAL_2</b> = 0x88, 
<b>INTERNATIONAL_3</b> = 0x89, 
<b>INTERNATIONAL_4</b> = 0x8a, 
<b>INTERNATIONAL_5</b> = 0x8b, 
<br />
&#160;&#160;<b>INTERNATIONAL_6</b> = 0x8c, 
<b>INTERNATIONAL_7</b> = 0x8d, 
<b>INTERNATIONAL_8</b> = 0x8e, 
<b>INTERNATIONAL_9</b> = 0x8f, 
<br />
&#160;&#160;<b>LANG_1</b> = 0x90, 
<b>LANG_2</b> = 0x91, 
<b>LANG_3</b> = 0x92, 
<b>LANG_4</b> = 0x93, 
<br />
&#160;&#160;<b>LANG_5</b> = 0x94, 
<b>LANG_6</b> = 0x95, 
<b>LANG_7</b> = 0x96, 
<b>LANG_8</b> = 0x97, 
<br />
&#160;&#160;<b>LANG_9</b> = 0x98, 
<b>ALT_ERASE</b> = 0x99, 
<b>SYSREQ_ATTENTION</b> = 0x9a, 
<b>CANCEL</b> = 0x9b, 
<br />
&#160;&#160;<b>CLEAR</b> = 0x9c, 
<b>PRIOR</b> = 0x9d, 
<b>RETURN</b> = 0x9e, 
<b>SEPARATOR</b> = 0x9f, 
<br />
&#160;&#160;<b>OUT_KEY</b> = 0xa0, 
<b>OPER</b> = 0xa1, 
<b>CLEAR_AGAIN</b> = 0xa2, 
<b>CR_SEL_PROPS</b> = 0xa3, 
<br />
&#160;&#160;<b>EX_SEL</b> = 0xa4, 
<b>CONTROL</b> = 0xa5, 
<b>SHIFT</b> = 0xa6, 
<b>ALT</b> = 0xa7, 
<br />
&#160;&#160;<b>KEYPAD_00</b> = 0xb0, 
<b>KEYPAD_000</b> = 0xb1, 
<b>THOUSANDS_SEPARATOR</b> = 0xb2, 
<b>DECIMAL_SEPARATOR</b> = 0xb3, 
<br />
&#160;&#160;<b>CURRENCY_UNIT</b> = 0xb4, 
<b>CURRENCY_SUB_UNIT</b> = 0xb5, 
<b>KEYPAD_LEFT_PARENTHESIS</b> = 0xb6, 
<b>KEYPAD_RIGHT_PARENTHESIS</b> = 0xb7, 
<br />
&#160;&#160;<b>KEYPAD_LEFT_BRACE</b> = 0xb8, 
<b>KEYPAD_RIGHT_BRACE</b> = 0xb9, 
<b>KEYPAD_TAB</b> = 0xba, 
<b>KEYPAD_BACKSPACE</b> = 0xbb, 
<br />
&#160;&#160;<b>KEYPAD_A</b> = 0xbc, 
<b>KEYPAD_B</b> = 0xbd, 
<b>KEYPAD_C</b> = 0xbe, 
<b>KEYPAD_D</b> = 0xbf, 
<br />
&#160;&#160;<b>KEYPAD_E</b> = 0xc0, 
<b>KEYPAD_F</b> = 0xc1, 
<b>KEYPAD_XOR</b> = 0xc2, 
<b>KEYPAD_POWER</b> = 0xc3, 
<br />
&#160;&#160;<b>KEYPAD_PERCENT</b> = 0xc4, 
<b>KEYPAD_LESS</b> = 0xc5, 
<b>KEYPAD_GREATER</b> = 0xc6, 
<b>KEYPAD_AMPERSAND</b> = 0xc7, 
<br />
&#160;&#160;<b>KEYPAD_DOUBLE_AMPERSAND</b> = 0xc8, 
<b>KEYPAD_VERTICAL_BAR</b> = 0xc9, 
<b>KEYPAD_DOUBLE_VERTICAL_BAR</b> = 0xca, 
<b>KEYPAD_COLON</b> = 0xcb, 
<br />
&#160;&#160;<b>KEYPAD_HASH</b> = 0xcc, 
<b>KEYPAD_SPACE</b> = 0xcd, 
<b>KEYPAD_AT</b> = 0xce, 
<b>KEYPAD_EXCLAMATION</b> = 0xcf, 
<br />
&#160;&#160;<b>KEYPAD_MEM_STORE</b> = 0xd0, 
<b>KEYPAD_MEM_RECALL</b> = 0xd1, 
<b>KEYPAD_MEM_CLEAR</b> = 0xd2, 
<b>KEYPAD_MEM_ADD</b> = 0xd3, 
<br />
&#160;&#160;<b>KEYPAD_MEM_SUBTRACT</b> = 0xd4, 
<b>KEYPAD_MEM_MULTIPLY</b> = 0xd5, 
<b>KEYPAD_MEM_DIVIDE</b> = 0xd6, 
<b>KEYPAD_PLUS_MINUS</b> = 0xd7, 
<br />
&#160;&#160;<b>KEYPAD_CLEAR</b> = 0xd8, 
<b>KEYPAD_CLEAR_ENTRY</b> = 0xd9, 
<b>KEYPAD_BINARY</b> = 0xda, 
<b>KEYPAD_OCTAL</b> = 0xdb, 
<br />
&#160;&#160;<b>KEYPAD_DECIMAL</b> = 0xdc, 
<b>KEYPAD_HEXADECIMAL</b> = 0xdd, 
<b>LEFT_CONTROL</b> = 0xe0, 
<b>LEFT_SHIFT</b> = 0xe1, 
<br />
&#160;&#160;<b>LEFT_ALT</b> = 0xe2, 
<b>LEFT_META</b> = 0xe3, 
<b>RIGHT_CONTROL</b> = 0xe4, 
<b>RIGHT_SHIFT</b> = 0xe5, 
<br />
&#160;&#160;<b>RIGHT_ALT</b> = 0xe6, 
<b>RIGHT_META</b> = 0xe7, 
<b>MEDIA_PLAY_PAUSE</b> = 0xe8, 
<b>MEDIA_STOP_CD</b> = 0xe9, 
<br />
&#160;&#160;<b>MEDIA_PREVIOUS_SONG</b> = 0xea, 
<b>MEDIA_NEXT_SONG</b> = 0xeb, 
<b>MEDIA_EJECT_CD</b> = 0xec, 
<b>MEDIA_VOLUME_UP</b> = 0xed, 
<br />
&#160;&#160;<b>MEDIA_VOLUME_DOWN</b> = 0xee, 
<b>MEDIA_MUTE</b> = 0xef, 
<b>MEDIA_WWW</b> = 0xf0, 
<b>MEDIA_BACK</b> = 0xf1, 
<br />
&#160;&#160;<b>MEDIA_FORWARD</b> = 0xf2, 
<b>MEDIA_STOP</b> = 0xf3, 
<b>MEDIA_FIND</b> = 0xf4, 
<b>MEDIA_SCROLL_UP</b> = 0xf5, 
<br />
&#160;&#160;<b>MEDIA_SCROLL_DOWN</b> = 0xf6, 
<b>MEDIA_EDIT</b> = 0xf7, 
<b>MEDIA_SLEEP</b> = 0xf8, 
<b>MEDIA_COFFEE</b> = 0xf9, 
<br />
&#160;&#160;<b>MEDIA_REFRESH</b> = 0xfa, 
<b>MEDIA_CALC</b> = 0xfb, 
<b>BRIGHTNESS_DOWN</b> = 0xfc, 
<b>BRIGHTNESS_UP</b> = 0xfd, 
<br />
&#160;&#160;<b>DISPLAY_SWITCH</b> = 0xfe, 
<b>NUM_KEYS</b> = 0xff
<br />
 }</td></tr>
<tr class="separator:aad0b5de9f5c32805861bae5dda36d501"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Declaration of <a class="el" href="namespace_event.php" title="Event&#39;s API. ">Event</a>'s API's Object : Key mapping. </p>
<dl class="section author"><dt>Author</dt><dd>Louis ABEL </dd></dl>
<dl class="section date"><dt>Date</dt><dd>11/05/2019 </dd></dl>
<dl class="section copyright"><dt>Copyright</dt><dd>CC-BY-NC-SA </dd></dl>
</div><h2 class="groupheader">Enumeration Type Documentation</h2>
<a class="anchor" id="file_aad0b5de9f5c32805861bae5dda36d501"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">enum <a class="el" href="_n_r_e___keys_8hpp.php#aad0b5de9f5c32805861bae5dda36d501">NRE::Event::KeyCode</a> : unsigned char</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Regroup all key codes, derived from <a href="https://source.android.com/devices/input/keyboard-devices.html">https://source.android.com/devices/input/keyboard-devices.html</a> </p>

</div>
</div>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
