<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: /mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Event/Handler/NRE_EventHandler.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_ef68f1e1f5148ff8ef7fb1c955106c3c.php">System</a></li><li class="navelem"><a class="el" href="dir_c60d7283d11d7ab0b1fc187569b1f175.php">Event</a></li><li class="navelem"><a class="el" href="dir_4e6217b49e2a4ddba854f2766f35a2c5.php">Handler</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_EventHandler.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___event_handler_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">    #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">    #include &lt;functional&gt;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;<span class="preprocessor">    #include &lt;Header/NRE_Utility.hpp&gt;</span></div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;<span class="preprocessor">    #include &quot;../../NRE_System.hpp&quot;</span></div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;</div><div class="line"><a name="l00020"></a><span class="lineno">   20</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00025"></a><span class="lineno">   25</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_event.php">Event</a> {</div><div class="line"><a name="l00026"></a><span class="lineno">   26</span>&#160;</div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;            <span class="keyword">template</span> &lt;<span class="keyword">class</span> T&gt;</div><div class="line"><a name="l00032"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_event_1_1_event_handler.php">   32</a></span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_1_1_event_1_1_event_handler.php">EventHandler</a> : <span class="keyword">public</span> Utility::Observer {</div><div class="line"><a name="l00033"></a><span class="lineno">   33</span>&#160;                <span class="keyword">public</span> :     <span class="comment">// Fields</span></div><div class="line"><a name="l00035"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_event_1_1_event_handler.php#a42d134d1d9799590c785e70e7bac0408">   35</a></span>&#160;<span class="comment"></span>                    <span class="keyword">typedef</span> std::function&lt;bool(T&amp;)&gt; <a class="code" href="class_n_r_e_1_1_event_1_1_event_handler.php#a42d134d1d9799590c785e70e7bac0408">Handler</a>;</div><div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;</div><div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;                <span class="keyword">private</span> :    <span class="comment">// Fields</span></div><div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;                    Handler handler;    </div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;                <span class="keyword">public</span> :     <span class="comment">// Methods</span></div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_event_1_1_event_handler.php#aee18ad5984f1d4caed07c117e0ea2a71">EventHandler</a>() = <span class="keyword">delete</span>;</div><div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;                        <a class="code" href="class_n_r_e_1_1_event_1_1_event_handler.php#aee18ad5984f1d4caed07c117e0ea2a71">EventHandler</a>(Handler &amp;&amp; h);</div><div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;</div><div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;                    <span class="comment">//## Copy Constructor ##//</span></div><div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_event_1_1_event_handler.php#aee18ad5984f1d4caed07c117e0ea2a71">EventHandler</a>(<a class="code" href="class_n_r_e_1_1_event_1_1_event_handler.php">EventHandler</a> <span class="keyword">const</span>&amp; h) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;</div><div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;                    <span class="comment">//## Move Constructor ##//</span></div><div class="line"><a name="l00064"></a><span class="lineno">   64</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_event_1_1_event_handler.php#aee18ad5984f1d4caed07c117e0ea2a71">EventHandler</a>(<a class="code" href="class_n_r_e_1_1_event_1_1_event_handler.php">EventHandler</a> &amp;&amp; h) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;</div><div class="line"><a name="l00066"></a><span class="lineno">   66</span>&#160;                    <span class="comment">//## Deconstructor ##//</span></div><div class="line"><a name="l00070"></a><span class="lineno">   70</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_event_1_1_event_handler.php#a58cd2257e8bc208c70211caeff00f743">~EventHandler</a>();</div><div class="line"><a name="l00071"></a><span class="lineno">   71</span>&#160;</div><div class="line"><a name="l00072"></a><span class="lineno">   72</span>&#160;                    <span class="comment">//## Methods ##//</span></div><div class="line"><a name="l00078"></a><span class="lineno">   78</span>&#160;<span class="comment"></span>                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_event_1_1_event_handler.php#abcbd6863bc67ef68f18ed1b5b1b2e6b4">update</a>(Utility::Observable* obs, <span class="keywordtype">void</span>* arg) <span class="keyword">override</span>;</div><div class="line"><a name="l00079"></a><span class="lineno">   79</span>&#160;</div><div class="line"><a name="l00080"></a><span class="lineno">   80</span>&#160;                    <span class="comment">//## Assignment Operator ##//</span></div><div class="line"><a name="l00086"></a><span class="lineno">   86</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_event_1_1_event_handler.php">EventHandler</a>&amp; <a class="code" href="class_n_r_e_1_1_event_1_1_event_handler.php#a4d86b6a4273b93f0381fa7dab7b6abe4">operator =</a>(<a class="code" href="class_n_r_e_1_1_event_1_1_event_handler.php">EventHandler</a> <span class="keyword">const</span>&amp; h) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00092"></a><span class="lineno">   92</span>&#160;                        <a class="code" href="class_n_r_e_1_1_event_1_1_event_handler.php">EventHandler</a>&amp; <a class="code" href="class_n_r_e_1_1_event_1_1_event_handler.php#a4d86b6a4273b93f0381fa7dab7b6abe4">operator =</a>(<a class="code" href="class_n_r_e_1_1_event_1_1_event_handler.php">EventHandler</a> &amp;&amp; h) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00093"></a><span class="lineno">   93</span>&#160;            };</div><div class="line"><a name="l00094"></a><span class="lineno">   94</span>&#160;        }</div><div class="line"><a name="l00095"></a><span class="lineno">   95</span>&#160;    }</div><div class="line"><a name="l00096"></a><span class="lineno">   96</span>&#160;</div><div class="line"><a name="l00097"></a><span class="lineno">   97</span>&#160;<span class="preprocessor">    #include &quot;NRE_EventHandler.tpp&quot;</span></div><div class="ttc" id="class_n_r_e_1_1_event_1_1_event_handler_php_a4d86b6a4273b93f0381fa7dab7b6abe4"><div class="ttname"><a href="class_n_r_e_1_1_event_1_1_event_handler.php#a4d86b6a4273b93f0381fa7dab7b6abe4">NRE::Event::EventHandler::operator=</a></div><div class="ttdeci">EventHandler &amp; operator=(EventHandler const &amp;h)=delete</div></div>
<div class="ttc" id="namespace_event_php"><div class="ttname"><a href="namespace_event.php">Event</a></div><div class="ttdoc">Event&amp;#39;s API. </div></div>
<div class="ttc" id="class_n_r_e_1_1_event_1_1_event_handler_php_a42d134d1d9799590c785e70e7bac0408"><div class="ttname"><a href="class_n_r_e_1_1_event_1_1_event_handler.php#a42d134d1d9799590c785e70e7bac0408">NRE::Event::EventHandler::Handler</a></div><div class="ttdeci">std::function&lt; bool(T &amp;)&gt; Handler</div><div class="ttdef"><b>Definition:</b> NRE_EventHandler.hpp:35</div></div>
<div class="ttc" id="class_n_r_e_1_1_event_1_1_event_handler_php_abcbd6863bc67ef68f18ed1b5b1b2e6b4"><div class="ttname"><a href="class_n_r_e_1_1_event_1_1_event_handler.php#abcbd6863bc67ef68f18ed1b5b1b2e6b4">NRE::Event::EventHandler::update</a></div><div class="ttdeci">void update(Utility::Observable *obs, void *arg) override</div></div>
<div class="ttc" id="class_n_r_e_1_1_event_1_1_event_handler_php_aee18ad5984f1d4caed07c117e0ea2a71"><div class="ttname"><a href="class_n_r_e_1_1_event_1_1_event_handler.php#aee18ad5984f1d4caed07c117e0ea2a71">NRE::Event::EventHandler::EventHandler</a></div><div class="ttdeci">EventHandler()=delete</div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div></div>
<div class="ttc" id="class_n_r_e_1_1_event_1_1_event_handler_php_a58cd2257e8bc208c70211caeff00f743"><div class="ttname"><a href="class_n_r_e_1_1_event_1_1_event_handler.php#a58cd2257e8bc208c70211caeff00f743">NRE::Event::EventHandler::~EventHandler</a></div><div class="ttdeci">~EventHandler()</div></div>
<div class="ttc" id="class_n_r_e_1_1_event_1_1_event_handler_php"><div class="ttname"><a href="class_n_r_e_1_1_event_1_1_event_handler.php">NRE::Event::EventHandler</a></div><div class="ttdoc">Manage an event handler for a special type. </div><div class="ttdef"><b>Definition:</b> NRE_EventHandler.hpp:32</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
