<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: /mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Event/NRE_EventSystem.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_ef68f1e1f5148ff8ef7fb1c955106c3c.php">System</a></li><li class="navelem"><a class="el" href="dir_c60d7283d11d7ab0b1fc187569b1f175.php">Event</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_EventSystem.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___event_system_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">    #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">    #include &lt;memory&gt;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;</div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;<span class="preprocessor">    #include &quot;../Graphics/Window/NRE_Window.hpp&quot;</span></div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;<span class="preprocessor">    #include &quot;<a class="code" href="_n_r_e___input_manager_8hpp.php">Input/NRE_InputManager.hpp</a>&quot;</span></div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;<span class="preprocessor">    #include &quot;<a class="code" href="_n_r_e___event_emitter_8hpp.php">Emitter/NRE_EventEmitter.hpp</a>&quot;</span></div><div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;<span class="preprocessor">    #include &quot;<a class="code" href="_n_r_e___event_8hpp.php">Event/NRE_Event.hpp</a>&quot;</span></div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;</div><div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;<span class="preprocessor">    #include &lt;Header/NRE_Utility.hpp&gt;</span></div><div class="line"><a name="l00020"></a><span class="lineno">   20</span>&#160;</div><div class="line"><a name="l00025"></a><span class="lineno">   25</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_event.php">Event</a> {</div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;            <span class="keyword">template</span>&lt;<span class="keyword">class</span>&gt; <span class="keyword">class </span>EventHandler;</div><div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;        }</div><div class="line"><a name="l00033"></a><span class="lineno">   33</span>&#160;</div><div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_system.php">System</a> {</div><div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;</div><div class="line"><a name="l00044"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_system_1_1_event_system.php">   44</a></span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_1_1_system_1_1_event_system.php">EventSystem</a> {</div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;                <span class="keyword">private</span> :   <span class="comment">// Fields</span></div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;                    <a class="code" href="class_n_r_e_1_1_event_1_1_input_manager.php">Event::InputManager</a> inputManager;                                          </div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;                    Utility::Vector&lt;std::unique_ptr&lt;Event::AbstractEventEmitter&gt;&gt; emitters;    </div><div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;                <span class="keyword">public</span> :    <span class="comment">// Methods</span></div><div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_system_1_1_event_system.php">EventSystem</a>();</div><div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;</div><div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;                    <span class="comment">//## Copy Constructor ##//</span></div><div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_system_1_1_event_system.php">EventSystem</a>(<a class="code" href="class_n_r_e_1_1_system_1_1_event_system.php">EventSystem</a> <span class="keyword">const</span>&amp; sys) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00062"></a><span class="lineno">   62</span>&#160;</div><div class="line"><a name="l00063"></a><span class="lineno">   63</span>&#160;                    <span class="comment">//## Move Constructor ##//</span></div><div class="line"><a name="l00068"></a><span class="lineno">   68</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_system_1_1_event_system.php">EventSystem</a>(<a class="code" href="class_n_r_e_1_1_system_1_1_event_system.php">EventSystem</a> &amp;&amp; sys) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00069"></a><span class="lineno">   69</span>&#160;</div><div class="line"><a name="l00070"></a><span class="lineno">   70</span>&#160;                    <span class="comment">//## Deconstructor ##//</span></div><div class="line"><a name="l00074"></a><span class="lineno">   74</span>&#160;<span class="comment"></span>                        ~<a class="code" href="class_n_r_e_1_1_system_1_1_event_system.php">EventSystem</a>() = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00075"></a><span class="lineno">   75</span>&#160;</div><div class="line"><a name="l00076"></a><span class="lineno">   76</span>&#160;                    <span class="comment">//## Methods ##//</span></div><div class="line"><a name="l00077"></a><span class="lineno">   77</span>&#160;<span class="preprocessor">                        #ifdef _WIN32                           // Windows</span></div><div class="line"><a name="l00078"></a><span class="lineno">   78</span>&#160;</div><div class="line"><a name="l00087"></a><span class="lineno">   87</span>&#160;                            LRESULT internalDispatcher(Graphics::Id <span class="keywordtype">id</span>, HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam);</div><div class="line"><a name="l00088"></a><span class="lineno">   88</span>&#160;<span class="preprocessor">                        #elif __linux__</span></div><div class="line"><a name="l00089"></a><span class="lineno">   89</span>&#160;</div><div class="line"><a name="l00093"></a><span class="lineno">   93</span>&#160;                            <span class="keywordtype">void</span> internalDispatcher(XEvent <span class="keyword">const</span>&amp; event);</div><div class="line"><a name="l00097"></a><span class="lineno">   97</span>&#160;                            <span class="keywordtype">bool</span> hasNextEvent();</div><div class="line"><a name="l00098"></a><span class="lineno">   98</span>&#160;<span class="preprocessor">                        #endif</span></div><div class="line"><a name="l00099"></a><span class="lineno">   99</span>&#160;</div><div class="line"><a name="l00102"></a><span class="lineno">  102</span>&#160;                        <span class="keywordtype">void</span> update();</div><div class="line"><a name="l00108"></a><span class="lineno">  108</span>&#160;                        <span class="keyword">template</span> &lt;<span class="keyword">class </span>T, <span class="keyword">class </span>... Args&gt;</div><div class="line"><a name="l00109"></a><span class="lineno">  109</span>&#160;                        <span class="keywordtype">bool</span> emit(Args &amp;&amp; ... args);</div><div class="line"><a name="l00114"></a><span class="lineno">  114</span>&#160;                        <span class="keyword">template</span> &lt;<span class="keyword">class</span> T&gt;</div><div class="line"><a name="l00115"></a><span class="lineno">  115</span>&#160;                        <span class="keywordtype">void</span> addHandler(<a class="code" href="class_n_r_e_1_1_event_1_1_event_handler.php">Event::EventHandler&lt;T&gt;</a>* handler);</div><div class="line"><a name="l00120"></a><span class="lineno">  120</span>&#160;                        <span class="keyword">template</span> &lt;<span class="keyword">class</span> T&gt;</div><div class="line"><a name="l00121"></a><span class="lineno">  121</span>&#160;                        <span class="keywordtype">void</span> removeHandler(<a class="code" href="class_n_r_e_1_1_event_1_1_event_handler.php">Event::EventHandler&lt;T&gt;</a>* handler);</div><div class="line"><a name="l00125"></a><span class="lineno">  125</span>&#160;                        <span class="keyword">template</span> &lt;<span class="keyword">class</span> T&gt;</div><div class="line"><a name="l00126"></a><span class="lineno">  126</span>&#160;                        <span class="keywordtype">void</span> registerEvent();</div><div class="line"><a name="l00127"></a><span class="lineno">  127</span>&#160;</div><div class="line"><a name="l00128"></a><span class="lineno">  128</span>&#160;                    <span class="comment">//## Assignment Operator ##//</span></div><div class="line"><a name="l00134"></a><span class="lineno">  134</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_system_1_1_event_system.php">EventSystem</a>&amp; operator =(<a class="code" href="class_n_r_e_1_1_system_1_1_event_system.php">EventSystem</a> <span class="keyword">const</span>&amp; sys) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00140"></a><span class="lineno">  140</span>&#160;                        <a class="code" href="class_n_r_e_1_1_system_1_1_event_system.php">EventSystem</a>&amp; operator =(<a class="code" href="class_n_r_e_1_1_system_1_1_event_system.php">EventSystem</a> &amp;&amp; sys) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00141"></a><span class="lineno">  141</span>&#160;</div><div class="line"><a name="l00142"></a><span class="lineno">  142</span>&#160;                <span class="keyword">private</span> :   <span class="comment">// Static</span></div><div class="line"><a name="l00146"></a><span class="lineno">  146</span>&#160;<span class="comment"></span>                    <span class="keyword">template</span> &lt;<span class="keyword">class</span> T&gt;</div><div class="line"><a name="l00147"></a><span class="lineno">  147</span>&#160;                    <a class="code" href="class_n_r_e_1_1_event_1_1_event_emitter.php">Event::EventEmitter&lt;T&gt;</a>&amp; getEmitter();</div><div class="line"><a name="l00148"></a><span class="lineno">  148</span>&#160;            };</div><div class="line"><a name="l00149"></a><span class="lineno">  149</span>&#160;        }</div><div class="line"><a name="l00150"></a><span class="lineno">  150</span>&#160;    }</div><div class="line"><a name="l00151"></a><span class="lineno">  151</span>&#160;</div><div class="line"><a name="l00152"></a><span class="lineno">  152</span>&#160;<span class="preprocessor">    #include &quot;NRE_EventSystem.tpp&quot;</span></div><div class="ttc" id="class_n_r_e_1_1_system_1_1_event_system_php"><div class="ttname"><a href="class_n_r_e_1_1_system_1_1_event_system.php">NRE::System::EventSystem</a></div><div class="ttdoc">Manage the event sub system. </div><div class="ttdef"><b>Definition:</b> NRE_EventSystem.hpp:44</div></div>
<div class="ttc" id="class_n_r_e_1_1_event_1_1_input_manager_php"><div class="ttname"><a href="class_n_r_e_1_1_event_1_1_input_manager.php">NRE::Event::InputManager</a></div><div class="ttdoc">Manage the process of native input. </div><div class="ttdef"><b>Definition:</b> NRE_InputManager.hpp:42</div></div>
<div class="ttc" id="_n_r_e___input_manager_8hpp_php"><div class="ttname"><a href="_n_r_e___input_manager_8hpp.php">NRE_InputManager.hpp</a></div><div class="ttdoc">Declaration of Event&amp;#39;s API&amp;#39;s Object : InputManager. </div></div>
<div class="ttc" id="class_n_r_e_1_1_event_1_1_event_emitter_php"><div class="ttname"><a href="class_n_r_e_1_1_event_1_1_event_emitter.php">NRE::Event::EventEmitter</a></div><div class="ttdoc">Manage event emission to all listener. </div><div class="ttdef"><b>Definition:</b> NRE_EventEmitter.hpp:30</div></div>
<div class="ttc" id="namespace_event_php"><div class="ttname"><a href="namespace_event.php">Event</a></div><div class="ttdoc">Event&amp;#39;s API. </div></div>
<div class="ttc" id="namespace_system_php"><div class="ttname"><a href="namespace_system.php">System</a></div><div class="ttdoc">System&amp;#39;s API. </div></div>
<div class="ttc" id="_n_r_e___event_emitter_8hpp_php"><div class="ttname"><a href="_n_r_e___event_emitter_8hpp.php">NRE_EventEmitter.hpp</a></div><div class="ttdoc">Declaration of Event&amp;#39;s API&amp;#39;s Object : EventEmitter. </div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div></div>
<div class="ttc" id="class_n_r_e_1_1_event_1_1_event_handler_php"><div class="ttname"><a href="class_n_r_e_1_1_event_1_1_event_handler.php">NRE::Event::EventHandler</a></div><div class="ttdoc">Manage an event handler for a special type. </div><div class="ttdef"><b>Definition:</b> NRE_EventHandler.hpp:32</div></div>
<div class="ttc" id="_n_r_e___event_8hpp_php"><div class="ttname"><a href="_n_r_e___event_8hpp.php">NRE_Event.hpp</a></div><div class="ttdoc">Declaration of Event&amp;#39;s API&amp;#39;s Events. </div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
