<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: /mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Graphics/Driver/NRE_GraphicsDriver.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_ef68f1e1f5148ff8ef7fb1c955106c3c.php">System</a></li><li class="navelem"><a class="el" href="dir_13c1ecb482d2b1153b2c0856159b065a.php">Graphics</a></li><li class="navelem"><a class="el" href="dir_81cdaf72272f1029aa25cae9892e5ec5.php">Driver</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_GraphicsDriver.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___graphics_driver_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">     #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">     #include &lt;cstdlib&gt;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;<span class="preprocessor">     #include &lt;iostream&gt;</span></div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;</div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;<span class="preprocessor">     #define GLEW_STATIC</span></div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;</div><div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;<span class="preprocessor">     #ifdef GLEW_STATIC</span></div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;<span class="preprocessor">         #define GLEWAPI extern</span></div><div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;<span class="preprocessor">     #else</span></div><div class="line"><a name="l00020"></a><span class="lineno">   20</span>&#160;<span class="preprocessor">         #ifdef GLEW_BUILD</span></div><div class="line"><a name="l00021"></a><span class="lineno">   21</span>&#160;<span class="preprocessor">             #define GLEWAPI extern __declspec(dllexport)</span></div><div class="line"><a name="l00022"></a><span class="lineno">   22</span>&#160;<span class="preprocessor">         #else</span></div><div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;<span class="preprocessor">             #define GLEWAPI extern __declspec(dllimport)</span></div><div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160;<span class="preprocessor">         #endif</span></div><div class="line"><a name="l00025"></a><span class="lineno">   25</span>&#160;<span class="preprocessor">     #endif</span></div><div class="line"><a name="l00026"></a><span class="lineno">   26</span>&#160;</div><div class="line"><a name="l00027"></a><span class="lineno">   27</span>&#160;<span class="preprocessor">     #include &lt;GL/glew.h&gt;</span></div><div class="line"><a name="l00028"></a><span class="lineno">   28</span>&#160;</div><div class="line"><a name="l00029"></a><span class="lineno">   29</span>&#160;<span class="preprocessor">     #ifdef _WIN32                           // Windows</span></div><div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160;<span class="preprocessor">        #include &lt;Windows.h&gt;</span></div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;<span class="preprocessor">        #include &lt;wingdi.h&gt;</span></div><div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;<span class="preprocessor">        #include &lt;GL/wglew.h&gt;</span></div><div class="line"><a name="l00033"></a><span class="lineno">   33</span>&#160;<span class="preprocessor">     #elif __linux__                         // Linux</span></div><div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;<span class="preprocessor">        #include &lt;X11/Xlib.h&gt;</span></div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;<span class="preprocessor">        #include &lt;X11/Xatom.h&gt;</span></div><div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;<span class="preprocessor">        #include &lt;GL/glxew.h&gt;</span></div><div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;<span class="preprocessor">     #else</span></div><div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;<span class="preprocessor">        #error &quot;Not Supported Yet or Unknown compiler&quot;</span></div><div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;<span class="preprocessor">     #endif</span></div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;</div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;<span class="preprocessor">     #include &lt;Utility/UnorderedMap/NRE_UnorderedMap.hpp&gt;</span></div><div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;<span class="preprocessor">     #include &lt;Utility/Singleton/NRE_Singleton.hpp&gt;</span></div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;<span class="preprocessor">     #include &lt;Utility/Id/NRE_Id.hpp&gt;</span></div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;</div><div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;     <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;         <span class="keyword">namespace </span><a class="code" href="namespace_graphics.php">Graphics</a> {</div><div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;</div><div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;            <span class="keyword">typedef</span> std::size_t Id;</div><div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;</div><div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;<span class="preprocessor">            #ifdef _WIN32                           // Windows</span></div><div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;                <span class="keyword">typedef</span> HWND NativeWindowType;</div><div class="line"><a name="l00060"></a><span class="lineno">   60</span>&#160;<span class="preprocessor">            #elif __linux__                         // Linux</span></div><div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160;                <span class="keyword">typedef</span> Window NativeWindowType;</div><div class="line"><a name="l00062"></a><span class="lineno">   62</span>&#160;<span class="preprocessor">            #endif</span></div><div class="line"><a name="l00063"></a><span class="lineno">   63</span>&#160;</div><div class="line"><a name="l00068"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_graphics_1_1_graphics_driver.php">   68</a></span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_1_1_graphics_1_1_graphics_driver.php">GraphicsDriver</a> : <span class="keyword">public</span> Utility::Singleton&lt;GraphicsDriver&gt; {</div><div class="line"><a name="l00069"></a><span class="lineno">   69</span>&#160;                <span class="keyword">friend</span> Utility::Singleton&lt;GraphicsDriver&gt;;</div><div class="line"><a name="l00070"></a><span class="lineno">   70</span>&#160;                <span class="keyword">private</span> :   <span class="comment">// Fields</span></div><div class="line"><a name="l00071"></a><span class="lineno">   71</span>&#160;<span class="preprocessor">                    #ifdef __linux__               // Linux</span></div><div class="line"><a name="l00072"></a><span class="lineno">   72</span>&#160;                        Display* display;                                       </div><div class="line"><a name="l00073"></a><span class="lineno">   73</span>&#160;                        Atom closeAtom;                                         </div><div class="line"><a name="l00074"></a><span class="lineno">   74</span>&#160;<span class="preprocessor">                    #endif</span></div><div class="line"><a name="l00075"></a><span class="lineno">   75</span>&#160;                    Utility::UnorderedMap&lt;NativeWindowType, Id&gt; windows;        </div><div class="line"><a name="l00077"></a><span class="lineno">   77</span>&#160;                <span class="keyword">public</span> :    <span class="comment">// Methods</span></div><div class="line"><a name="l00078"></a><span class="lineno">   78</span>&#160;                    <span class="comment">//## Move Constructor ##//</span></div><div class="line"><a name="l00083"></a><span class="lineno">   83</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_graphics_1_1_graphics_driver.php">GraphicsDriver</a>(<a class="code" href="class_n_r_e_1_1_graphics_1_1_graphics_driver.php">GraphicsDriver</a> &amp;&amp; drv) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00084"></a><span class="lineno">   84</span>&#160;</div><div class="line"><a name="l00085"></a><span class="lineno">   85</span>&#160;                    <span class="comment">//## Deconstructor ##//</span></div><div class="line"><a name="l00089"></a><span class="lineno">   89</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_graphics_1_1_graphics_driver.php#a065c6b942cdb7747fd4b0f397fbe2976">~GraphicsDriver</a>();</div><div class="line"><a name="l00090"></a><span class="lineno">   90</span>&#160;</div><div class="line"><a name="l00091"></a><span class="lineno">   91</span>&#160;                    <span class="comment">//## Getter ##//</span></div><div class="line"><a name="l00092"></a><span class="lineno">   92</span>&#160;<span class="preprocessor">                        #ifdef __linux__               // Linux</span></div><div class="line"><a name="l00093"></a><span class="lineno">   93</span>&#160;</div><div class="line"><a name="l00096"></a><span class="lineno">   96</span>&#160;                            Display* getDisplay();</div><div class="line"><a name="l00100"></a><span class="lineno">  100</span>&#160;                            Atom&amp; getCloseAtom();</div><div class="line"><a name="l00101"></a><span class="lineno">  101</span>&#160;<span class="preprocessor">                        #endif</span></div><div class="line"><a name="l00102"></a><span class="lineno">  102</span>&#160;</div><div class="line"><a name="l00107"></a><span class="lineno">  107</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_graphics_1_1_graphics_driver.php#a30b763db26e35abbffd65764c13c6e63">registerWindow</a>(NativeWindowType window, Id <span class="keywordtype">id</span>);</div><div class="line"><a name="l00112"></a><span class="lineno">  112</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_graphics_1_1_graphics_driver.php#a28629d3a2e0025ff360cea6a0578f7a9">unregisterWindow</a>(NativeWindowType window);</div><div class="line"><a name="l00118"></a><span class="lineno">  118</span>&#160;                        Id <a class="code" href="class_n_r_e_1_1_graphics_1_1_graphics_driver.php#a030f91488049870b404df084c671a80a">findId</a>(NativeWindowType window) <span class="keyword">const</span>;</div><div class="line"><a name="l00119"></a><span class="lineno">  119</span>&#160;</div><div class="line"><a name="l00120"></a><span class="lineno">  120</span>&#160;                    <span class="comment">//## Assignment Operator ##//</span></div><div class="line"><a name="l00126"></a><span class="lineno">  126</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_graphics_1_1_graphics_driver.php">GraphicsDriver</a>&amp; <a class="code" href="class_n_r_e_1_1_graphics_1_1_graphics_driver.php#acccee0609eae30ac095fbe27d6598136">operator =</a>(<a class="code" href="class_n_r_e_1_1_graphics_1_1_graphics_driver.php">GraphicsDriver</a> &amp;&amp; drv) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00127"></a><span class="lineno">  127</span>&#160;</div><div class="line"><a name="l00128"></a><span class="lineno">  128</span>&#160;                <span class="keyword">private</span> :   <span class="comment">// Methods</span></div><div class="line"><a name="l00129"></a><span class="lineno">  129</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00133"></a><span class="lineno">  133</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_graphics_1_1_graphics_driver.php">GraphicsDriver</a>();</div><div class="line"><a name="l00134"></a><span class="lineno">  134</span>&#160;</div><div class="line"><a name="l00135"></a><span class="lineno">  135</span>&#160;            };</div><div class="line"><a name="l00136"></a><span class="lineno">  136</span>&#160;        }</div><div class="line"><a name="l00137"></a><span class="lineno">  137</span>&#160;    }</div><div class="line"><a name="l00138"></a><span class="lineno">  138</span>&#160;</div><div class="line"><a name="l00139"></a><span class="lineno">  139</span>&#160;<span class="preprocessor">    #include &quot;NRE_GraphicsDriver.tpp&quot;</span></div><div class="line"><a name="l00140"></a><span class="lineno">  140</span>&#160;<span class="preprocessor">    #ifdef _WIN32                           // Windows</span></div><div class="line"><a name="l00141"></a><span class="lineno">  141</span>&#160;<span class="preprocessor">        #include &quot;../../../OS/Windows/Graphics/Driver/NRE_WindowsGraphicsDriver.tpp&quot;</span></div><div class="line"><a name="l00142"></a><span class="lineno">  142</span>&#160;<span class="preprocessor">    #elif __linux__                         // Linux</span></div><div class="line"><a name="l00143"></a><span class="lineno">  143</span>&#160;<span class="preprocessor">        #include &quot;../../../OS/Linux/Graphics/Driver/NRE_LinuxGraphicsDriver.tpp&quot;</span></div><div class="line"><a name="l00144"></a><span class="lineno">  144</span>&#160;<span class="preprocessor">    #endif</span></div><div class="ttc" id="class_n_r_e_1_1_graphics_1_1_graphics_driver_php"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_graphics_driver.php">NRE::Graphics::GraphicsDriver</a></div><div class="ttdoc">Manage the os-dependant graphics driver. </div><div class="ttdef"><b>Definition:</b> NRE_GraphicsDriver.hpp:68</div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_graphics_driver_php_acccee0609eae30ac095fbe27d6598136"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_graphics_driver.php#acccee0609eae30ac095fbe27d6598136">NRE::Graphics::GraphicsDriver::operator=</a></div><div class="ttdeci">GraphicsDriver &amp; operator=(GraphicsDriver &amp;&amp;drv)=delete</div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_graphics_driver_php_a28629d3a2e0025ff360cea6a0578f7a9"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_graphics_driver.php#a28629d3a2e0025ff360cea6a0578f7a9">NRE::Graphics::GraphicsDriver::unregisterWindow</a></div><div class="ttdeci">void unregisterWindow(NativeWindowType window)</div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div></div>
<div class="ttc" id="namespace_graphics_php"><div class="ttname"><a href="namespace_graphics.php">Graphics</a></div><div class="ttdoc">Graphics&amp;#39; API. </div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_graphics_driver_php_a30b763db26e35abbffd65764c13c6e63"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_graphics_driver.php#a30b763db26e35abbffd65764c13c6e63">NRE::Graphics::GraphicsDriver::registerWindow</a></div><div class="ttdeci">void registerWindow(NativeWindowType window, Id id)</div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_graphics_driver_php_a065c6b942cdb7747fd4b0f397fbe2976"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_graphics_driver.php#a065c6b942cdb7747fd4b0f397fbe2976">NRE::Graphics::GraphicsDriver::~GraphicsDriver</a></div><div class="ttdeci">~GraphicsDriver()</div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_graphics_driver_php_a030f91488049870b404df084c671a80a"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_graphics_driver.php#a030f91488049870b404df084c671a80a">NRE::Graphics::GraphicsDriver::findId</a></div><div class="ttdeci">Id findId(NativeWindowType window) const </div><div class="ttdef"><b>Definition:</b> NRE_GraphicsDriver.cpp:15</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
