<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: /mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Application/NRE_Application.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_ef68f1e1f5148ff8ef7fb1c955106c3c.php">System</a></li><li class="navelem"><a class="el" href="dir_588b4414fd30d99aa19c4bdadd3ce084.php">Application</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_Application.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___application_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">    #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">    #include &quot;../NRE_System.hpp&quot;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;<span class="preprocessor">    #include &lt;Utility/Vector/NRE_Vector.hpp&gt;</span></div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;</div><div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_system.php">System</a> {</div><div class="line"><a name="l00025"></a><span class="lineno">   25</span>&#160;</div><div class="line"><a name="l00030"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_system_1_1_application.php">   30</a></span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_1_1_system_1_1_application.php">Application</a> {</div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;                <span class="keyword">private</span> :   <span class="comment">// Fields</span></div><div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;                    <a class="code" href="class_n_r_e_1_1_graphics_1_1_window.php">Graphics::Window</a>&amp; window;                       </div><div class="line"><a name="l00033"></a><span class="lineno">   33</span>&#160;                    Utility::Vector&lt;Utility::Observer*&gt; handlers;   </div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;                <span class="keyword">public</span> :    <span class="comment">// Methods</span></div><div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_system_1_1_application.php#a7e91b3d4219b340ff9d92e3f95c24e57">Application</a>() = <span class="keyword">delete</span>;</div><div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;                        <a class="code" href="class_n_r_e_1_1_system_1_1_application.php#a7e91b3d4219b340ff9d92e3f95c24e57">Application</a>(Utility::String <span class="keyword">const</span>&amp; title, Math::Point2D&lt;unsigned int&gt; <span class="keyword">const</span>&amp; position, Math::Vector2D&lt;unsigned int&gt; <span class="keyword">const</span>&amp; size, <span class="keywordtype">unsigned</span> <span class="keywordtype">int</span> style, <a class="code" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">Graphics::ContextAttributes</a> <span class="keyword">const</span>&amp; attr = <a class="code" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">Graphics::ContextAttributes</a>());</div><div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;                        <a class="code" href="class_n_r_e_1_1_system_1_1_application.php#a7e91b3d4219b340ff9d92e3f95c24e57">Application</a>(Utility::String <span class="keyword">const</span>&amp; title, Math::Vector2D&lt;unsigned int&gt; <span class="keyword">const</span>&amp; size, <span class="keywordtype">unsigned</span> <span class="keywordtype">int</span> style, <a class="code" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">Graphics::ContextAttributes</a> <span class="keyword">const</span>&amp; attr = <a class="code" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">Graphics::ContextAttributes</a>());</div><div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;</div><div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;                    <span class="comment">//## Copy Constructor ##//</span></div><div class="line"><a name="l00064"></a><span class="lineno">   64</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_system_1_1_application.php#a7e91b3d4219b340ff9d92e3f95c24e57">Application</a>(<a class="code" href="class_n_r_e_1_1_system_1_1_application.php">Application</a> <span class="keyword">const</span>&amp; app) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;</div><div class="line"><a name="l00066"></a><span class="lineno">   66</span>&#160;                    <span class="comment">//## Move Constructor ##//</span></div><div class="line"><a name="l00071"></a><span class="lineno">   71</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_system_1_1_application.php#a7e91b3d4219b340ff9d92e3f95c24e57">Application</a>(<a class="code" href="class_n_r_e_1_1_system_1_1_application.php">Application</a> &amp;&amp; app) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00072"></a><span class="lineno">   72</span>&#160;</div><div class="line"><a name="l00073"></a><span class="lineno">   73</span>&#160;                    <span class="comment">//## Deconstructor ##//</span></div><div class="line"><a name="l00077"></a><span class="lineno">   77</span>&#160;<span class="comment"></span>                        <span class="keyword">virtual</span> <a class="code" href="class_n_r_e_1_1_system_1_1_application.php#a9fcb9646e9736afa161f41ca11581835">~Application</a>();</div><div class="line"><a name="l00078"></a><span class="lineno">   78</span>&#160;</div><div class="line"><a name="l00079"></a><span class="lineno">   79</span>&#160;                    <span class="comment">//## Methods ##//</span></div><div class="line"><a name="l00083"></a><span class="lineno">   83</span>&#160;<span class="comment"></span>                        <span class="keyword">virtual</span> <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_system_1_1_application.php#ae260cd0edfb36c05366f227de079e986">create</a>() = 0;</div><div class="line"><a name="l00087"></a><span class="lineno">   87</span>&#160;                        <span class="keyword">virtual</span> <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_system_1_1_application.php#a99093f5efe59dab4c5be09df98b42481">update</a>() = 0;</div><div class="line"><a name="l00091"></a><span class="lineno">   91</span>&#160;                        <span class="keyword">virtual</span> <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_system_1_1_application.php#ae538f4a0b860650369a8af2af5135e9e">render</a>() = 0;</div><div class="line"><a name="l00095"></a><span class="lineno">   95</span>&#160;                        <span class="keyword">virtual</span> <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_system_1_1_application.php#add0eae3e71241478586e6781d6ddd327">destroy</a>() = 0;</div><div class="line"><a name="l00100"></a><span class="lineno">  100</span>&#160;                        <span class="keyword">template</span> &lt;<span class="keyword">class</span> T&gt;</div><div class="line"><a name="l00101"></a><span class="lineno">  101</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_system_1_1_application.php#a6f7a8eb37b949821baac564f043760d1">addHandler</a>(<span class="keyword">typename</span> <a class="code" href="class_n_r_e_1_1_event_1_1_event_handler.php#a42d134d1d9799590c785e70e7bac0408">Event::EventHandler&lt;T&gt;::Handler</a> &amp;&amp; handler);</div><div class="line"><a name="l00105"></a><span class="lineno">  105</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_system_1_1_application.php#a3f0bcb146c0f1f64155718618f6c9dce">NREmain</a>();</div><div class="line"><a name="l00106"></a><span class="lineno">  106</span>&#160;</div><div class="line"><a name="l00107"></a><span class="lineno">  107</span>&#160;                    <span class="comment">//## Assignment Operator ##//</span></div><div class="line"><a name="l00113"></a><span class="lineno">  113</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_system_1_1_application.php">Application</a>&amp; <a class="code" href="class_n_r_e_1_1_system_1_1_application.php#a91a31e944a7767fe6c75579370dc9fda">operator =</a>(<a class="code" href="class_n_r_e_1_1_system_1_1_application.php">Application</a> <span class="keyword">const</span>&amp; app) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00119"></a><span class="lineno">  119</span>&#160;                        <a class="code" href="class_n_r_e_1_1_system_1_1_application.php">Application</a>&amp; <a class="code" href="class_n_r_e_1_1_system_1_1_application.php#a91a31e944a7767fe6c75579370dc9fda">operator =</a>(<a class="code" href="class_n_r_e_1_1_system_1_1_application.php">Application</a> &amp;&amp; app) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00120"></a><span class="lineno">  120</span>&#160;</div><div class="line"><a name="l00121"></a><span class="lineno">  121</span>&#160;            };</div><div class="line"><a name="l00122"></a><span class="lineno">  122</span>&#160;</div><div class="line"><a name="l00123"></a><span class="lineno">  123</span>&#160;        }</div><div class="line"><a name="l00124"></a><span class="lineno">  124</span>&#160;    }</div><div class="line"><a name="l00125"></a><span class="lineno">  125</span>&#160;</div><div class="line"><a name="l00126"></a><span class="lineno">  126</span>&#160;<span class="preprocessor">    #include &quot;NRE_Application.tpp&quot;</span></div><div class="ttc" id="class_n_r_e_1_1_graphics_1_1_window_php"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_window.php">NRE::Graphics::Window</a></div><div class="ttdoc">Manage a graphics window. </div><div class="ttdef"><b>Definition:</b> NRE_Window.hpp:34</div></div>
<div class="ttc" id="class_n_r_e_1_1_system_1_1_application_php_a91a31e944a7767fe6c75579370dc9fda"><div class="ttname"><a href="class_n_r_e_1_1_system_1_1_application.php#a91a31e944a7767fe6c75579370dc9fda">NRE::System::Application::operator=</a></div><div class="ttdeci">Application &amp; operator=(Application const &amp;app)=delete</div></div>
<div class="ttc" id="class_n_r_e_1_1_system_1_1_application_php_a3f0bcb146c0f1f64155718618f6c9dce"><div class="ttname"><a href="class_n_r_e_1_1_system_1_1_application.php#a3f0bcb146c0f1f64155718618f6c9dce">NRE::System::Application::NREmain</a></div><div class="ttdeci">void NREmain()</div></div>
<div class="ttc" id="class_n_r_e_1_1_system_1_1_application_php_a99093f5efe59dab4c5be09df98b42481"><div class="ttname"><a href="class_n_r_e_1_1_system_1_1_application.php#a99093f5efe59dab4c5be09df98b42481">NRE::System::Application::update</a></div><div class="ttdeci">virtual void update()=0</div></div>
<div class="ttc" id="class_n_r_e_1_1_system_1_1_application_php_ae538f4a0b860650369a8af2af5135e9e"><div class="ttname"><a href="class_n_r_e_1_1_system_1_1_application.php#ae538f4a0b860650369a8af2af5135e9e">NRE::System::Application::render</a></div><div class="ttdeci">virtual void render()=0</div></div>
<div class="ttc" id="class_n_r_e_1_1_event_1_1_event_handler_php_a42d134d1d9799590c785e70e7bac0408"><div class="ttname"><a href="class_n_r_e_1_1_event_1_1_event_handler.php#a42d134d1d9799590c785e70e7bac0408">NRE::Event::EventHandler::Handler</a></div><div class="ttdeci">std::function&lt; bool(T &amp;)&gt; Handler</div><div class="ttdef"><b>Definition:</b> NRE_EventHandler.hpp:35</div></div>
<div class="ttc" id="class_n_r_e_1_1_system_1_1_application_php"><div class="ttname"><a href="class_n_r_e_1_1_system_1_1_application.php">NRE::System::Application</a></div><div class="ttdoc">Manage an user application. </div><div class="ttdef"><b>Definition:</b> NRE_Application.hpp:30</div></div>
<div class="ttc" id="class_n_r_e_1_1_system_1_1_application_php_a9fcb9646e9736afa161f41ca11581835"><div class="ttname"><a href="class_n_r_e_1_1_system_1_1_application.php#a9fcb9646e9736afa161f41ca11581835">NRE::System::Application::~Application</a></div><div class="ttdeci">virtual ~Application()</div></div>
<div class="ttc" id="class_n_r_e_1_1_system_1_1_application_php_a6f7a8eb37b949821baac564f043760d1"><div class="ttname"><a href="class_n_r_e_1_1_system_1_1_application.php#a6f7a8eb37b949821baac564f043760d1">NRE::System::Application::addHandler</a></div><div class="ttdeci">void addHandler(typename Event::EventHandler&lt; T &gt;::Handler &amp;&amp;handler)</div></div>
<div class="ttc" id="class_n_r_e_1_1_system_1_1_application_php_ae260cd0edfb36c05366f227de079e986"><div class="ttname"><a href="class_n_r_e_1_1_system_1_1_application.php#ae260cd0edfb36c05366f227de079e986">NRE::System::Application::create</a></div><div class="ttdeci">virtual void create()=0</div></div>
<div class="ttc" id="namespace_system_php"><div class="ttname"><a href="namespace_system.php">System</a></div><div class="ttdoc">System&amp;#39;s API. </div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div></div>
<div class="ttc" id="class_n_r_e_1_1_system_1_1_application_php_add0eae3e71241478586e6781d6ddd327"><div class="ttname"><a href="class_n_r_e_1_1_system_1_1_application.php#add0eae3e71241478586e6781d6ddd327">NRE::System::Application::destroy</a></div><div class="ttdeci">virtual void destroy()=0</div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_context_attributes_php"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">NRE::Graphics::ContextAttributes</a></div><div class="ttdoc">Regroup all attributes needed in a GL context, should be modified before creation. </div><div class="ttdef"><b>Definition:</b> NRE_ContextAttributes.hpp:52</div></div>
<div class="ttc" id="class_n_r_e_1_1_system_1_1_application_php_a7e91b3d4219b340ff9d92e3f95c24e57"><div class="ttname"><a href="class_n_r_e_1_1_system_1_1_application.php#a7e91b3d4219b340ff9d92e3f95c24e57">NRE::System::Application::Application</a></div><div class="ttdeci">Application()=delete</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
