<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: /mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Graphics/NRE_GraphicsSystem.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_ef68f1e1f5148ff8ef7fb1c955106c3c.php">System</a></li><li class="navelem"><a class="el" href="dir_13c1ecb482d2b1153b2c0856159b065a.php">Graphics</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_GraphicsSystem.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___graphics_system_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">    #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">    #include &quot;<a class="code" href="_n_r_e___window_8hpp.php">Window/NRE_Window.hpp</a>&quot;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;</div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;<span class="preprocessor">    #include &lt;Utility/String/NRE_String.hpp&gt;</span></div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;<span class="preprocessor">    #include &lt;Utility/UnorderedMap/NRE_UnorderedMap.hpp&gt;</span></div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;</div><div class="line"><a name="l00021"></a><span class="lineno">   21</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00026"></a><span class="lineno">   26</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_system.php">System</a> {</div><div class="line"><a name="l00027"></a><span class="lineno">   27</span>&#160;</div><div class="line"><a name="l00032"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_system_1_1_graphics_system.php">   32</a></span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_1_1_system_1_1_graphics_system.php">GraphicsSystem</a> {</div><div class="line"><a name="l00033"></a><span class="lineno">   33</span>&#160;                <span class="keyword">private</span> :   <span class="comment">// Fields</span></div><div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;                    Utility::UnorderedMap&lt;Graphics::Id, Graphics::Window*&gt; windows;  </div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;                    Graphics::Id counter;                                            </div><div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;                    <span class="keywordtype">bool</span> running;                                                    </div><div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;                <span class="keyword">public</span> :    <span class="comment">// Methods</span></div><div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_system_1_1_graphics_system.php#a21c1ed2d8e7e7749616afa84c0c99dc1">GraphicsSystem</a>();</div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;</div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;                    <span class="comment">//## Copy Constructor ##//</span></div><div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_system_1_1_graphics_system.php#a21c1ed2d8e7e7749616afa84c0c99dc1">GraphicsSystem</a>(<a class="code" href="class_n_r_e_1_1_system_1_1_graphics_system.php">GraphicsSystem</a> <span class="keyword">const</span>&amp; sys) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;</div><div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;                    <span class="comment">//## Move Constructor ##//</span></div><div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_system_1_1_graphics_system.php#a21c1ed2d8e7e7749616afa84c0c99dc1">GraphicsSystem</a>(<a class="code" href="class_n_r_e_1_1_system_1_1_graphics_system.php">GraphicsSystem</a> &amp;&amp; sys) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;</div><div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;                    <span class="comment">//## Deconstructor ##//</span></div><div class="line"><a name="l00063"></a><span class="lineno">   63</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_system_1_1_graphics_system.php#a14000797c1edf260675cf16a70276df5">~GraphicsSystem</a>();</div><div class="line"><a name="l00064"></a><span class="lineno">   64</span>&#160;</div><div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;                    <span class="comment">//## Getter ##//</span></div><div class="line"><a name="l00071"></a><span class="lineno">   71</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_graphics_1_1_window.php">Graphics::Window</a>&amp; <a class="code" href="class_n_r_e_1_1_system_1_1_graphics_system.php#ac856987f85e1c7f3ceb17075b9fa0845">getWindow</a>(Graphics::Id <span class="keywordtype">id</span>);</div><div class="line"><a name="l00076"></a><span class="lineno">   76</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_system_1_1_graphics_system.php#a10e0a93d4f756515711c309550ee4099">closeWindow</a>(Graphics::Id <span class="keywordtype">id</span>);</div><div class="line"><a name="l00080"></a><span class="lineno">   80</span>&#160;                        <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_1_1_system_1_1_graphics_system.php#ae73e6260470cf6d4afac187cba4e431c">isRunning</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00081"></a><span class="lineno">   81</span>&#160;</div><div class="line"><a name="l00082"></a><span class="lineno">   82</span>&#160;                    <span class="comment">//## Methods ##//</span></div><div class="line"><a name="l00092"></a><span class="lineno">   92</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_graphics_1_1_window.php">Graphics::Window</a>&amp; <a class="code" href="class_n_r_e_1_1_system_1_1_graphics_system.php#a4f3eafe115b1516f039e8a537caf83b0">createWindow</a>(Utility::String <span class="keyword">const</span>&amp; title, Math::Point2D&lt;unsigned int&gt; <span class="keyword">const</span>&amp; position, Math::Vector2D&lt;unsigned int&gt; <span class="keyword">const</span>&amp; size, <span class="keywordtype">unsigned</span> <span class="keywordtype">int</span> style, <a class="code" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">Graphics::ContextAttributes</a> <span class="keyword">const</span>&amp; attr);</div><div class="line"><a name="l00101"></a><span class="lineno">  101</span>&#160;                        <a class="code" href="class_n_r_e_1_1_graphics_1_1_window.php">Graphics::Window</a>&amp; <a class="code" href="class_n_r_e_1_1_system_1_1_graphics_system.php#a4f3eafe115b1516f039e8a537caf83b0">createWindow</a>(Utility::String <span class="keyword">const</span>&amp; title, Math::Vector2D&lt;unsigned int&gt; <span class="keyword">const</span>&amp; size, <span class="keywordtype">unsigned</span> <span class="keywordtype">int</span> style, <a class="code" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">Graphics::ContextAttributes</a> <span class="keyword">const</span>&amp; attr);</div><div class="line"><a name="l00106"></a><span class="lineno">  106</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_system_1_1_graphics_system.php#a8a743aa5637475cf7203cba2c6621d49">removeWindow</a>(Graphics::Id <span class="keyword">const</span>&amp; <span class="keywordtype">id</span>);</div><div class="line"><a name="l00107"></a><span class="lineno">  107</span>&#160;</div><div class="line"><a name="l00108"></a><span class="lineno">  108</span>&#160;                    <span class="comment">//## Assignment Operator ##//</span></div><div class="line"><a name="l00114"></a><span class="lineno">  114</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_system_1_1_graphics_system.php">GraphicsSystem</a>&amp; <a class="code" href="class_n_r_e_1_1_system_1_1_graphics_system.php#a90ef417cfe165ad559a7cdcbfb333b25">operator =</a>(<a class="code" href="class_n_r_e_1_1_system_1_1_graphics_system.php">GraphicsSystem</a> <span class="keyword">const</span>&amp; sys) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00120"></a><span class="lineno">  120</span>&#160;                        <a class="code" href="class_n_r_e_1_1_system_1_1_graphics_system.php">GraphicsSystem</a>&amp; <a class="code" href="class_n_r_e_1_1_system_1_1_graphics_system.php#a90ef417cfe165ad559a7cdcbfb333b25">operator =</a>(<a class="code" href="class_n_r_e_1_1_system_1_1_graphics_system.php">GraphicsSystem</a> &amp;&amp; sys) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00121"></a><span class="lineno">  121</span>&#160;</div><div class="line"><a name="l00122"></a><span class="lineno">  122</span>&#160;                <span class="keyword">private</span> :   <span class="comment">// Methods</span></div><div class="line"><a name="l00126"></a><span class="lineno">  126</span>&#160;<span class="comment"></span>                    <span class="keywordtype">void</span> checkRunningState();</div><div class="line"><a name="l00127"></a><span class="lineno">  127</span>&#160;            };</div><div class="line"><a name="l00128"></a><span class="lineno">  128</span>&#160;        }</div><div class="line"><a name="l00129"></a><span class="lineno">  129</span>&#160;    }</div><div class="line"><a name="l00130"></a><span class="lineno">  130</span>&#160;</div><div class="line"><a name="l00131"></a><span class="lineno">  131</span>&#160;<span class="preprocessor">    #include &quot;NRE_GraphicsSystem.tpp&quot;</span></div><div class="ttc" id="class_n_r_e_1_1_graphics_1_1_window_php"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_window.php">NRE::Graphics::Window</a></div><div class="ttdoc">Manage a graphics window. </div><div class="ttdef"><b>Definition:</b> NRE_Window.hpp:34</div></div>
<div class="ttc" id="class_n_r_e_1_1_system_1_1_graphics_system_php_a10e0a93d4f756515711c309550ee4099"><div class="ttname"><a href="class_n_r_e_1_1_system_1_1_graphics_system.php#a10e0a93d4f756515711c309550ee4099">NRE::System::GraphicsSystem::closeWindow</a></div><div class="ttdeci">void closeWindow(Graphics::Id id)</div><div class="ttdef"><b>Definition:</b> NRE_GraphicsSystem.cpp:25</div></div>
<div class="ttc" id="class_n_r_e_1_1_system_1_1_graphics_system_php_ac856987f85e1c7f3ceb17075b9fa0845"><div class="ttname"><a href="class_n_r_e_1_1_system_1_1_graphics_system.php#ac856987f85e1c7f3ceb17075b9fa0845">NRE::System::GraphicsSystem::getWindow</a></div><div class="ttdeci">Graphics::Window &amp; getWindow(Graphics::Id id)</div></div>
<div class="ttc" id="class_n_r_e_1_1_system_1_1_graphics_system_php"><div class="ttname"><a href="class_n_r_e_1_1_system_1_1_graphics_system.php">NRE::System::GraphicsSystem</a></div><div class="ttdoc">Manage the graphics sub system. </div><div class="ttdef"><b>Definition:</b> NRE_GraphicsSystem.hpp:32</div></div>
<div class="ttc" id="namespace_system_php"><div class="ttname"><a href="namespace_system.php">System</a></div><div class="ttdoc">System&amp;#39;s API. </div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div></div>
<div class="ttc" id="class_n_r_e_1_1_system_1_1_graphics_system_php_a21c1ed2d8e7e7749616afa84c0c99dc1"><div class="ttname"><a href="class_n_r_e_1_1_system_1_1_graphics_system.php#a21c1ed2d8e7e7749616afa84c0c99dc1">NRE::System::GraphicsSystem::GraphicsSystem</a></div><div class="ttdeci">GraphicsSystem()</div></div>
<div class="ttc" id="_n_r_e___window_8hpp_php"><div class="ttname"><a href="_n_r_e___window_8hpp.php">NRE_Window.hpp</a></div><div class="ttdoc">Declaration of Graphics&amp;#39;s API&amp;#39;s Object : Window. </div></div>
<div class="ttc" id="class_n_r_e_1_1_system_1_1_graphics_system_php_a4f3eafe115b1516f039e8a537caf83b0"><div class="ttname"><a href="class_n_r_e_1_1_system_1_1_graphics_system.php#a4f3eafe115b1516f039e8a537caf83b0">NRE::System::GraphicsSystem::createWindow</a></div><div class="ttdeci">Graphics::Window &amp; createWindow(Utility::String const &amp;title, Math::Point2D&lt; unsigned int &gt; const &amp;position, Math::Vector2D&lt; unsigned int &gt; const &amp;size, unsigned int style, Graphics::ContextAttributes const &amp;attr)</div></div>
<div class="ttc" id="class_n_r_e_1_1_system_1_1_graphics_system_php_a8a743aa5637475cf7203cba2c6621d49"><div class="ttname"><a href="class_n_r_e_1_1_system_1_1_graphics_system.php#a8a743aa5637475cf7203cba2c6621d49">NRE::System::GraphicsSystem::removeWindow</a></div><div class="ttdeci">void removeWindow(Graphics::Id const &amp;id)</div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_context_attributes_php"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">NRE::Graphics::ContextAttributes</a></div><div class="ttdoc">Regroup all attributes needed in a GL context, should be modified before creation. </div><div class="ttdef"><b>Definition:</b> NRE_ContextAttributes.hpp:52</div></div>
<div class="ttc" id="class_n_r_e_1_1_system_1_1_graphics_system_php_ae73e6260470cf6d4afac187cba4e431c"><div class="ttname"><a href="class_n_r_e_1_1_system_1_1_graphics_system.php#ae73e6260470cf6d4afac187cba4e431c">NRE::System::GraphicsSystem::isRunning</a></div><div class="ttdeci">bool isRunning() const </div></div>
<div class="ttc" id="class_n_r_e_1_1_system_1_1_graphics_system_php_a14000797c1edf260675cf16a70276df5"><div class="ttname"><a href="class_n_r_e_1_1_system_1_1_graphics_system.php#a14000797c1edf260675cf16a70276df5">NRE::System::GraphicsSystem::~GraphicsSystem</a></div><div class="ttdeci">~GraphicsSystem()</div><div class="ttdef"><b>Definition:</b> NRE_GraphicsSystem.cpp:19</div></div>
<div class="ttc" id="class_n_r_e_1_1_system_1_1_graphics_system_php_a90ef417cfe165ad559a7cdcbfb333b25"><div class="ttname"><a href="class_n_r_e_1_1_system_1_1_graphics_system.php#a90ef417cfe165ad559a7cdcbfb333b25">NRE::System::GraphicsSystem::operator=</a></div><div class="ttdeci">GraphicsSystem &amp; operator=(GraphicsSystem const &amp;sys)=delete</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
