<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: /mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Graphics/Driver/Context/Attributes/NRE_ContextAttributes.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_ef68f1e1f5148ff8ef7fb1c955106c3c.php">System</a></li><li class="navelem"><a class="el" href="dir_13c1ecb482d2b1153b2c0856159b065a.php">Graphics</a></li><li class="navelem"><a class="el" href="dir_81cdaf72272f1029aa25cae9892e5ec5.php">Driver</a></li><li class="navelem"><a class="el" href="dir_1477e6a23db3f04bafbf815d517a2f44.php">Context</a></li><li class="navelem"><a class="el" href="dir_1b663ed7aa3bcd7e6c59d81ea34b4049.php">Attributes</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_ContextAttributes.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___context_attributes_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">     #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">     #include &lt;Utility/Array/NRE_Array.hpp&gt;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;</div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;     <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;         <span class="keyword">namespace </span><a class="code" href="namespace_graphics.php">Graphics</a> {</div><div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160;</div><div class="line"><a name="l00029"></a><span class="lineno"><a class="line" href="_n_r_e___context_attributes_8hpp.php#a8eaf2bb29661035844777e583db8b899">   29</a></span>&#160;            <span class="keyword">enum class</span> <a class="code" href="_n_r_e___context_attributes_8hpp.php#a8eaf2bb29661035844777e583db8b899">GLAttributes</a> : int {</div><div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160;                RED_SIZE,               </div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;                GREEN_SIZE,             </div><div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;                BLUE_SIZE,              </div><div class="line"><a name="l00033"></a><span class="lineno">   33</span>&#160;                ALPHA_SIZE,             </div><div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;                BUFFER_SIZE,            </div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;                DOUBLEBUFFER,           </div><div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;                DEPTH_SIZE,             </div><div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;                STENCIL_SIZE,           </div><div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;                STEREO,                 </div><div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;                MULTISAMPLE_BUFFERS,    </div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;                MULTISAMPLE_SAMPLES,    </div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;                ACCELERATED_VISUAL,     </div><div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;                MAJOR_VERSION,          </div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;                MINOR_VERSION,          </div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;                NUM_ATTRIBUTES          <span class="comment">/*&lt; The number of attributes */</span></div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;            };</div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;</div><div class="line"><a name="l00052"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">   52</a></span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">ContextAttributes</a> {</div><div class="line"><a name="l00053"></a><span class="lineno">   53</span>&#160;                <span class="keyword">private</span> :   <span class="comment">// Fields</span></div><div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;                    Utility::Array&lt;int, static_cast &lt;std::size_t&gt; (GLAttributes::NUM_ATTRIBUTES)&gt; attributes;   </div><div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;                <span class="keyword">public</span> :    <span class="comment">// Methods</span></div><div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">ContextAttributes</a>();</div><div class="line"><a name="l00066"></a><span class="lineno">   66</span>&#160;                        <a class="code" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">ContextAttributes</a>(std::initializer_list&lt;int&gt; list);</div><div class="line"><a name="l00067"></a><span class="lineno">   67</span>&#160;</div><div class="line"><a name="l00068"></a><span class="lineno">   68</span>&#160;                    <span class="comment">//## Copy Constructor ##//</span></div><div class="line"><a name="l00073"></a><span class="lineno">   73</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">ContextAttributes</a>(<a class="code" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">ContextAttributes</a> <span class="keyword">const</span>&amp; attr) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00074"></a><span class="lineno">   74</span>&#160;</div><div class="line"><a name="l00075"></a><span class="lineno">   75</span>&#160;                    <span class="comment">//## Move Constructor ##//</span></div><div class="line"><a name="l00080"></a><span class="lineno">   80</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">ContextAttributes</a>(<a class="code" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">ContextAttributes</a> &amp;&amp; attr) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00081"></a><span class="lineno">   81</span>&#160;</div><div class="line"><a name="l00082"></a><span class="lineno">   82</span>&#160;                    <span class="comment">//## Deconstructor ##//</span></div><div class="line"><a name="l00086"></a><span class="lineno">   86</span>&#160;<span class="comment"></span>                        ~<a class="code" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">ContextAttributes</a>() = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00087"></a><span class="lineno">   87</span>&#160;</div><div class="line"><a name="l00088"></a><span class="lineno">   88</span>&#160;                    <span class="comment">//## Access Operator ##//</span></div><div class="line"><a name="l00094"></a><span class="lineno">   94</span>&#160;<span class="comment"></span>                        <span class="keywordtype">int</span>&amp; operator[](<a class="code" href="_n_r_e___context_attributes_8hpp.php#a8eaf2bb29661035844777e583db8b899">GLAttributes</a> index);</div><div class="line"><a name="l00100"></a><span class="lineno">  100</span>&#160;                        <span class="keywordtype">int</span> <span class="keyword">const</span>&amp; operator[](<a class="code" href="_n_r_e___context_attributes_8hpp.php#a8eaf2bb29661035844777e583db8b899">GLAttributes</a> index) <span class="keyword">const</span>;</div><div class="line"><a name="l00101"></a><span class="lineno">  101</span>&#160;</div><div class="line"><a name="l00102"></a><span class="lineno">  102</span>&#160;                    <span class="comment">//## Assignment Operator ##//</span></div><div class="line"><a name="l00108"></a><span class="lineno">  108</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">ContextAttributes</a>&amp; operator =(<a class="code" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">ContextAttributes</a> <span class="keyword">const</span>&amp; attr) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00114"></a><span class="lineno">  114</span>&#160;                        <a class="code" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">ContextAttributes</a>&amp; operator =(<a class="code" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">ContextAttributes</a> &amp;&amp; attr) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00115"></a><span class="lineno">  115</span>&#160;</div><div class="line"><a name="l00116"></a><span class="lineno">  116</span>&#160;            };</div><div class="line"><a name="l00117"></a><span class="lineno">  117</span>&#160;</div><div class="line"><a name="l00118"></a><span class="lineno">  118</span>&#160;         }</div><div class="line"><a name="l00119"></a><span class="lineno">  119</span>&#160;     }</div><div class="line"><a name="l00120"></a><span class="lineno">  120</span>&#160;</div><div class="line"><a name="l00121"></a><span class="lineno">  121</span>&#160;<span class="preprocessor">     #include &quot;NRE_ContextAttributes.tpp&quot;</span></div><div class="ttc" id="_n_r_e___context_attributes_8hpp_php_a8eaf2bb29661035844777e583db8b899"><div class="ttname"><a href="_n_r_e___context_attributes_8hpp.php#a8eaf2bb29661035844777e583db8b899">NRE::Graphics::GLAttributes</a></div><div class="ttdeci">GLAttributes</div><div class="ttdoc">Regroup all attributes that the user can modiy before create a GL context. </div><div class="ttdef"><b>Definition:</b> NRE_ContextAttributes.hpp:29</div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div></div>
<div class="ttc" id="namespace_graphics_php"><div class="ttname"><a href="namespace_graphics.php">Graphics</a></div><div class="ttdoc">Graphics&amp;#39; API. </div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_context_attributes_php"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">NRE::Graphics::ContextAttributes</a></div><div class="ttdoc">Regroup all attributes needed in a GL context, should be modified before creation. </div><div class="ttdef"><b>Definition:</b> NRE_ContextAttributes.hpp:52</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
