<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: /mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Event/Input/NRE_InputManager.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_ef68f1e1f5148ff8ef7fb1c955106c3c.php">System</a></li><li class="navelem"><a class="el" href="dir_c60d7283d11d7ab0b1fc187569b1f175.php">Event</a></li><li class="navelem"><a class="el" href="dir_d92417724dfd51f842fe3a3ba51d06cc.php">Input</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_InputManager.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___input_manager_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">    #include &lt;vector&gt;</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;<span class="preprocessor">    #include &lt;Header/NRE_Math.hpp&gt;</span></div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">    #include &lt;Header/NRE_Utility.hpp&gt;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;</div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;<span class="preprocessor">    #ifdef _WIN32                           // Windows</span></div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;<span class="preprocessor">        #include &quot;../../../OS/Windows/Event/Input/Keys/NRE_WindowsKeyTranslater.hpp&quot;</span></div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;<span class="preprocessor">    #elif __linux__                         // Linux</span></div><div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;<span class="preprocessor">        #include &quot;../../../OS/Linux/Event/Input/Keys/NRE_LinuxKeyTranslater.hpp&quot;</span></div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;<span class="preprocessor">    #else</span></div><div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;<span class="preprocessor">       #error &quot;Not Supported Yet or Unknown compiler&quot;</span></div><div class="line"><a name="l00020"></a><span class="lineno">   20</span>&#160;<span class="preprocessor">    #endif</span></div><div class="line"><a name="l00021"></a><span class="lineno">   21</span>&#160;</div><div class="line"><a name="l00022"></a><span class="lineno">   22</span>&#160;</div><div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;<span class="preprocessor">    #include &quot;../Event/NRE_Event.hpp&quot;</span></div><div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160;</div><div class="line"><a name="l00025"></a><span class="lineno">   25</span>&#160;<span class="preprocessor">    #pragma once</span></div><div class="line"><a name="l00026"></a><span class="lineno">   26</span>&#160;</div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_event.php">Event</a> {</div><div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;</div><div class="line"><a name="l00042"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_event_1_1_input_manager.php">   42</a></span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_1_1_event_1_1_input_manager.php">InputManager</a> {</div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;                <span class="keyword">private</span> :   <span class="comment">// Fields</span></div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;                    <a class="code" href="class_n_r_e_1_1_event_1_1_key_translater.php">KeyTranslater</a> keyTranslater;         </div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;                    Utility::Vector&lt;KeyCode&gt; keys;                </div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;                    Utility::Vector&lt;ButtonEventData&gt; buttons;     </div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;                <span class="keyword">public</span> :    <span class="comment">// Methods</span></div><div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;                    <span class="comment">//## Getter ##//</span></div><div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;<span class="comment"></span>                        <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_1_1_event_1_1_input_manager.php#aa8d6f2d0d14b9b1fde715c9a0e496656">isKeyPressed</a>(<a class="code" href="_n_r_e___keys_8hpp.php#aad0b5de9f5c32805861bae5dda36d501">KeyCode</a> code) <span class="keyword">const</span>;</div><div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160;                        <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_1_1_event_1_1_input_manager.php#af27a0330fff81319a4a19fe1b5dfb627">isButtonPressed</a>(<a class="code" href="_n_r_e___buttons_8hpp.php#a3117cef30b4eed21ee57db72bd9d3ef8">ButtonCode</a> code) <span class="keyword">const</span>;</div><div class="line"><a name="l00062"></a><span class="lineno">   62</span>&#160;</div><div class="line"><a name="l00063"></a><span class="lineno">   63</span>&#160;                    <span class="comment">//## Methods ##//</span></div><div class="line"><a name="l00064"></a><span class="lineno">   64</span>&#160;<span class="preprocessor">                        #ifdef _WIN32                           // Windows</span></div><div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;</div><div class="line"><a name="l00071"></a><span class="lineno">   71</span>&#160;                            <a class="code" href="_n_r_e___keys_8hpp.php#aad0b5de9f5c32805861bae5dda36d501">KeyCode</a> translateKey(WPARAM wParam, LPARAM lParam) <span class="keyword">const</span>;</div><div class="line"><a name="l00077"></a><span class="lineno">   77</span>&#160;                            <a class="code" href="_n_r_e___buttons_8hpp.php#a3117cef30b4eed21ee57db72bd9d3ef8">ButtonCode</a> translateButton(WPARAM wParam) <span class="keyword">const</span>;</div><div class="line"><a name="l00078"></a><span class="lineno">   78</span>&#160;<span class="preprocessor">                        #elif __linux__                         // Linux</span></div><div class="line"><a name="l00079"></a><span class="lineno">   79</span>&#160;</div><div class="line"><a name="l00084"></a><span class="lineno">   84</span>&#160;                            <a class="code" href="_n_r_e___keys_8hpp.php#aad0b5de9f5c32805861bae5dda36d501">KeyCode</a> translateKey(XKeyEvent <span class="keyword">const</span>&amp; keyEvent) <span class="keyword">const</span>;</div><div class="line"><a name="l00090"></a><span class="lineno">   90</span>&#160;                            <a class="code" href="_n_r_e___buttons_8hpp.php#a3117cef30b4eed21ee57db72bd9d3ef8">ButtonCode</a> translateButton(XButtonEvent <span class="keyword">const</span>&amp; buttonEvent) <span class="keyword">const</span>;</div><div class="line"><a name="l00091"></a><span class="lineno">   91</span>&#160;<span class="preprocessor">                        #endif</span></div><div class="line"><a name="l00092"></a><span class="lineno">   92</span>&#160;</div><div class="line"><a name="l00096"></a><span class="lineno">   96</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_event_1_1_input_manager.php#a8c79605377604bc1921c94b815ce1156">processPressedKey</a>(<a class="code" href="_n_r_e___keys_8hpp.php#aad0b5de9f5c32805861bae5dda36d501">KeyCode</a> key);</div><div class="line"><a name="l00101"></a><span class="lineno">  101</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_event_1_1_input_manager.php#a49c78dd73cf5b5eae6daec89030e09dc">processPressedButton</a>(<a class="code" href="class_n_r_e_1_1_event_1_1_button_event.php">ButtonEventData</a> <span class="keyword">const</span>&amp; buttonData);</div><div class="line"><a name="l00106"></a><span class="lineno">  106</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_event_1_1_input_manager.php#a50c021dddab878c05e26511485438a2b">processReleasedKey</a>(<a class="code" href="_n_r_e___keys_8hpp.php#aad0b5de9f5c32805861bae5dda36d501">KeyCode</a> key);</div><div class="line"><a name="l00111"></a><span class="lineno">  111</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_event_1_1_input_manager.php#a49c2c4284cf3eda4c74e2026dde5be74">processReleasedButton</a>(<a class="code" href="class_n_r_e_1_1_event_1_1_button_event.php">ButtonEventData</a> <span class="keyword">const</span>&amp; buttonData);</div><div class="line"><a name="l00115"></a><span class="lineno">  115</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_event_1_1_input_manager.php#ad30e5d64bd4823311de1612c4b7520f1">update</a>();</div><div class="line"><a name="l00120"></a><span class="lineno">  120</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_event_1_1_input_manager.php#a7799ede2c90932658c79a0674a3fa0a0">updateButtonEventData</a>(<a class="code" href="class_n_r_e_1_1_event_1_1_button_event.php">ButtonEventData</a> <span class="keyword">const</span>&amp; buttonData);</div><div class="line"><a name="l00121"></a><span class="lineno">  121</span>&#160;            };</div><div class="line"><a name="l00122"></a><span class="lineno">  122</span>&#160;        }</div><div class="line"><a name="l00123"></a><span class="lineno">  123</span>&#160;    }</div><div class="line"><a name="l00124"></a><span class="lineno">  124</span>&#160;</div><div class="line"><a name="l00125"></a><span class="lineno">  125</span>&#160;<span class="preprocessor">    #include &quot;NRE_InputManager.tpp&quot;</span></div><div class="line"><a name="l00126"></a><span class="lineno">  126</span>&#160;<span class="preprocessor">    #ifdef _WIN32                           // Windows</span></div><div class="line"><a name="l00127"></a><span class="lineno">  127</span>&#160;<span class="preprocessor">        #include &quot;../../../OS/Windows/Event/Input/NRE_WindowsInputManager.tpp&quot;</span></div><div class="line"><a name="l00128"></a><span class="lineno">  128</span>&#160;<span class="preprocessor">    #elif __linux__                         // Linux</span></div><div class="line"><a name="l00129"></a><span class="lineno">  129</span>&#160;<span class="preprocessor">        #include &quot;../../../OS/Linux/Event/Input/NRE_LinuxInputManager.tpp&quot;</span></div><div class="line"><a name="l00130"></a><span class="lineno">  130</span>&#160;<span class="preprocessor">    #endif</span></div><div class="ttc" id="_n_r_e___keys_8hpp_php_aad0b5de9f5c32805861bae5dda36d501"><div class="ttname"><a href="_n_r_e___keys_8hpp.php#aad0b5de9f5c32805861bae5dda36d501">NRE::Event::KeyCode</a></div><div class="ttdeci">KeyCode</div><div class="ttdef"><b>Definition:</b> NRE_Keys.hpp:27</div></div>
<div class="ttc" id="class_n_r_e_1_1_event_1_1_input_manager_php_a7799ede2c90932658c79a0674a3fa0a0"><div class="ttname"><a href="class_n_r_e_1_1_event_1_1_input_manager.php#a7799ede2c90932658c79a0674a3fa0a0">NRE::Event::InputManager::updateButtonEventData</a></div><div class="ttdeci">void updateButtonEventData(ButtonEventData const &amp;buttonData)</div></div>
<div class="ttc" id="class_n_r_e_1_1_event_1_1_input_manager_php"><div class="ttname"><a href="class_n_r_e_1_1_event_1_1_input_manager.php">NRE::Event::InputManager</a></div><div class="ttdoc">Manage the process of native input. </div><div class="ttdef"><b>Definition:</b> NRE_InputManager.hpp:42</div></div>
<div class="ttc" id="class_n_r_e_1_1_event_1_1_input_manager_php_ad30e5d64bd4823311de1612c4b7520f1"><div class="ttname"><a href="class_n_r_e_1_1_event_1_1_input_manager.php#ad30e5d64bd4823311de1612c4b7520f1">NRE::Event::InputManager::update</a></div><div class="ttdeci">void update()</div><div class="ttdef"><b>Definition:</b> NRE_InputManager.cpp:20</div></div>
<div class="ttc" id="class_n_r_e_1_1_event_1_1_key_translater_php"><div class="ttname"><a href="class_n_r_e_1_1_event_1_1_key_translater.php">NRE::Event::KeyTranslater</a></div><div class="ttdoc">Manage the translation of native key. </div><div class="ttdef"><b>Definition:</b> NRE_LinuxKeyTranslater.hpp:31</div></div>
<div class="ttc" id="class_n_r_e_1_1_event_1_1_input_manager_php_af27a0330fff81319a4a19fe1b5dfb627"><div class="ttname"><a href="class_n_r_e_1_1_event_1_1_input_manager.php#af27a0330fff81319a4a19fe1b5dfb627">NRE::Event::InputManager::isButtonPressed</a></div><div class="ttdeci">bool isButtonPressed(ButtonCode code) const </div></div>
<div class="ttc" id="namespace_event_php"><div class="ttname"><a href="namespace_event.php">Event</a></div><div class="ttdoc">Event&amp;#39;s API. </div></div>
<div class="ttc" id="class_n_r_e_1_1_event_1_1_input_manager_php_a49c2c4284cf3eda4c74e2026dde5be74"><div class="ttname"><a href="class_n_r_e_1_1_event_1_1_input_manager.php#a49c2c4284cf3eda4c74e2026dde5be74">NRE::Event::InputManager::processReleasedButton</a></div><div class="ttdeci">void processReleasedButton(ButtonEventData const &amp;buttonData)</div></div>
<div class="ttc" id="class_n_r_e_1_1_event_1_1_input_manager_php_a49c78dd73cf5b5eae6daec89030e09dc"><div class="ttname"><a href="class_n_r_e_1_1_event_1_1_input_manager.php#a49c78dd73cf5b5eae6daec89030e09dc">NRE::Event::InputManager::processPressedButton</a></div><div class="ttdeci">void processPressedButton(ButtonEventData const &amp;buttonData)</div></div>
<div class="ttc" id="class_n_r_e_1_1_event_1_1_input_manager_php_a50c021dddab878c05e26511485438a2b"><div class="ttname"><a href="class_n_r_e_1_1_event_1_1_input_manager.php#a50c021dddab878c05e26511485438a2b">NRE::Event::InputManager::processReleasedKey</a></div><div class="ttdeci">void processReleasedKey(KeyCode key)</div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div></div>
<div class="ttc" id="class_n_r_e_1_1_event_1_1_button_event_php"><div class="ttname"><a href="class_n_r_e_1_1_event_1_1_button_event.php">NRE::Event::ButtonEvent</a></div><div class="ttdoc">Manage a button event. </div><div class="ttdef"><b>Definition:</b> NRE_ButtonEvent.hpp:31</div></div>
<div class="ttc" id="_n_r_e___buttons_8hpp_php_a3117cef30b4eed21ee57db72bd9d3ef8"><div class="ttname"><a href="_n_r_e___buttons_8hpp.php#a3117cef30b4eed21ee57db72bd9d3ef8">NRE::Event::ButtonCode</a></div><div class="ttdeci">ButtonCode</div><div class="ttdef"><b>Definition:</b> NRE_Buttons.hpp:27</div></div>
<div class="ttc" id="class_n_r_e_1_1_event_1_1_input_manager_php_a8c79605377604bc1921c94b815ce1156"><div class="ttname"><a href="class_n_r_e_1_1_event_1_1_input_manager.php#a8c79605377604bc1921c94b815ce1156">NRE::Event::InputManager::processPressedKey</a></div><div class="ttdeci">void processPressedKey(KeyCode key)</div></div>
<div class="ttc" id="class_n_r_e_1_1_event_1_1_input_manager_php_aa8d6f2d0d14b9b1fde715c9a0e496656"><div class="ttname"><a href="class_n_r_e_1_1_event_1_1_input_manager.php#aa8d6f2d0d14b9b1fde715c9a0e496656">NRE::Event::InputManager::isKeyPressed</a></div><div class="ttdeci">bool isKeyPressed(KeyCode code) const </div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
