<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: /mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Time/Clock/NRE_Clock.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_ef68f1e1f5148ff8ef7fb1c955106c3c.php">System</a></li><li class="navelem"><a class="el" href="dir_2023b60a521fa94f074e6209789d9c9f.php">Time</a></li><li class="navelem"><a class="el" href="dir_04297c08d9ec56edc0b08583d24902cf.php">Clock</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_Clock.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___clock_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">     #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">    #include &lt;iostream&gt;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;<span class="preprocessor">    #include &lt;thread&gt;</span></div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;<span class="preprocessor">    #include &lt;chrono&gt;</span></div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;</div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;<span class="preprocessor">    #include &lt;Utility/String/NRE_String.hpp&gt;</span></div><div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;</div><div class="line"><a name="l00022"></a><span class="lineno">   22</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00027"></a><span class="lineno">   27</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_time.php">Time</a> {</div><div class="line"><a name="l00028"></a><span class="lineno">   28</span>&#160;</div><div class="line"><a name="l00030"></a><span class="lineno"><a class="line" href="_n_r_e___clock_8hpp.php#ad1571e29443ed974088ad851f74b2824">   30</a></span>&#160;            <span class="keyword">typedef</span> std::chrono::steady_clock <a class="code" href="_n_r_e___clock_8hpp.php#ad1571e29443ed974088ad851f74b2824">Chrono</a>;</div><div class="line"><a name="l00032"></a><span class="lineno"><a class="line" href="_n_r_e___clock_8hpp.php#aab6710cca35ec01cff2f2b352efcf4cb">   32</a></span>&#160;            <span class="keyword">typedef</span> std::chrono::time_point&lt;Chrono&gt; <a class="code" href="_n_r_e___clock_8hpp.php#aab6710cca35ec01cff2f2b352efcf4cb">TimePoint</a>;</div><div class="line"><a name="l00034"></a><span class="lineno"><a class="line" href="_n_r_e___clock_8hpp.php#ab1956335fcfad28ae6fd32e8d9b1249d">   34</a></span>&#160;            <span class="keyword">typedef</span> std::chrono::duration&lt;float, std::milli&gt; <a class="code" href="_n_r_e___clock_8hpp.php#ab1956335fcfad28ae6fd32e8d9b1249d">TimeStep</a>;</div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;</div><div class="line"><a name="l00040"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_time_1_1_clock.php">   40</a></span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_1_1_time_1_1_clock.php">Clock</a> {</div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;                <span class="keyword">private</span>:    <span class="comment">//Fields</span></div><div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;                    TimePoint now;      </div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;                    TimePoint before;   </div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;                    TimePoint frame;    </div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;                    TimeStep timestep;  </div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;                    <span class="keywordtype">int</span> nbFrames;       </div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;                    <span class="keywordtype">bool</span> show;          </div><div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;                <span class="keyword">public</span>:    <span class="comment">// Methods</span></div><div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_time_1_1_clock.php#ac2d4b5d1580b750386ef55cb5c5f9769">Clock</a>();</div><div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;</div><div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;                    <span class="comment">//## Copy-Constructor ##//</span></div><div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_time_1_1_clock.php#ac2d4b5d1580b750386ef55cb5c5f9769">Clock</a>(<a class="code" href="class_n_r_e_1_1_time_1_1_clock.php">Clock</a> <span class="keyword">const</span>&amp; c) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00062"></a><span class="lineno">   62</span>&#160;</div><div class="line"><a name="l00063"></a><span class="lineno">   63</span>&#160;                    <span class="comment">//## Move-Constructor ##//</span></div><div class="line"><a name="l00068"></a><span class="lineno">   68</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_time_1_1_clock.php#ac2d4b5d1580b750386ef55cb5c5f9769">Clock</a>(<a class="code" href="class_n_r_e_1_1_time_1_1_clock.php">Clock</a> &amp;&amp; c) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00069"></a><span class="lineno">   69</span>&#160;</div><div class="line"><a name="l00070"></a><span class="lineno">   70</span>&#160;                    <span class="comment">//## Deconstructor ##//</span></div><div class="line"><a name="l00074"></a><span class="lineno">   74</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_time_1_1_clock.php#a27f33c16e7ae21b959ca57ea161e58bb">~Clock</a>() = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00075"></a><span class="lineno">   75</span>&#160;</div><div class="line"><a name="l00076"></a><span class="lineno">   76</span>&#160;                    <span class="comment">//## Getter ##//</span></div><div class="line"><a name="l00080"></a><span class="lineno">   80</span>&#160;<span class="comment"></span>                        TimeStep <span class="keyword">const</span>&amp; <a class="code" href="class_n_r_e_1_1_time_1_1_clock.php#ac5b2dec3b35c168d02a1433ce4e5c64e">getTimestep</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00084"></a><span class="lineno">   84</span>&#160;                        <span class="keywordtype">float</span> <a class="code" href="class_n_r_e_1_1_time_1_1_clock.php#aab40084fb604b17969006b707208e015">getDelta</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00085"></a><span class="lineno">   85</span>&#160;</div><div class="line"><a name="l00086"></a><span class="lineno">   86</span>&#160;                    <span class="comment">//## Methods ##//</span></div><div class="line"><a name="l00090"></a><span class="lineno">   90</span>&#160;<span class="comment"></span>                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_time_1_1_clock.php#a1e2d008610a63cc7bcefecc1a0c2547a">update</a>();</div><div class="line"><a name="l00095"></a><span class="lineno">   95</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_time_1_1_clock.php#ac26847d5b64b5ab6df415765fe4a36af">updateAndSleep</a>(TimeStep <span class="keyword">const</span>&amp; time);</div><div class="line"><a name="l00100"></a><span class="lineno">  100</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_time_1_1_clock.php#ad38ac4031cc4c65a0eb7ef1f350fac4b">sleep</a>(TimeStep <span class="keyword">const</span>&amp; time);</div><div class="line"><a name="l00104"></a><span class="lineno">  104</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_time_1_1_clock.php#a15fbdd1027cbb859d5cdb88f67ee9d5d">showFPS</a>();</div><div class="line"><a name="l00108"></a><span class="lineno">  108</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_time_1_1_clock.php#a43f4e99cfb7c1a83504b3f12c3a39135">hideFPS</a>();</div><div class="line"><a name="l00109"></a><span class="lineno">  109</span>&#160;</div><div class="line"><a name="l00110"></a><span class="lineno">  110</span>&#160;                    <span class="comment">//## Assignment Operator ##//</span></div><div class="line"><a name="l00116"></a><span class="lineno">  116</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_time_1_1_clock.php">Clock</a>&amp; <a class="code" href="class_n_r_e_1_1_time_1_1_clock.php#ac0f40674f22edc75a7138dce945ef195">operator =</a>(<a class="code" href="class_n_r_e_1_1_time_1_1_clock.php">Clock</a> <span class="keyword">const</span>&amp; c) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00122"></a><span class="lineno">  122</span>&#160;                        <a class="code" href="class_n_r_e_1_1_time_1_1_clock.php">Clock</a>&amp; <a class="code" href="class_n_r_e_1_1_time_1_1_clock.php#ac0f40674f22edc75a7138dce945ef195">operator =</a>(<a class="code" href="class_n_r_e_1_1_time_1_1_clock.php">Clock</a> &amp;&amp; c) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00123"></a><span class="lineno">  123</span>&#160;</div><div class="line"><a name="l00124"></a><span class="lineno">  124</span>&#160;                    <span class="comment">//## Stream Operator ##//</span></div><div class="line"><a name="l00129"></a><span class="lineno">  129</span>&#160;<span class="comment"></span>                        Utility::String <a class="code" href="class_n_r_e_1_1_time_1_1_clock.php#a6ac7db084c2bbe7d765b18578c28ad80">toString</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00130"></a><span class="lineno">  130</span>&#160;</div><div class="line"><a name="l00131"></a><span class="lineno">  131</span>&#160;                <span class="keyword">private</span>:   <span class="comment">// Methods</span></div><div class="line"><a name="l00135"></a><span class="lineno">  135</span>&#160;<span class="comment"></span>                    <span class="keywordtype">void</span> updateNow();</div><div class="line"><a name="l00139"></a><span class="lineno">  139</span>&#160;                    <span class="keywordtype">void</span> updateBefore();</div><div class="line"><a name="l00143"></a><span class="lineno">  143</span>&#160;                    <span class="keywordtype">void</span> updateTimestep();</div><div class="line"><a name="l00147"></a><span class="lineno">  147</span>&#160;                    <span class="keywordtype">void</span> updateFrame();</div><div class="line"><a name="l00148"></a><span class="lineno">  148</span>&#160;</div><div class="line"><a name="l00149"></a><span class="lineno">  149</span>&#160;                <span class="keyword">public</span>:     <span class="comment">// Static</span></div><div class="line"><a name="l00150"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_time_1_1_clock.php#a8c0dffc9c6f3bf190d7ed1580a9b72fb">  150</a></span>&#160;                    <span class="keyword">static</span> <span class="keywordtype">float</span> <a class="code" href="class_n_r_e_1_1_time_1_1_clock.php#a8c0dffc9c6f3bf190d7ed1580a9b72fb">TIMESTEP</a>;  </div><div class="line"><a name="l00151"></a><span class="lineno">  151</span>&#160;            };</div><div class="line"><a name="l00152"></a><span class="lineno">  152</span>&#160;</div><div class="line"><a name="l00159"></a><span class="lineno">  159</span>&#160;            std::ostream&amp; operator &lt;&lt;(std::ostream&amp; stream, <a class="code" href="class_n_r_e_1_1_time_1_1_clock.php">Clock</a> <span class="keyword">const</span>&amp; o);</div><div class="line"><a name="l00160"></a><span class="lineno">  160</span>&#160;        }</div><div class="line"><a name="l00161"></a><span class="lineno">  161</span>&#160;    }</div><div class="line"><a name="l00162"></a><span class="lineno">  162</span>&#160;</div><div class="line"><a name="l00163"></a><span class="lineno">  163</span>&#160;<span class="preprocessor">    #include &quot;NRE_Clock.tpp&quot;</span></div><div class="ttc" id="class_n_r_e_1_1_time_1_1_clock_php_a43f4e99cfb7c1a83504b3f12c3a39135"><div class="ttname"><a href="class_n_r_e_1_1_time_1_1_clock.php#a43f4e99cfb7c1a83504b3f12c3a39135">NRE::Time::Clock::hideFPS</a></div><div class="ttdeci">void hideFPS()</div></div>
<div class="ttc" id="namespace_time_php"><div class="ttname"><a href="namespace_time.php">Time</a></div><div class="ttdoc">Time&amp;#39;s API. </div></div>
<div class="ttc" id="_n_r_e___clock_8hpp_php_ab1956335fcfad28ae6fd32e8d9b1249d"><div class="ttname"><a href="_n_r_e___clock_8hpp.php#ab1956335fcfad28ae6fd32e8d9b1249d">NRE::Time::TimeStep</a></div><div class="ttdeci">std::chrono::duration&lt; float, std::milli &gt; TimeStep</div><div class="ttdef"><b>Definition:</b> NRE_Clock.hpp:34</div></div>
<div class="ttc" id="class_n_r_e_1_1_time_1_1_clock_php_a15fbdd1027cbb859d5cdb88f67ee9d5d"><div class="ttname"><a href="class_n_r_e_1_1_time_1_1_clock.php#a15fbdd1027cbb859d5cdb88f67ee9d5d">NRE::Time::Clock::showFPS</a></div><div class="ttdeci">void showFPS()</div></div>
<div class="ttc" id="class_n_r_e_1_1_time_1_1_clock_php_ac26847d5b64b5ab6df415765fe4a36af"><div class="ttname"><a href="class_n_r_e_1_1_time_1_1_clock.php#ac26847d5b64b5ab6df415765fe4a36af">NRE::Time::Clock::updateAndSleep</a></div><div class="ttdeci">void updateAndSleep(TimeStep const &amp;time)</div></div>
<div class="ttc" id="class_n_r_e_1_1_time_1_1_clock_php_a1e2d008610a63cc7bcefecc1a0c2547a"><div class="ttname"><a href="class_n_r_e_1_1_time_1_1_clock.php#a1e2d008610a63cc7bcefecc1a0c2547a">NRE::Time::Clock::update</a></div><div class="ttdeci">void update()</div></div>
<div class="ttc" id="class_n_r_e_1_1_time_1_1_clock_php_ac5b2dec3b35c168d02a1433ce4e5c64e"><div class="ttname"><a href="class_n_r_e_1_1_time_1_1_clock.php#ac5b2dec3b35c168d02a1433ce4e5c64e">NRE::Time::Clock::getTimestep</a></div><div class="ttdeci">TimeStep const &amp; getTimestep() const </div></div>
<div class="ttc" id="_n_r_e___clock_8hpp_php_ad1571e29443ed974088ad851f74b2824"><div class="ttname"><a href="_n_r_e___clock_8hpp.php#ad1571e29443ed974088ad851f74b2824">NRE::Time::Chrono</a></div><div class="ttdeci">std::chrono::steady_clock Chrono</div><div class="ttdef"><b>Definition:</b> NRE_Clock.hpp:30</div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div></div>
<div class="ttc" id="class_n_r_e_1_1_time_1_1_clock_php_a27f33c16e7ae21b959ca57ea161e58bb"><div class="ttname"><a href="class_n_r_e_1_1_time_1_1_clock.php#a27f33c16e7ae21b959ca57ea161e58bb">NRE::Time::Clock::~Clock</a></div><div class="ttdeci">~Clock()=default</div></div>
<div class="ttc" id="class_n_r_e_1_1_time_1_1_clock_php_ac2d4b5d1580b750386ef55cb5c5f9769"><div class="ttname"><a href="class_n_r_e_1_1_time_1_1_clock.php#ac2d4b5d1580b750386ef55cb5c5f9769">NRE::Time::Clock::Clock</a></div><div class="ttdeci">Clock()</div></div>
<div class="ttc" id="class_n_r_e_1_1_time_1_1_clock_php_ad38ac4031cc4c65a0eb7ef1f350fac4b"><div class="ttname"><a href="class_n_r_e_1_1_time_1_1_clock.php#ad38ac4031cc4c65a0eb7ef1f350fac4b">NRE::Time::Clock::sleep</a></div><div class="ttdeci">void sleep(TimeStep const &amp;time)</div></div>
<div class="ttc" id="class_n_r_e_1_1_time_1_1_clock_php"><div class="ttname"><a href="class_n_r_e_1_1_time_1_1_clock.php">NRE::Time::Clock</a></div><div class="ttdoc">Manage timing and program pause. </div><div class="ttdef"><b>Definition:</b> NRE_Clock.hpp:40</div></div>
<div class="ttc" id="class_n_r_e_1_1_time_1_1_clock_php_a8c0dffc9c6f3bf190d7ed1580a9b72fb"><div class="ttname"><a href="class_n_r_e_1_1_time_1_1_clock.php#a8c0dffc9c6f3bf190d7ed1580a9b72fb">NRE::Time::Clock::TIMESTEP</a></div><div class="ttdeci">static float TIMESTEP</div><div class="ttdef"><b>Definition:</b> NRE_Clock.hpp:150</div></div>
<div class="ttc" id="class_n_r_e_1_1_time_1_1_clock_php_ac0f40674f22edc75a7138dce945ef195"><div class="ttname"><a href="class_n_r_e_1_1_time_1_1_clock.php#ac0f40674f22edc75a7138dce945ef195">NRE::Time::Clock::operator=</a></div><div class="ttdeci">Clock &amp; operator=(Clock const &amp;c)=default</div></div>
<div class="ttc" id="class_n_r_e_1_1_time_1_1_clock_php_a6ac7db084c2bbe7d765b18578c28ad80"><div class="ttname"><a href="class_n_r_e_1_1_time_1_1_clock.php#a6ac7db084c2bbe7d765b18578c28ad80">NRE::Time::Clock::toString</a></div><div class="ttdeci">Utility::String toString() const </div><div class="ttdef"><b>Definition:</b> NRE_Clock.cpp:31</div></div>
<div class="ttc" id="class_n_r_e_1_1_time_1_1_clock_php_aab40084fb604b17969006b707208e015"><div class="ttname"><a href="class_n_r_e_1_1_time_1_1_clock.php#aab40084fb604b17969006b707208e015">NRE::Time::Clock::getDelta</a></div><div class="ttdeci">float getDelta() const </div></div>
<div class="ttc" id="_n_r_e___clock_8hpp_php_aab6710cca35ec01cff2f2b352efcf4cb"><div class="ttname"><a href="_n_r_e___clock_8hpp.php#aab6710cca35ec01cff2f2b352efcf4cb">NRE::Time::TimePoint</a></div><div class="ttdeci">std::chrono::time_point&lt; Chrono &gt; TimePoint</div><div class="ttdef"><b>Definition:</b> NRE_Clock.hpp:32</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
