<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: /mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Graphics/Window/NRE_Window.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_ef68f1e1f5148ff8ef7fb1c955106c3c.php">System</a></li><li class="navelem"><a class="el" href="dir_13c1ecb482d2b1153b2c0856159b065a.php">Graphics</a></li><li class="navelem"><a class="el" href="dir_4f86bd3a8a8cc0a9216ad2e14aa5b93d.php">Window</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_Window.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___window_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">     #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">     #include &quot;<a class="code" href="_n_r_e___window_attributes_8hpp.php">Attributes/NRE_WindowAttributes.hpp</a>&quot;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;<span class="preprocessor">     #include &quot;<a class="code" href="_n_r_e___window_status_8hpp.php">Status/NRE_WindowStatus.hpp</a>&quot;</span></div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;<span class="preprocessor">     #include &quot;<a class="code" href="_n_r_e___internal_window_8hpp.php">Internal/NRE_InternalWindow.hpp</a>&quot;</span></div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;<span class="preprocessor">     #include &quot;../Driver/Context/NRE_Context.hpp&quot;</span></div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;</div><div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;<span class="preprocessor">     #include &lt;Utility/String/NRE_String.hpp&gt;</span></div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;</div><div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;     <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00028"></a><span class="lineno">   28</span>&#160;         <span class="keyword">namespace </span><a class="code" href="namespace_graphics.php">Graphics</a> {</div><div class="line"><a name="l00029"></a><span class="lineno">   29</span>&#160;</div><div class="line"><a name="l00034"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_graphics_1_1_window.php">   34</a></span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_1_1_graphics_1_1_window.php">Window</a> {</div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;                <span class="keyword">private</span> :   <span class="comment">// Fields</span></div><div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;                    <a class="code" href="class_n_r_e_1_1_graphics_1_1_internal_window.php">InternalWindow</a> window;          </div><div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;                    <a class="code" href="class_n_r_e_1_1_graphics_1_1_window_attributes.php">WindowAttributes</a> attributes;    </div><div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;                    <a class="code" href="class_n_r_e_1_1_graphics_1_1_window_status.php">WindowStatus</a> status;            </div><div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;                    <a class="code" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a> style;              </div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;                    Id id;                          </div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;                    <a class="code" href="class_n_r_e_1_1_graphics_1_1_context.php">Context</a> context;                </div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;                <span class="keyword">public</span> :    <span class="comment">// Methods</span></div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_graphics_1_1_window.php#afb4a3ec6654693a69a77fdef0618a300">Window</a>() = <span class="keyword">delete</span>;</div><div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;                        <a class="code" href="class_n_r_e_1_1_graphics_1_1_window.php#afb4a3ec6654693a69a77fdef0618a300">Window</a>(Id <span class="keyword">const</span>&amp; i, Utility::String <span class="keyword">const</span>&amp; t, Math::Point2D&lt;unsigned int&gt; <span class="keyword">const</span>&amp; pos, Math::Vector2D&lt;unsigned int&gt; <span class="keyword">const</span>&amp; s, <a class="code" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a> <span class="keyword">const</span>&amp; ws, <a class="code" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">ContextAttributes</a> <span class="keyword">const</span>&amp; attr);</div><div class="line"><a name="l00067"></a><span class="lineno">   67</span>&#160;                        <a class="code" href="class_n_r_e_1_1_graphics_1_1_window.php#afb4a3ec6654693a69a77fdef0618a300">Window</a>(Id <span class="keyword">const</span>&amp; i, Utility::String <span class="keyword">const</span>&amp; t, Math::Vector2D&lt;unsigned int&gt; <span class="keyword">const</span>&amp; s, <a class="code" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a> <span class="keyword">const</span>&amp; ws, <a class="code" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">ContextAttributes</a> <span class="keyword">const</span>&amp; attr);</div><div class="line"><a name="l00068"></a><span class="lineno">   68</span>&#160;</div><div class="line"><a name="l00069"></a><span class="lineno">   69</span>&#160;                    <span class="comment">//## Copy Constructor ##//</span></div><div class="line"><a name="l00074"></a><span class="lineno">   74</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_graphics_1_1_window.php#afb4a3ec6654693a69a77fdef0618a300">Window</a>(<a class="code" href="class_n_r_e_1_1_graphics_1_1_window.php">Window</a> <span class="keyword">const</span>&amp; w) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00075"></a><span class="lineno">   75</span>&#160;</div><div class="line"><a name="l00076"></a><span class="lineno">   76</span>&#160;                    <span class="comment">//## Copy Constructor ##//</span></div><div class="line"><a name="l00081"></a><span class="lineno">   81</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_graphics_1_1_window.php#afb4a3ec6654693a69a77fdef0618a300">Window</a>(<a class="code" href="class_n_r_e_1_1_graphics_1_1_window.php">Window</a> &amp;&amp; w) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00082"></a><span class="lineno">   82</span>&#160;</div><div class="line"><a name="l00083"></a><span class="lineno">   83</span>&#160;                    <span class="comment">//## Deconstructor ##//</span></div><div class="line"><a name="l00087"></a><span class="lineno">   87</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_graphics_1_1_window.php#a578cc889485c2db6e2b7c00cb01268a8">~Window</a>();</div><div class="line"><a name="l00088"></a><span class="lineno">   88</span>&#160;</div><div class="line"><a name="l00089"></a><span class="lineno">   89</span>&#160;                    <span class="comment">//## Getter ##//</span></div><div class="line"><a name="l00093"></a><span class="lineno">   93</span>&#160;<span class="comment"></span>                        <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_1_1_graphics_1_1_window.php#a75d09fcf9899e97ab4729aec113551fe">isRunning</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00097"></a><span class="lineno">   97</span>&#160;                        Id <a class="code" href="class_n_r_e_1_1_graphics_1_1_window.php#a1a8c28f36a398d0e10bd4c7b1cf89ac4">getId</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00098"></a><span class="lineno">   98</span>&#160;</div><div class="line"><a name="l00099"></a><span class="lineno">   99</span>&#160;                    <span class="comment">//## Methods ##//</span></div><div class="line"><a name="l00104"></a><span class="lineno">  104</span>&#160;<span class="comment"></span>                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_graphics_1_1_window.php#a2a5f32f300a87565e5db94f459dbf963">close</a>(<span class="keywordtype">bool</span> removeFromSystem = <span class="keyword">true</span>);</div><div class="line"><a name="l00108"></a><span class="lineno">  108</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_graphics_1_1_window.php#ac255a15a9f8b13961d6103ebc273a280">refresh</a>();</div><div class="line"><a name="l00109"></a><span class="lineno">  109</span>&#160;</div><div class="line"><a name="l00110"></a><span class="lineno">  110</span>&#160;                    <span class="comment">//## Assignment Operator ##//</span></div><div class="line"><a name="l00116"></a><span class="lineno">  116</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_graphics_1_1_window.php">Window</a>&amp; <a class="code" href="class_n_r_e_1_1_graphics_1_1_window.php#a31b91ff88d0cc953df075840e4a7d7f8">operator =</a>(<a class="code" href="class_n_r_e_1_1_graphics_1_1_window.php">Window</a> <span class="keyword">const</span>&amp; w) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00122"></a><span class="lineno">  122</span>&#160;                        <a class="code" href="class_n_r_e_1_1_graphics_1_1_window.php">Window</a>&amp; <a class="code" href="class_n_r_e_1_1_graphics_1_1_window.php#a31b91ff88d0cc953df075840e4a7d7f8">operator =</a>(<a class="code" href="class_n_r_e_1_1_graphics_1_1_window.php">Window</a> &amp;&amp; w) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00123"></a><span class="lineno">  123</span>&#160;</div><div class="line"><a name="l00124"></a><span class="lineno">  124</span>&#160;                    <span class="comment">//## Stream Operator ##//</span></div><div class="line"><a name="l00129"></a><span class="lineno">  129</span>&#160;<span class="comment"></span>                        Utility::String <a class="code" href="class_n_r_e_1_1_graphics_1_1_window.php#a5ac753c6a5f4126e47190159cd3a8c9b">toString</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00130"></a><span class="lineno">  130</span>&#160;</div><div class="line"><a name="l00131"></a><span class="lineno">  131</span>&#160;            };</div><div class="line"><a name="l00132"></a><span class="lineno">  132</span>&#160;</div><div class="line"><a name="l00139"></a><span class="lineno">  139</span>&#160;            std::ostream&amp; operator &lt;&lt;(std::ostream&amp; stream, <a class="code" href="class_n_r_e_1_1_graphics_1_1_window.php">Window</a> <span class="keyword">const</span>&amp; o);</div><div class="line"><a name="l00140"></a><span class="lineno">  140</span>&#160;         }</div><div class="line"><a name="l00141"></a><span class="lineno">  141</span>&#160;     }</div><div class="line"><a name="l00142"></a><span class="lineno">  142</span>&#160;</div><div class="line"><a name="l00143"></a><span class="lineno">  143</span>&#160;<span class="preprocessor">     #include &quot;NRE_Window.tpp&quot;</span></div><div class="ttc" id="class_n_r_e_1_1_graphics_1_1_window_php"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_window.php">NRE::Graphics::Window</a></div><div class="ttdoc">Manage a graphics window. </div><div class="ttdef"><b>Definition:</b> NRE_Window.hpp:34</div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_window_style_php"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_window_style.php">NRE::Graphics::WindowStyle</a></div><div class="ttdoc">Manage a window style. </div><div class="ttdef"><b>Definition:</b> NRE_WindowStyle.hpp:37</div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_window_status_php"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_window_status.php">NRE::Graphics::WindowStatus</a></div><div class="ttdoc">Manage a window status. </div><div class="ttdef"><b>Definition:</b> NRE_WindowStatus.hpp:29</div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_window_php_a31b91ff88d0cc953df075840e4a7d7f8"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_window.php#a31b91ff88d0cc953df075840e4a7d7f8">NRE::Graphics::Window::operator=</a></div><div class="ttdeci">Window &amp; operator=(Window const &amp;w)=delete</div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_context_php"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_context.php">NRE::Graphics::Context</a></div><div class="ttdoc">Describe an OpenGL Context with a set of attributes. </div><div class="ttdef"><b>Definition:</b> NRE_Context.hpp:40</div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_window_php_a5ac753c6a5f4126e47190159cd3a8c9b"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_window.php#a5ac753c6a5f4126e47190159cd3a8c9b">NRE::Graphics::Window::toString</a></div><div class="ttdeci">Utility::String toString() const </div><div class="ttdef"><b>Definition:</b> NRE_Window.cpp:48</div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_window_attributes_php"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_window_attributes.php">NRE::Graphics::WindowAttributes</a></div><div class="ttdoc">Manage a window attributes. </div><div class="ttdef"><b>Definition:</b> NRE_WindowAttributes.hpp:30</div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_window_php_ac255a15a9f8b13961d6103ebc273a280"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_window.php#ac255a15a9f8b13961d6103ebc273a280">NRE::Graphics::Window::refresh</a></div><div class="ttdeci">void refresh()</div></div>
<div class="ttc" id="_n_r_e___internal_window_8hpp_php"><div class="ttname"><a href="_n_r_e___internal_window_8hpp.php">NRE_InternalWindow.hpp</a></div><div class="ttdoc">Declaration of Graphics&amp;#39;s API&amp;#39;s Object : InternalWindow. </div></div>
<div class="ttc" id="_n_r_e___window_attributes_8hpp_php"><div class="ttname"><a href="_n_r_e___window_attributes_8hpp.php">NRE_WindowAttributes.hpp</a></div><div class="ttdoc">Declaration of Graphics&amp;#39;s API&amp;#39;s Object : WindowAttributes. </div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_window_php_a1a8c28f36a398d0e10bd4c7b1cf89ac4"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_window.php#a1a8c28f36a398d0e10bd4c7b1cf89ac4">NRE::Graphics::Window::getId</a></div><div class="ttdeci">Id getId() const </div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_window_php_a2a5f32f300a87565e5db94f459dbf963"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_window.php#a2a5f32f300a87565e5db94f459dbf963">NRE::Graphics::Window::close</a></div><div class="ttdeci">void close(bool removeFromSystem=true)</div><div class="ttdef"><b>Definition:</b> NRE_Window.cpp:39</div></div>
<div class="ttc" id="_n_r_e___window_status_8hpp_php"><div class="ttname"><a href="_n_r_e___window_status_8hpp.php">NRE_WindowStatus.hpp</a></div><div class="ttdoc">Declaration of Graphics&amp;#39;s API&amp;#39;s Object : WindowStatus. </div></div>
<div class="ttc" id="namespace_graphics_php"><div class="ttname"><a href="namespace_graphics.php">Graphics</a></div><div class="ttdoc">Graphics&amp;#39; API. </div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_context_attributes_php"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">NRE::Graphics::ContextAttributes</a></div><div class="ttdoc">Regroup all attributes needed in a GL context, should be modified before creation. </div><div class="ttdef"><b>Definition:</b> NRE_ContextAttributes.hpp:52</div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_window_php_afb4a3ec6654693a69a77fdef0618a300"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_window.php#afb4a3ec6654693a69a77fdef0618a300">NRE::Graphics::Window::Window</a></div><div class="ttdeci">Window()=delete</div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_internal_window_php"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_internal_window.php">NRE::Graphics::InternalWindow</a></div><div class="ttdoc">Manage the internal os-dependant graphics window. </div><div class="ttdef"><b>Definition:</b> NRE_InternalWindow.hpp:34</div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_window_php_a75d09fcf9899e97ab4729aec113551fe"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_window.php#a75d09fcf9899e97ab4729aec113551fe">NRE::Graphics::Window::isRunning</a></div><div class="ttdeci">bool isRunning() const </div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_window_php_a578cc889485c2db6e2b7c00cb01268a8"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_window.php#a578cc889485c2db6e2b7c00cb01268a8">NRE::Graphics::Window::~Window</a></div><div class="ttdeci">~Window()</div><div class="ttdef"><b>Definition:</b> NRE_Window.cpp:33</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
