<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: /mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Graphics/Window/Status/NRE_WindowStatus.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_ef68f1e1f5148ff8ef7fb1c955106c3c.php">System</a></li><li class="navelem"><a class="el" href="dir_13c1ecb482d2b1153b2c0856159b065a.php">Graphics</a></li><li class="navelem"><a class="el" href="dir_4f86bd3a8a8cc0a9216ad2e14aa5b93d.php">Window</a></li><li class="navelem"><a class="el" href="dir_0b2f896eadce44639169ed93629d9a2d.php">Status</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_WindowStatus.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___window_status_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">     #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">     #include &lt;utility&gt;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;</div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;     <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;         <span class="keyword">namespace </span><a class="code" href="namespace_graphics.php">Graphics</a> {</div><div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160;</div><div class="line"><a name="l00029"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_graphics_1_1_window_status.php">   29</a></span>&#160;             <span class="keyword">class </span><a class="code" href="class_n_r_e_1_1_graphics_1_1_window_status.php">WindowStatus</a> {</div><div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160;                 <span class="keyword">private</span> :  <span class="comment">// Fields</span></div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;                    <span class="keywordtype">bool</span> closed;        </div><div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;                    <span class="keywordtype">bool</span> inFullscreen;  </div><div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;                 <span class="keyword">public</span> :   <span class="comment">// Methods</span></div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_graphics_1_1_window_status.php#aac836fda411dee146d6604f3ae3b4445">WindowStatus</a>();</div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;</div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;                    <span class="comment">//## Copy Constructor ##//</span></div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_graphics_1_1_window_status.php#aac836fda411dee146d6604f3ae3b4445">WindowStatus</a>(<a class="code" href="class_n_r_e_1_1_graphics_1_1_window_status.php">WindowStatus</a> <span class="keyword">const</span>&amp; status) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;</div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;                    <span class="comment">//## Move Constructor ##//</span></div><div class="line"><a name="l00053"></a><span class="lineno">   53</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_graphics_1_1_window_status.php#aac836fda411dee146d6604f3ae3b4445">WindowStatus</a>(<a class="code" href="class_n_r_e_1_1_graphics_1_1_window_status.php">WindowStatus</a> &amp;&amp; status) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;</div><div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;                    <span class="comment">//## Deconstructor ##//</span></div><div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_graphics_1_1_window_status.php#a4037b7c2fe608ded48e098705968fe90">~WindowStatus</a>() = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00060"></a><span class="lineno">   60</span>&#160;</div><div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160;                    <span class="comment">//## Getter ##//</span></div><div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;<span class="comment"></span>                        <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_1_1_graphics_1_1_window_status.php#a197809fbe99ec7ddf5efd46532323798">isClosed</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00069"></a><span class="lineno">   69</span>&#160;                        <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_1_1_graphics_1_1_window_status.php#ae1b12de65049ad0459e8a02647d55a9e">isInFullscreen</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00070"></a><span class="lineno">   70</span>&#160;</div><div class="line"><a name="l00071"></a><span class="lineno">   71</span>&#160;                    <span class="comment">//## Setter ##//</span></div><div class="line"><a name="l00076"></a><span class="lineno">   76</span>&#160;<span class="comment"></span>                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_graphics_1_1_window_status.php#a96bd10aa2cb54cd70ecb8c3c480c16e7">setClosed</a>(<span class="keywordtype">bool</span> status);</div><div class="line"><a name="l00081"></a><span class="lineno">   81</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_graphics_1_1_window_status.php#aada6a41a88391b418d962e3407d08e52">setFullscreen</a>(<span class="keywordtype">bool</span> status);</div><div class="line"><a name="l00082"></a><span class="lineno">   82</span>&#160;</div><div class="line"><a name="l00083"></a><span class="lineno">   83</span>&#160;                    <span class="comment">//## Assignment Operator ##//</span></div><div class="line"><a name="l00089"></a><span class="lineno">   89</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_graphics_1_1_window_status.php">WindowStatus</a>&amp; <a class="code" href="class_n_r_e_1_1_graphics_1_1_window_status.php#a9eb71c79a7702dffb7e1e9f9029ef80d">operator =</a>(<a class="code" href="class_n_r_e_1_1_graphics_1_1_window_status.php">WindowStatus</a> <span class="keyword">const</span>&amp; status) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00095"></a><span class="lineno">   95</span>&#160;                        <a class="code" href="class_n_r_e_1_1_graphics_1_1_window_status.php">WindowStatus</a>&amp; <a class="code" href="class_n_r_e_1_1_graphics_1_1_window_status.php#a9eb71c79a7702dffb7e1e9f9029ef80d">operator =</a>(<a class="code" href="class_n_r_e_1_1_graphics_1_1_window_status.php">WindowStatus</a> &amp;&amp; status) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00096"></a><span class="lineno">   96</span>&#160;             };</div><div class="line"><a name="l00097"></a><span class="lineno">   97</span>&#160;         }</div><div class="line"><a name="l00098"></a><span class="lineno">   98</span>&#160;     }</div><div class="line"><a name="l00099"></a><span class="lineno">   99</span>&#160;</div><div class="line"><a name="l00100"></a><span class="lineno">  100</span>&#160;<span class="preprocessor">     #include &quot;NRE_WindowStatus.tpp&quot;</span></div><div class="ttc" id="class_n_r_e_1_1_graphics_1_1_window_status_php_aada6a41a88391b418d962e3407d08e52"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_window_status.php#aada6a41a88391b418d962e3407d08e52">NRE::Graphics::WindowStatus::setFullscreen</a></div><div class="ttdeci">void setFullscreen(bool status)</div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_window_status_php_a197809fbe99ec7ddf5efd46532323798"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_window_status.php#a197809fbe99ec7ddf5efd46532323798">NRE::Graphics::WindowStatus::isClosed</a></div><div class="ttdeci">bool isClosed() const </div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_window_status_php_aac836fda411dee146d6604f3ae3b4445"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_window_status.php#aac836fda411dee146d6604f3ae3b4445">NRE::Graphics::WindowStatus::WindowStatus</a></div><div class="ttdeci">WindowStatus()</div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_window_status_php"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_window_status.php">NRE::Graphics::WindowStatus</a></div><div class="ttdoc">Manage a window status. </div><div class="ttdef"><b>Definition:</b> NRE_WindowStatus.hpp:29</div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_window_status_php_a4037b7c2fe608ded48e098705968fe90"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_window_status.php#a4037b7c2fe608ded48e098705968fe90">NRE::Graphics::WindowStatus::~WindowStatus</a></div><div class="ttdeci">~WindowStatus()=default</div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_window_status_php_a9eb71c79a7702dffb7e1e9f9029ef80d"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_window_status.php#a9eb71c79a7702dffb7e1e9f9029ef80d">NRE::Graphics::WindowStatus::operator=</a></div><div class="ttdeci">WindowStatus &amp; operator=(WindowStatus const &amp;status)=default</div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_window_status_php_a96bd10aa2cb54cd70ecb8c3c480c16e7"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_window_status.php#a96bd10aa2cb54cd70ecb8c3c480c16e7">NRE::Graphics::WindowStatus::setClosed</a></div><div class="ttdeci">void setClosed(bool status)</div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div></div>
<div class="ttc" id="class_n_r_e_1_1_graphics_1_1_window_status_php_ae1b12de65049ad0459e8a02647d55a9e"><div class="ttname"><a href="class_n_r_e_1_1_graphics_1_1_window_status.php#ae1b12de65049ad0459e8a02647d55a9e">NRE::Graphics::WindowStatus::isInFullscreen</a></div><div class="ttdeci">bool isInFullscreen() const </div></div>
<div class="ttc" id="namespace_graphics_php"><div class="ttname"><a href="namespace_graphics.php">Graphics</a></div><div class="ttdoc">Graphics&amp;#39; API. </div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
