<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: /mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/NRE_System.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_ef68f1e1f5148ff8ef7fb1c955106c3c.php">System</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_System.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_system_2_n_r_e___system_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">    #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">    #include &lt;cstring&gt;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;<span class="preprocessor">    #include &lt;iostream&gt;</span></div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;<span class="preprocessor">    #include &lt;fstream&gt;</span></div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;</div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;<span class="preprocessor">    #include &quot;<a class="code" href="_n_r_e___system_info_8hpp.php">Info/NRE_SystemInfo.hpp</a>&quot;</span></div><div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;<span class="preprocessor">    #include &quot;<a class="code" href="_n_r_e___cpu_i_d_8hpp.php">CpuID/NRE_CpuID.hpp</a>&quot;</span></div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;<span class="preprocessor">    #include &quot;<a class="code" href="_n_r_e___graphics_system_8hpp.php">Graphics/NRE_GraphicsSystem.hpp</a>&quot;</span></div><div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;<span class="preprocessor">    #include &quot;<a class="code" href="_n_r_e___event_system_8hpp.php">Event/NRE_EventSystem.hpp</a>&quot;</span></div><div class="line"><a name="l00020"></a><span class="lineno">   20</span>&#160;<span class="preprocessor">    #include &quot;<a class="code" href="_n_r_e___clock_8hpp.php">Time/Clock/NRE_Clock.hpp</a>&quot;</span></div><div class="line"><a name="l00021"></a><span class="lineno">   21</span>&#160;</div><div class="line"><a name="l00022"></a><span class="lineno">   22</span>&#160;<span class="preprocessor">    #include &lt;Utility/String/NRE_String.hpp&gt;</span></div><div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;<span class="preprocessor">    #include &lt;Utility/Singleton/NRE_Singleton.hpp&gt;</span></div><div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160;</div><div class="line"><a name="l00029"></a><span class="lineno">   29</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_system.php">System</a> {</div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;</div><div class="line"><a name="l00040"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_system_1_1_system.php">   40</a></span>&#160;            <span class="keyword">class </span><a class="code" href="namespace_system.php">System</a> : <span class="keyword">public</span> Utility::Singleton&lt;System&gt; {</div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;                <span class="keyword">friend</span> Utility::Singleton&lt;System&gt;;</div><div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;                <span class="keyword">private</span> :   <span class="comment">// Fields</span></div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;                    <a class="code" href="class_n_r_e_1_1_system_1_1_system_info.php">SystemInfo</a> infos;           </div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;                    <a class="code" href="class_n_r_e_1_1_system_1_1_graphics_system.php">GraphicsSystem</a> graphics;    </div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;                    <a class="code" href="class_n_r_e_1_1_system_1_1_event_system.php">EventSystem</a> events;         </div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;                    <a class="code" href="class_n_r_e_1_1_time_1_1_clock.php">Time::Clock</a> clock;          </div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;                <span class="keyword">public</span> :    <span class="comment">// Methods</span></div><div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;                    <span class="comment">//## Move Constructor ##//</span></div><div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;<span class="comment"></span>                        <a class="code" href="namespace_system.php">System</a>(<a class="code" href="namespace_system.php">System</a> &amp;&amp; sys) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;</div><div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;                    <span class="comment">//## Deconstructor ##//</span></div><div class="line"><a name="l00060"></a><span class="lineno">   60</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_system_1_1_system.php#a30efe5d710af9663cc6df77f40158509">~System</a>() = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160;</div><div class="line"><a name="l00062"></a><span class="lineno">   62</span>&#160;                    <span class="comment">//## Getter ##//</span></div><div class="line"><a name="l00066"></a><span class="lineno">   66</span>&#160;<span class="comment"></span>                        Utility::String <a class="code" href="class_n_r_e_1_1_system_1_1_system.php#a9ec11b369f76b5a3c28848214d537a2a">getSystemName</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00070"></a><span class="lineno">   70</span>&#160;                        <a class="code" href="class_n_r_e_1_1_system_1_1_system_info.php">SystemInfo</a> <span class="keyword">const</span>&amp; <a class="code" href="class_n_r_e_1_1_system_1_1_system.php#aec6231860ffa5d7bd5b4967bc924ae47">getSystemInfo</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00074"></a><span class="lineno">   74</span>&#160;                        <a class="code" href="class_n_r_e_1_1_system_1_1_graphics_system.php">GraphicsSystem</a>&amp; <a class="code" href="class_n_r_e_1_1_system_1_1_system.php#aaacfbb3bdc568117a97814127f9d2b37">getGraphicsSystem</a>();</div><div class="line"><a name="l00078"></a><span class="lineno">   78</span>&#160;                        <a class="code" href="class_n_r_e_1_1_system_1_1_event_system.php">EventSystem</a>&amp; <a class="code" href="class_n_r_e_1_1_system_1_1_system.php#aa247ee0adb3423e34af2859b0145c8ed">getEventSystem</a>();</div><div class="line"><a name="l00082"></a><span class="lineno">   82</span>&#160;                        <a class="code" href="class_n_r_e_1_1_time_1_1_clock.php">Time::Clock</a>&amp; <a class="code" href="class_n_r_e_1_1_system_1_1_system.php#ac895939d8863dae1dbed70855a07ec4a">getClock</a>();</div><div class="line"><a name="l00083"></a><span class="lineno">   83</span>&#160;</div><div class="line"><a name="l00084"></a><span class="lineno">   84</span>&#160;                    <span class="comment">//## Methods ##//</span></div><div class="line"><a name="l00088"></a><span class="lineno">   88</span>&#160;<span class="comment"></span>                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_system_1_1_system.php#a364858c330bd950e73c74edf3b465eed">queryMemoryInfo</a>();</div><div class="line"><a name="l00092"></a><span class="lineno">   92</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_system_1_1_system.php#a8940363632225bbfd082d1b52ebbce23">querySystemInfo</a>();</div><div class="line"><a name="l00096"></a><span class="lineno">   96</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_system_1_1_system.php#ac7e24af1a48517898bdbf42c87987d82">queryCPUName</a>();</div><div class="line"><a name="l00097"></a><span class="lineno">   97</span>&#160;</div><div class="line"><a name="l00098"></a><span class="lineno">   98</span>&#160;                    <span class="comment">//## Assignment Operator ##//</span></div><div class="line"><a name="l00104"></a><span class="lineno">  104</span>&#160;<span class="comment"></span>                        <a class="code" href="namespace_system.php">System</a>&amp; <a class="code" href="class_n_r_e_1_1_system_1_1_system.php#a5e81c9c5f2f7808cb1498f211155925c">operator =</a>(<a class="code" href="namespace_system.php">System</a> &amp;&amp; s) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00105"></a><span class="lineno">  105</span>&#160;</div><div class="line"><a name="l00106"></a><span class="lineno">  106</span>&#160;                    <span class="comment">//## Stream Operator ##//</span></div><div class="line"><a name="l00111"></a><span class="lineno">  111</span>&#160;<span class="comment"></span>                        Utility::String <a class="code" href="class_n_r_e_1_1_system_1_1_system.php#a93bfdbddfd9e67689b900258f6d8f2a1">toString</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00112"></a><span class="lineno">  112</span>&#160;</div><div class="line"><a name="l00113"></a><span class="lineno">  113</span>&#160;                <span class="keyword">private</span> :   <span class="comment">// Methods</span></div><div class="line"><a name="l00114"></a><span class="lineno">  114</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00118"></a><span class="lineno">  118</span>&#160;<span class="comment"></span>                        <a class="code" href="namespace_system.php">System</a>();</div><div class="line"><a name="l00119"></a><span class="lineno">  119</span>&#160;            };</div><div class="line"><a name="l00120"></a><span class="lineno">  120</span>&#160;</div><div class="line"><a name="l00127"></a><span class="lineno">  127</span>&#160;            std::ostream&amp; operator &lt;&lt;(std::ostream&amp; stream, <a class="code" href="namespace_system.php">System</a> <span class="keyword">const</span>&amp; o);</div><div class="line"><a name="l00128"></a><span class="lineno">  128</span>&#160;        }</div><div class="line"><a name="l00129"></a><span class="lineno">  129</span>&#160;    }</div><div class="line"><a name="l00130"></a><span class="lineno">  130</span>&#160;</div><div class="line"><a name="l00131"></a><span class="lineno">  131</span>&#160;<span class="preprocessor">    #include &quot;NRE_System.tpp&quot;</span></div><div class="ttc" id="class_n_r_e_1_1_system_1_1_system_php_a8940363632225bbfd082d1b52ebbce23"><div class="ttname"><a href="class_n_r_e_1_1_system_1_1_system.php#a8940363632225bbfd082d1b52ebbce23">NRE::System::System::querySystemInfo</a></div><div class="ttdeci">void querySystemInfo()</div><div class="ttdef"><b>Definition:</b> NRE_LinuxSystem.cpp:44</div></div>
<div class="ttc" id="class_n_r_e_1_1_system_1_1_event_system_php"><div class="ttname"><a href="class_n_r_e_1_1_system_1_1_event_system.php">NRE::System::EventSystem</a></div><div class="ttdoc">Manage the event sub system. </div><div class="ttdef"><b>Definition:</b> NRE_EventSystem.hpp:44</div></div>
<div class="ttc" id="class_n_r_e_1_1_system_1_1_system_php_a93bfdbddfd9e67689b900258f6d8f2a1"><div class="ttname"><a href="class_n_r_e_1_1_system_1_1_system.php#a93bfdbddfd9e67689b900258f6d8f2a1">NRE::System::System::toString</a></div><div class="ttdeci">Utility::String toString() const </div><div class="ttdef"><b>Definition:</b> NRE_System.cpp:23</div></div>
<div class="ttc" id="class_n_r_e_1_1_system_1_1_system_php_a9ec11b369f76b5a3c28848214d537a2a"><div class="ttname"><a href="class_n_r_e_1_1_system_1_1_system.php#a9ec11b369f76b5a3c28848214d537a2a">NRE::System::System::getSystemName</a></div><div class="ttdeci">Utility::String getSystemName() const </div><div class="ttdef"><b>Definition:</b> NRE_LinuxSystem.cpp:20</div></div>
<div class="ttc" id="class_n_r_e_1_1_system_1_1_system_php_a5e81c9c5f2f7808cb1498f211155925c"><div class="ttname"><a href="class_n_r_e_1_1_system_1_1_system.php#a5e81c9c5f2f7808cb1498f211155925c">NRE::System::System::operator=</a></div><div class="ttdeci">System &amp; operator=(System &amp;&amp;s)=delete</div></div>
<div class="ttc" id="_n_r_e___cpu_i_d_8hpp_php"><div class="ttname"><a href="_n_r_e___cpu_i_d_8hpp.php">NRE_CpuID.hpp</a></div><div class="ttdoc">Declaration of System&amp;#39;s API&amp;#39;s Object : CpuID. </div></div>
<div class="ttc" id="class_n_r_e_1_1_system_1_1_system_php_aaacfbb3bdc568117a97814127f9d2b37"><div class="ttname"><a href="class_n_r_e_1_1_system_1_1_system.php#aaacfbb3bdc568117a97814127f9d2b37">NRE::System::System::getGraphicsSystem</a></div><div class="ttdeci">GraphicsSystem &amp; getGraphicsSystem()</div></div>
<div class="ttc" id="class_n_r_e_1_1_system_1_1_system_php_aec6231860ffa5d7bd5b4967bc924ae47"><div class="ttname"><a href="class_n_r_e_1_1_system_1_1_system.php#aec6231860ffa5d7bd5b4967bc924ae47">NRE::System::System::getSystemInfo</a></div><div class="ttdeci">SystemInfo const &amp; getSystemInfo() const </div></div>
<div class="ttc" id="class_n_r_e_1_1_system_1_1_graphics_system_php"><div class="ttname"><a href="class_n_r_e_1_1_system_1_1_graphics_system.php">NRE::System::GraphicsSystem</a></div><div class="ttdoc">Manage the graphics sub system. </div><div class="ttdef"><b>Definition:</b> NRE_GraphicsSystem.hpp:32</div></div>
<div class="ttc" id="class_n_r_e_1_1_system_1_1_system_info_php"><div class="ttname"><a href="class_n_r_e_1_1_system_1_1_system_info.php">NRE::System::SystemInfo</a></div><div class="ttdoc">Represent all informations from the user system. </div><div class="ttdef"><b>Definition:</b> NRE_SystemInfo.hpp:31</div></div>
<div class="ttc" id="_n_r_e___event_system_8hpp_php"><div class="ttname"><a href="_n_r_e___event_system_8hpp.php">NRE_EventSystem.hpp</a></div><div class="ttdoc">Declaration of System&amp;#39;s API&amp;#39;s Object : EventSystem. </div></div>
<div class="ttc" id="namespace_system_php"><div class="ttname"><a href="namespace_system.php">System</a></div><div class="ttdoc">System&amp;#39;s API. </div></div>
<div class="ttc" id="_n_r_e___system_info_8hpp_php"><div class="ttname"><a href="_n_r_e___system_info_8hpp.php">NRE_SystemInfo.hpp</a></div><div class="ttdoc">Declaration of System&amp;#39;s API&amp;#39;s Object : SystemInfo. </div></div>
<div class="ttc" id="class_n_r_e_1_1_system_1_1_system_php_aa247ee0adb3423e34af2859b0145c8ed"><div class="ttname"><a href="class_n_r_e_1_1_system_1_1_system.php#aa247ee0adb3423e34af2859b0145c8ed">NRE::System::System::getEventSystem</a></div><div class="ttdeci">EventSystem &amp; getEventSystem()</div></div>
<div class="ttc" id="_n_r_e___clock_8hpp_php"><div class="ttname"><a href="_n_r_e___clock_8hpp.php">NRE_Clock.hpp</a></div><div class="ttdoc">Declaration of Time&amp;#39;s API&amp;#39;s Object : Clock. </div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div></div>
<div class="ttc" id="class_n_r_e_1_1_system_1_1_system_php_ac895939d8863dae1dbed70855a07ec4a"><div class="ttname"><a href="class_n_r_e_1_1_system_1_1_system.php#ac895939d8863dae1dbed70855a07ec4a">NRE::System::System::getClock</a></div><div class="ttdeci">Time::Clock &amp; getClock()</div></div>
<div class="ttc" id="class_n_r_e_1_1_system_1_1_system_php_a30efe5d710af9663cc6df77f40158509"><div class="ttname"><a href="class_n_r_e_1_1_system_1_1_system.php#a30efe5d710af9663cc6df77f40158509">NRE::System::System::~System</a></div><div class="ttdeci">~System()=default</div></div>
<div class="ttc" id="class_n_r_e_1_1_system_1_1_system_php_ac7e24af1a48517898bdbf42c87987d82"><div class="ttname"><a href="class_n_r_e_1_1_system_1_1_system.php#ac7e24af1a48517898bdbf42c87987d82">NRE::System::System::queryCPUName</a></div><div class="ttdeci">void queryCPUName()</div><div class="ttdef"><b>Definition:</b> NRE_LinuxSystem.cpp:54</div></div>
<div class="ttc" id="class_n_r_e_1_1_time_1_1_clock_php"><div class="ttname"><a href="class_n_r_e_1_1_time_1_1_clock.php">NRE::Time::Clock</a></div><div class="ttdoc">Manage timing and program pause. </div><div class="ttdef"><b>Definition:</b> NRE_Clock.hpp:40</div></div>
<div class="ttc" id="_n_r_e___graphics_system_8hpp_php"><div class="ttname"><a href="_n_r_e___graphics_system_8hpp.php">NRE_GraphicsSystem.hpp</a></div><div class="ttdoc">Declaration of System&amp;#39;s API&amp;#39;s Object : GraphicsSystem. </div></div>
<div class="ttc" id="class_n_r_e_1_1_system_1_1_system_php_a364858c330bd950e73c74edf3b465eed"><div class="ttname"><a href="class_n_r_e_1_1_system_1_1_system.php#a364858c330bd950e73c74edf3b465eed">NRE::System::System::queryMemoryInfo</a></div><div class="ttdeci">void queryMemoryInfo()</div><div class="ttdef"><b>Definition:</b> NRE_LinuxSystem.cpp:24</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
