<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: NRE::Graphics::ContextAttributes Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Graphics</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">ContextAttributes</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_graphics_1_1_context_attributes-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Graphics::ContextAttributes Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Regroup all attributes needed in a GL context, should be modified before creation.  
 <a href="class_n_r_e_1_1_graphics_1_1_context_attributes.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___context_attributes_8hpp_source.php">NRE_ContextAttributes.hpp</a>&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:ad65f576552b6ebccbc6239365693b78f"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php#ad65f576552b6ebccbc6239365693b78f">ContextAttributes</a> ()</td></tr>
<tr class="separator:ad65f576552b6ebccbc6239365693b78f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aeabed83fb6618e09b72b1c64c2d4901e"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php#aeabed83fb6618e09b72b1c64c2d4901e">ContextAttributes</a> (std::initializer_list&lt; int &gt; list)</td></tr>
<tr class="separator:aeabed83fb6618e09b72b1c64c2d4901e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a58d11eda2901d0c0fffc4294bb336518"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php#a58d11eda2901d0c0fffc4294bb336518">ContextAttributes</a> (<a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">ContextAttributes</a> const &amp;attr)=default</td></tr>
<tr class="separator:a58d11eda2901d0c0fffc4294bb336518"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab723123dbb59b26f65733e0b7be7f0ac"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php#ab723123dbb59b26f65733e0b7be7f0ac">ContextAttributes</a> (<a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">ContextAttributes</a> &amp;&amp;attr)=default</td></tr>
<tr class="separator:ab723123dbb59b26f65733e0b7be7f0ac"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a81789d26f597fc0f292c3d3ee6acc428"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php#a81789d26f597fc0f292c3d3ee6acc428">~ContextAttributes</a> ()=default</td></tr>
<tr class="separator:a81789d26f597fc0f292c3d3ee6acc428"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3f541ea3c370c76148f4b1ecf4fae608"><td class="memItemLeft" align="right" valign="top">int &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php#a3f541ea3c370c76148f4b1ecf4fae608">operator[]</a> (<a class="el" href="_n_r_e___context_attributes_8hpp.php#a8eaf2bb29661035844777e583db8b899">GLAttributes</a> index)</td></tr>
<tr class="separator:a3f541ea3c370c76148f4b1ecf4fae608"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a881e43f3e302ef65043e00643fc93b8d"><td class="memItemLeft" align="right" valign="top">int const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php#a881e43f3e302ef65043e00643fc93b8d">operator[]</a> (<a class="el" href="_n_r_e___context_attributes_8hpp.php#a8eaf2bb29661035844777e583db8b899">GLAttributes</a> index) const </td></tr>
<tr class="separator:a881e43f3e302ef65043e00643fc93b8d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae1f8e2d48ffba31a7a99ad659bb7c58e"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">ContextAttributes</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php#ae1f8e2d48ffba31a7a99ad659bb7c58e">operator=</a> (<a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">ContextAttributes</a> const &amp;attr)=default</td></tr>
<tr class="separator:ae1f8e2d48ffba31a7a99ad659bb7c58e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a394caf953b6ff8775f34a2fbd782d108"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">ContextAttributes</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php#a394caf953b6ff8775f34a2fbd782d108">operator=</a> (<a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">ContextAttributes</a> &amp;&amp;attr)=default</td></tr>
<tr class="separator:a394caf953b6ff8775f34a2fbd782d108"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Regroup all attributes needed in a GL context, should be modified before creation. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="ad65f576552b6ebccbc6239365693b78f"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Graphics::ContextAttributes::ContextAttributes </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Create a default context attributes </p>

</div>
</div>
<a class="anchor" id="aeabed83fb6618e09b72b1c64c2d4901e"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Graphics::ContextAttributes::ContextAttributes </td>
          <td>(</td>
          <td class="paramtype">std::initializer_list&lt; int &gt;&#160;</td>
          <td class="paramname"><em>list</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Create a context attributes from an attributes list </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">list</td><td>the attributes list </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a58d11eda2901d0c0fffc4294bb336518"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Graphics::ContextAttributes::ContextAttributes </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">ContextAttributes</a> const &amp;&#160;</td>
          <td class="paramname"><em>attr</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy attr into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">attr</td><td>the context attributes to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="ab723123dbb59b26f65733e0b7be7f0ac"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Graphics::ContextAttributes::ContextAttributes </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">ContextAttributes</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>attr</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move attr into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">attr</td><td>the context attributes to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a81789d26f597fc0f292c3d3ee6acc428"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Graphics::ContextAttributes::~ContextAttributes </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php" title="Regroup all attributes needed in a GL context, should be modified before creation. ">ContextAttributes</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="ae1f8e2d48ffba31a7a99ad659bb7c58e"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">ContextAttributes</a>&amp; NRE::Graphics::ContextAttributes::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">ContextAttributes</a> const &amp;&#160;</td>
          <td class="paramname"><em>attr</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy assignment of attr into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">attr</td><td>the context attributes to copy into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a394caf953b6ff8775f34a2fbd782d108"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">ContextAttributes</a>&amp; NRE::Graphics::ContextAttributes::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">ContextAttributes</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>attr</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move assignment of attr into this, leaving o empty </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">attr</td><td>the context attributes to move into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a3f541ea3c370c76148f4b1ecf4fae608"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">int&amp; NRE::Graphics::ContextAttributes::operator[] </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="_n_r_e___context_attributes_8hpp.php#a8eaf2bb29661035844777e583db8b899">GLAttributes</a>&#160;</td>
          <td class="paramname"><em>index</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Access a particular attribute without bound checking </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">index</td><td>the attribute index </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the corresponding attribute </dd></dl>

</div>
</div>
<a class="anchor" id="a881e43f3e302ef65043e00643fc93b8d"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">int const&amp; NRE::Graphics::ContextAttributes::operator[] </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="_n_r_e___context_attributes_8hpp.php#a8eaf2bb29661035844777e583db8b899">GLAttributes</a>&#160;</td>
          <td class="paramname"><em>index</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Access a particular attribute without bound checking </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">index</td><td>the attribute index </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the corresponding attribute </dd></dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Graphics/Driver/Context/Attributes/<a class="el" href="_n_r_e___context_attributes_8hpp_source.php">NRE_ContextAttributes.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
