<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: NRE::Event::EventHandler&lt; T &gt; Class Template Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Event</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php">EventHandler</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-types">Public Types</a> &#124;
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_event_1_1_event_handler-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Event::EventHandler&lt; T &gt; Class Template Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Manage an event handler for a special type.  
 <a href="class_n_r_e_1_1_event_1_1_event_handler.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___event_handler_8hpp_source.php">NRE_EventHandler.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for NRE::Event::EventHandler&lt; T &gt;:</div>
<div class="dyncontent">
 <div class="center">
  <img src="class_n_r_e_1_1_event_1_1_event_handler.png" usemap="#NRE::Event::EventHandler_3C_20T_20_3E_map" alt=""/>
  <map id="NRE::Event::EventHandler_3C_20T_20_3E_map" name="NRE::Event::EventHandler&lt; T &gt;_map">
</map>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-types"></a>
Public Types</h2></td></tr>
<tr class="memitem:a42d134d1d9799590c785e70e7bac0408"><td class="memItemLeft" align="right" valign="top">typedef std::function&lt; bool(T &amp;)&gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php#a42d134d1d9799590c785e70e7bac0408">Handler</a></td></tr>
<tr class="separator:a42d134d1d9799590c785e70e7bac0408"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:aee18ad5984f1d4caed07c117e0ea2a71"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php#aee18ad5984f1d4caed07c117e0ea2a71">EventHandler</a> ()=delete</td></tr>
<tr class="separator:aee18ad5984f1d4caed07c117e0ea2a71"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:adff4ffd419fe8db66af74e58d0fb6169"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php#adff4ffd419fe8db66af74e58d0fb6169">EventHandler</a> (<a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php#a42d134d1d9799590c785e70e7bac0408">Handler</a> &amp;&amp;h)</td></tr>
<tr class="separator:adff4ffd419fe8db66af74e58d0fb6169"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a12ecf90537f60c7a5d46d32ec3b24ccc"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php#a12ecf90537f60c7a5d46d32ec3b24ccc">EventHandler</a> (<a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php">EventHandler</a> const &amp;h)=delete</td></tr>
<tr class="separator:a12ecf90537f60c7a5d46d32ec3b24ccc"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a18dabfff433a6d5f42a8b19c88aff56a"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php#a18dabfff433a6d5f42a8b19c88aff56a">EventHandler</a> (<a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php">EventHandler</a> &amp;&amp;h)=delete</td></tr>
<tr class="separator:a18dabfff433a6d5f42a8b19c88aff56a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a58cd2257e8bc208c70211caeff00f743"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php#a58cd2257e8bc208c70211caeff00f743">~EventHandler</a> ()</td></tr>
<tr class="separator:a58cd2257e8bc208c70211caeff00f743"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:abcbd6863bc67ef68f18ed1b5b1b2e6b4"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php#abcbd6863bc67ef68f18ed1b5b1b2e6b4">update</a> (Utility::Observable *obs, void *arg) override</td></tr>
<tr class="separator:abcbd6863bc67ef68f18ed1b5b1b2e6b4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4d86b6a4273b93f0381fa7dab7b6abe4"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php">EventHandler</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php#a4d86b6a4273b93f0381fa7dab7b6abe4">operator=</a> (<a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php">EventHandler</a> const &amp;h)=delete</td></tr>
<tr class="separator:a4d86b6a4273b93f0381fa7dab7b6abe4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a694519ce97c9d3022852e5f398581268"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php">EventHandler</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php#a694519ce97c9d3022852e5f398581268">operator=</a> (<a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php">EventHandler</a> &amp;&amp;h)=delete</td></tr>
<tr class="separator:a694519ce97c9d3022852e5f398581268"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><h3>template&lt;class T&gt;<br />
class NRE::Event::EventHandler&lt; T &gt;</h3>

<p>Manage an event handler for a special type. </p>
</div><h2 class="groupheader">Member Typedef Documentation</h2>
<a class="anchor" id="a42d134d1d9799590c785e70e7bac0408"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">typedef std::function&lt;bool(T&amp;)&gt; <a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php">NRE::Event::EventHandler</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php#a42d134d1d9799590c785e70e7bac0408">Handler</a></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Shortcut for handler type abstraction </p>

</div>
</div>
<h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="aee18ad5984f1d4caed07c117e0ea2a71"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php">NRE::Event::EventHandler</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php">EventHandler</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Default constructor </p>

</div>
</div>
<a class="anchor" id="adff4ffd419fe8db66af74e58d0fb6169"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php">NRE::Event::EventHandler</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php">EventHandler</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php#a42d134d1d9799590c785e70e7bac0408">Handler</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>h</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct an <a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php" title="Manage an event handler for a special type. ">EventHandler</a> with a passed lambda expression </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">h</td><td>the handler function </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a12ecf90537f60c7a5d46d32ec3b24ccc"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php">NRE::Event::EventHandler</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php">EventHandler</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php">EventHandler</a>&lt; T &gt; const &amp;&#160;</td>
          <td class="paramname"><em>h</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">h</td><td>the event handler to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a18dabfff433a6d5f42a8b19c88aff56a"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php">NRE::Event::EventHandler</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php">EventHandler</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php">EventHandler</a>&lt; T &gt; &amp;&amp;&#160;</td>
          <td class="paramname"><em>h</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">h</td><td>the event handler to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a58cd2257e8bc208c70211caeff00f743"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php">NRE::Event::EventHandler</a>&lt; T &gt;::~<a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php">EventHandler</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php" title="Manage an event handler for a special type. ">EventHandler</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a4d86b6a4273b93f0381fa7dab7b6abe4"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php">EventHandler</a>&amp; <a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php">NRE::Event::EventHandler</a>&lt; T &gt;::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php">EventHandler</a>&lt; T &gt; const &amp;&#160;</td>
          <td class="paramname"><em>h</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">h</td><td>the object to copy into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a694519ce97c9d3022852e5f398581268"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php">EventHandler</a>&amp; <a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php">NRE::Event::EventHandler</a>&lt; T &gt;::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php">EventHandler</a>&lt; T &gt; &amp;&amp;&#160;</td>
          <td class="paramname"><em>h</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">h</td><td>the object to move into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="abcbd6863bc67ef68f18ed1b5b1b2e6b4"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php">NRE::Event::EventHandler</a>&lt; T &gt;::update </td>
          <td>(</td>
          <td class="paramtype">Utility::Observable *&#160;</td>
          <td class="paramname"><em>obs</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">void *&#160;</td>
          <td class="paramname"><em>arg</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">override</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Update the observer when the observable notify it </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">obs</td><td>the observed object </td></tr>
    <tr><td class="paramname">arg</td><td>notification data </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Event/Handler/<a class="el" href="_n_r_e___event_handler_8hpp_source.php">NRE_EventHandler.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
