<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: NRE::System::System Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>System</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_system_1_1_system.php">System</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_system_1_1_system-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::System::System Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Represent the <a class="el" href="class_n_r_e_1_1_system_1_1_system.php" title="Represent the System abstraction layer. ">System</a> abstraction layer.  
 <a href="class_n_r_e_1_1_system_1_1_system.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_system_2_n_r_e___system_8hpp_source.php">NRE_System.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for NRE::System::System:</div>
<div class="dyncontent">
 <div class="center">
  <img src="class_n_r_e_1_1_system_1_1_system.png" usemap="#NRE::System::System_map" alt=""/>
  <map id="NRE::System::System_map" name="NRE::System::System_map">
</map>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a071e220861b0cf5005f79d817bf63775"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_system.php#a071e220861b0cf5005f79d817bf63775">System</a> (<a class="el" href="class_n_r_e_1_1_system_1_1_system.php">System</a> &amp;&amp;sys)=delete</td></tr>
<tr class="separator:a071e220861b0cf5005f79d817bf63775"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a30efe5d710af9663cc6df77f40158509"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_system.php#a30efe5d710af9663cc6df77f40158509">~System</a> ()=default</td></tr>
<tr class="separator:a30efe5d710af9663cc6df77f40158509"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9ec11b369f76b5a3c28848214d537a2a"><td class="memItemLeft" align="right" valign="top">Utility::String&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_system.php#a9ec11b369f76b5a3c28848214d537a2a">getSystemName</a> () const </td></tr>
<tr class="separator:a9ec11b369f76b5a3c28848214d537a2a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aec6231860ffa5d7bd5b4967bc924ae47"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_system_1_1_system_info.php">SystemInfo</a> const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_system.php#aec6231860ffa5d7bd5b4967bc924ae47">getSystemInfo</a> () const </td></tr>
<tr class="separator:aec6231860ffa5d7bd5b4967bc924ae47"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aaacfbb3bdc568117a97814127f9d2b37"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_system_1_1_graphics_system.php">GraphicsSystem</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_system.php#aaacfbb3bdc568117a97814127f9d2b37">getGraphicsSystem</a> ()</td></tr>
<tr class="separator:aaacfbb3bdc568117a97814127f9d2b37"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa247ee0adb3423e34af2859b0145c8ed"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_system_1_1_event_system.php">EventSystem</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_system.php#aa247ee0adb3423e34af2859b0145c8ed">getEventSystem</a> ()</td></tr>
<tr class="separator:aa247ee0adb3423e34af2859b0145c8ed"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac895939d8863dae1dbed70855a07ec4a"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_time_1_1_clock.php">Time::Clock</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_system.php#ac895939d8863dae1dbed70855a07ec4a">getClock</a> ()</td></tr>
<tr class="separator:ac895939d8863dae1dbed70855a07ec4a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a364858c330bd950e73c74edf3b465eed"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_system.php#a364858c330bd950e73c74edf3b465eed">queryMemoryInfo</a> ()</td></tr>
<tr class="separator:a364858c330bd950e73c74edf3b465eed"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8940363632225bbfd082d1b52ebbce23"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_system.php#a8940363632225bbfd082d1b52ebbce23">querySystemInfo</a> ()</td></tr>
<tr class="separator:a8940363632225bbfd082d1b52ebbce23"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac7e24af1a48517898bdbf42c87987d82"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_system.php#ac7e24af1a48517898bdbf42c87987d82">queryCPUName</a> ()</td></tr>
<tr class="separator:ac7e24af1a48517898bdbf42c87987d82"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5e81c9c5f2f7808cb1498f211155925c"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_system_1_1_system.php">System</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_system.php#a5e81c9c5f2f7808cb1498f211155925c">operator=</a> (<a class="el" href="class_n_r_e_1_1_system_1_1_system.php">System</a> &amp;&amp;s)=delete</td></tr>
<tr class="separator:a5e81c9c5f2f7808cb1498f211155925c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a93bfdbddfd9e67689b900258f6d8f2a1"><td class="memItemLeft" align="right" valign="top">Utility::String&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_system.php#a93bfdbddfd9e67689b900258f6d8f2a1">toString</a> () const </td></tr>
<tr class="separator:a93bfdbddfd9e67689b900258f6d8f2a1"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Represent the <a class="el" href="class_n_r_e_1_1_system_1_1_system.php" title="Represent the System abstraction layer. ">System</a> abstraction layer. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a071e220861b0cf5005f79d817bf63775"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::System::System::System </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_system_1_1_system.php">System</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>sys</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">sys</td><td>the system to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a30efe5d710af9663cc6df77f40158509"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::System::System::~System </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_system_1_1_system.php" title="Represent the System abstraction layer. ">System</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="ac895939d8863dae1dbed70855a07ec4a"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_time_1_1_clock.php">Time::Clock</a>&amp; NRE::System::System::getClock </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the system clock </dd></dl>

</div>
</div>
<a class="anchor" id="aa247ee0adb3423e34af2859b0145c8ed"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_system_1_1_event_system.php">EventSystem</a>&amp; NRE::System::System::getEventSystem </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the events sub system </dd></dl>

</div>
</div>
<a class="anchor" id="aaacfbb3bdc568117a97814127f9d2b37"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_system_1_1_graphics_system.php">GraphicsSystem</a>&amp; NRE::System::System::getGraphicsSystem </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the graphics sub system </dd></dl>

</div>
</div>
<a class="anchor" id="aec6231860ffa5d7bd5b4967bc924ae47"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_system_1_1_system_info.php">SystemInfo</a> const&amp; NRE::System::System::getSystemInfo </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the <a class="el" href="class_n_r_e_1_1_system_1_1_system.php" title="Represent the System abstraction layer. ">System</a> info </dd></dl>

</div>
</div>
<a class="anchor" id="a9ec11b369f76b5a3c28848214d537a2a"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">String NRE::System::System::getSystemName </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the system's name </dd></dl>

</div>
</div>
<a class="anchor" id="a5e81c9c5f2f7808cb1498f211155925c"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_system_1_1_system.php">System</a>&amp; NRE::System::System::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_system_1_1_system.php">System</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>s</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">s</td><td>the object to move into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="ac7e24af1a48517898bdbf42c87987d82"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::System::System::queryCPUName </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Query the CPU's name </p>

</div>
</div>
<a class="anchor" id="a364858c330bd950e73c74edf3b465eed"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::System::System::queryMemoryInfo </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Query the <a class="el" href="class_n_r_e_1_1_system_1_1_system.php" title="Represent the System abstraction layer. ">System</a>'s Memory info </p>

</div>
</div>
<a class="anchor" id="a8940363632225bbfd082d1b52ebbce23"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::System::System::querySystemInfo </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Query the <a class="el" href="class_n_r_e_1_1_system_1_1_system.php" title="Represent the System abstraction layer. ">System</a>'s Info </p>

</div>
</div>
<a class="anchor" id="a93bfdbddfd9e67689b900258f6d8f2a1"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">String NRE::System::System::toString </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Convert the system into a string </p><dl class="section return"><dt>Returns</dt><dd>the converted system </dd></dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/<a class="el" href="_system_2_n_r_e___system_8hpp_source.php">NRE_System.hpp</a></li>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/OS/Linux/<a class="el" href="_n_r_e___linux_system_8cpp.php">NRE_LinuxSystem.cpp</a></li>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/OS/Windows/<a class="el" href="_n_r_e___windows_system_8cpp.php">NRE_WindowsSystem.cpp</a></li>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/<a class="el" href="_n_r_e___system_8cpp.php">NRE_System.cpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
