<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: NRE::Time::Clock Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Time</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_time_1_1_clock.php">Clock</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pub-static-attribs">Static Public Attributes</a> &#124;
<a href="class_n_r_e_1_1_time_1_1_clock-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Time::Clock Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Manage timing and program pause.  
 <a href="class_n_r_e_1_1_time_1_1_clock.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___clock_8hpp_source.php">NRE_Clock.hpp</a>&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:ac2d4b5d1580b750386ef55cb5c5f9769"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_time_1_1_clock.php#ac2d4b5d1580b750386ef55cb5c5f9769">Clock</a> ()</td></tr>
<tr class="separator:ac2d4b5d1580b750386ef55cb5c5f9769"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a280e8bcf00a40426c5583fdddfadafd0"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_time_1_1_clock.php#a280e8bcf00a40426c5583fdddfadafd0">Clock</a> (<a class="el" href="class_n_r_e_1_1_time_1_1_clock.php">Clock</a> const &amp;c)=default</td></tr>
<tr class="separator:a280e8bcf00a40426c5583fdddfadafd0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a76c02ac205819a4376b5b28f96bdaf01"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_time_1_1_clock.php#a76c02ac205819a4376b5b28f96bdaf01">Clock</a> (<a class="el" href="class_n_r_e_1_1_time_1_1_clock.php">Clock</a> &amp;&amp;c)=default</td></tr>
<tr class="separator:a76c02ac205819a4376b5b28f96bdaf01"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a27f33c16e7ae21b959ca57ea161e58bb"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_time_1_1_clock.php#a27f33c16e7ae21b959ca57ea161e58bb">~Clock</a> ()=default</td></tr>
<tr class="separator:a27f33c16e7ae21b959ca57ea161e58bb"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac5b2dec3b35c168d02a1433ce4e5c64e"><td class="memItemLeft" align="right" valign="top"><a class="el" href="_n_r_e___clock_8hpp.php#ab1956335fcfad28ae6fd32e8d9b1249d">TimeStep</a> const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_time_1_1_clock.php#ac5b2dec3b35c168d02a1433ce4e5c64e">getTimestep</a> () const </td></tr>
<tr class="separator:ac5b2dec3b35c168d02a1433ce4e5c64e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aab40084fb604b17969006b707208e015"><td class="memItemLeft" align="right" valign="top">float&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_time_1_1_clock.php#aab40084fb604b17969006b707208e015">getDelta</a> () const </td></tr>
<tr class="separator:aab40084fb604b17969006b707208e015"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1e2d008610a63cc7bcefecc1a0c2547a"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_time_1_1_clock.php#a1e2d008610a63cc7bcefecc1a0c2547a">update</a> ()</td></tr>
<tr class="separator:a1e2d008610a63cc7bcefecc1a0c2547a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac26847d5b64b5ab6df415765fe4a36af"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_time_1_1_clock.php#ac26847d5b64b5ab6df415765fe4a36af">updateAndSleep</a> (<a class="el" href="_n_r_e___clock_8hpp.php#ab1956335fcfad28ae6fd32e8d9b1249d">TimeStep</a> const &amp;time)</td></tr>
<tr class="separator:ac26847d5b64b5ab6df415765fe4a36af"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad38ac4031cc4c65a0eb7ef1f350fac4b"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_time_1_1_clock.php#ad38ac4031cc4c65a0eb7ef1f350fac4b">sleep</a> (<a class="el" href="_n_r_e___clock_8hpp.php#ab1956335fcfad28ae6fd32e8d9b1249d">TimeStep</a> const &amp;time)</td></tr>
<tr class="separator:ad38ac4031cc4c65a0eb7ef1f350fac4b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a15fbdd1027cbb859d5cdb88f67ee9d5d"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_time_1_1_clock.php#a15fbdd1027cbb859d5cdb88f67ee9d5d">showFPS</a> ()</td></tr>
<tr class="separator:a15fbdd1027cbb859d5cdb88f67ee9d5d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a43f4e99cfb7c1a83504b3f12c3a39135"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_time_1_1_clock.php#a43f4e99cfb7c1a83504b3f12c3a39135">hideFPS</a> ()</td></tr>
<tr class="separator:a43f4e99cfb7c1a83504b3f12c3a39135"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac0f40674f22edc75a7138dce945ef195"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_time_1_1_clock.php">Clock</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_time_1_1_clock.php#ac0f40674f22edc75a7138dce945ef195">operator=</a> (<a class="el" href="class_n_r_e_1_1_time_1_1_clock.php">Clock</a> const &amp;c)=default</td></tr>
<tr class="separator:ac0f40674f22edc75a7138dce945ef195"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acd00e63510ebba422ace06a2d452928e"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_time_1_1_clock.php">Clock</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_time_1_1_clock.php#acd00e63510ebba422ace06a2d452928e">operator=</a> (<a class="el" href="class_n_r_e_1_1_time_1_1_clock.php">Clock</a> &amp;&amp;c)=default</td></tr>
<tr class="separator:acd00e63510ebba422ace06a2d452928e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6ac7db084c2bbe7d765b18578c28ad80"><td class="memItemLeft" align="right" valign="top">Utility::String&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_time_1_1_clock.php#a6ac7db084c2bbe7d765b18578c28ad80">toString</a> () const </td></tr>
<tr class="separator:a6ac7db084c2bbe7d765b18578c28ad80"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-static-attribs"></a>
Static Public Attributes</h2></td></tr>
<tr class="memitem:a8c0dffc9c6f3bf190d7ed1580a9b72fb"><td class="memItemLeft" align="right" valign="top">static float&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_time_1_1_clock.php#a8c0dffc9c6f3bf190d7ed1580a9b72fb">TIMESTEP</a> = 0</td></tr>
<tr class="separator:a8c0dffc9c6f3bf190d7ed1580a9b72fb"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Manage timing and program pause. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="ac2d4b5d1580b750386ef55cb5c5f9769"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Time::Clock::Clock </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Default constructor </p>

</div>
</div>
<a class="anchor" id="a280e8bcf00a40426c5583fdddfadafd0"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Time::Clock::Clock </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_time_1_1_clock.php">Clock</a> const &amp;&#160;</td>
          <td class="paramname"><em>c</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy c into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">c</td><td>the clock to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a76c02ac205819a4376b5b28f96bdaf01"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Time::Clock::Clock </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_time_1_1_clock.php">Clock</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>c</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move c into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">c</td><td>the clock to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a27f33c16e7ae21b959ca57ea161e58bb"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Time::Clock::~Clock </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_time_1_1_clock.php" title="Manage timing and program pause. ">Clock</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="aab40084fb604b17969006b707208e015"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">float NRE::Time::Clock::getDelta </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the timestep with float format </dd></dl>

</div>
</div>
<a class="anchor" id="ac5b2dec3b35c168d02a1433ce4e5c64e"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="_n_r_e___clock_8hpp.php#ab1956335fcfad28ae6fd32e8d9b1249d">TimeStep</a> const&amp; NRE::Time::Clock::getTimestep </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the clock's timestep </dd></dl>

</div>
</div>
<a class="anchor" id="a43f4e99cfb7c1a83504b3f12c3a39135"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Time::Clock::hideFPS </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Disable fps display </p>

</div>
</div>
<a class="anchor" id="ac0f40674f22edc75a7138dce945ef195"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_time_1_1_clock.php">Clock</a>&amp; NRE::Time::Clock::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_time_1_1_clock.php">Clock</a> const &amp;&#160;</td>
          <td class="paramname"><em>c</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy assignment of c into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">c</td><td>the clock to copy into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="acd00e63510ebba422ace06a2d452928e"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_time_1_1_clock.php">Clock</a>&amp; NRE::Time::Clock::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_time_1_1_clock.php">Clock</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>c</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move assignment of c into this, leaving c empty </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">c</td><td>the clock to move into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a15fbdd1027cbb859d5cdb88f67ee9d5d"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Time::Clock::showFPS </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Enable fps display </p>

</div>
</div>
<a class="anchor" id="ad38ac4031cc4c65a0eb7ef1f350fac4b"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Time::Clock::sleep </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="_n_r_e___clock_8hpp.php#ab1956335fcfad28ae6fd32e8d9b1249d">TimeStep</a> const &amp;&#160;</td>
          <td class="paramname"><em>time</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Sleep for a given time </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">time</td><td>the timestep to sleep </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a6ac7db084c2bbe7d765b18578c28ad80"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">String NRE::Time::Clock::toString </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Convert the clock into a string </p><dl class="section return"><dt>Returns</dt><dd>the converted clock </dd></dl>

</div>
</div>
<a class="anchor" id="a1e2d008610a63cc7bcefecc1a0c2547a"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Time::Clock::update </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Update the clock </p>

</div>
</div>
<a class="anchor" id="ac26847d5b64b5ab6df415765fe4a36af"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Time::Clock::updateAndSleep </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="_n_r_e___clock_8hpp.php#ab1956335fcfad28ae6fd32e8d9b1249d">TimeStep</a> const &amp;&#160;</td>
          <td class="paramname"><em>time</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Update the clock and sleep if the timestep is lesser than the given limit </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">time</td><td>the minimum timestep </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<h2 class="groupheader">Member Data Documentation</h2>
<a class="anchor" id="a8c0dffc9c6f3bf190d7ed1580a9b72fb"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">float NRE::Time::Clock::TIMESTEP = 0</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>The application's delta </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Time/Clock/<a class="el" href="_n_r_e___clock_8hpp_source.php">NRE_Clock.hpp</a></li>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Time/Clock/<a class="el" href="_n_r_e___clock_8cpp.php">NRE_Clock.cpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
