<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: NRE::Event::MotionEvent Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Event</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_event_1_1_motion_event.php">MotionEvent</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_event_1_1_motion_event-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Event::MotionEvent Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Manage a controller motion event.  
 <a href="class_n_r_e_1_1_event_1_1_motion_event.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___motion_event_8hpp_source.php">NRE_MotionEvent.hpp</a>&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:aacc47c54bf59794481c332523371a950"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_motion_event.php#aacc47c54bf59794481c332523371a950">MotionEvent</a> ()=delete</td></tr>
<tr class="separator:aacc47c54bf59794481c332523371a950"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab34ccbfd3672e40b53daf92ff8ce1b79"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_motion_event.php#ab34ccbfd3672e40b53daf92ff8ce1b79">MotionEvent</a> (<a class="el" href="_n_r_e___buttons_8hpp.php#a3117cef30b4eed21ee57db72bd9d3ef8">ButtonCode</a> c, Math::Point2D&lt; unsigned int &gt; const &amp;pos)</td></tr>
<tr class="separator:ab34ccbfd3672e40b53daf92ff8ce1b79"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a32b1458e3203426a60f90e29a5b146be"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_motion_event.php#a32b1458e3203426a60f90e29a5b146be">MotionEvent</a> (<a class="el" href="class_n_r_e_1_1_event_1_1_motion_event.php">MotionEvent</a> const &amp;e)=default</td></tr>
<tr class="separator:a32b1458e3203426a60f90e29a5b146be"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aebcaa6b769249662b962bacf2329ffed"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_motion_event.php#aebcaa6b769249662b962bacf2329ffed">MotionEvent</a> (<a class="el" href="class_n_r_e_1_1_event_1_1_motion_event.php">MotionEvent</a> &amp;&amp;e)=default</td></tr>
<tr class="separator:aebcaa6b769249662b962bacf2329ffed"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7e9611d5a255a13b806da69e7a4eb4b5"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_motion_event.php#a7e9611d5a255a13b806da69e7a4eb4b5">~MotionEvent</a> ()=default</td></tr>
<tr class="separator:a7e9611d5a255a13b806da69e7a4eb4b5"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a635696b185c15a978cb7d0443a50549d"><td class="memItemLeft" align="right" valign="top"><a class="el" href="_n_r_e___buttons_8hpp.php#a3117cef30b4eed21ee57db72bd9d3ef8">ButtonCode</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_motion_event.php#a635696b185c15a978cb7d0443a50549d">getCode</a> () const </td></tr>
<tr class="separator:a635696b185c15a978cb7d0443a50549d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af96a0a6eee49ee320313e6d134c5dcbb"><td class="memItemLeft" align="right" valign="top">Math::Point2D&lt; unsigned int &gt; const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_motion_event.php#af96a0a6eee49ee320313e6d134c5dcbb">getPosition</a> () const </td></tr>
<tr class="separator:af96a0a6eee49ee320313e6d134c5dcbb"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8270a0f73eb36d36b183afb02581c2ae"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_motion_event.php#a8270a0f73eb36d36b183afb02581c2ae">isCode</a> (<a class="el" href="_n_r_e___buttons_8hpp.php#a3117cef30b4eed21ee57db72bd9d3ef8">ButtonCode</a> c) const </td></tr>
<tr class="separator:a8270a0f73eb36d36b183afb02581c2ae"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2160634a53f34dca907062cd08574f24"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_event_1_1_motion_event.php">MotionEvent</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_motion_event.php#a2160634a53f34dca907062cd08574f24">operator=</a> (<a class="el" href="class_n_r_e_1_1_event_1_1_motion_event.php">MotionEvent</a> const &amp;e)=default</td></tr>
<tr class="separator:a2160634a53f34dca907062cd08574f24"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a25343307a5f9e574691a4a9518f1e05e"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_event_1_1_motion_event.php">MotionEvent</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_motion_event.php#a25343307a5f9e574691a4a9518f1e05e">operator=</a> (<a class="el" href="class_n_r_e_1_1_event_1_1_motion_event.php">MotionEvent</a> &amp;&amp;e)=default</td></tr>
<tr class="separator:a25343307a5f9e574691a4a9518f1e05e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a32948df1cec46edbe33ec82dd5d4ce9b"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_motion_event.php#a32948df1cec46edbe33ec82dd5d4ce9b">operator==</a> (<a class="el" href="class_n_r_e_1_1_event_1_1_motion_event.php">MotionEvent</a> const &amp;e) const </td></tr>
<tr class="separator:a32948df1cec46edbe33ec82dd5d4ce9b"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Manage a controller motion event. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="aacc47c54bf59794481c332523371a950"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Event::MotionEvent::MotionEvent </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Default constructor </p>

</div>
</div>
<a class="anchor" id="ab34ccbfd3672e40b53daf92ff8ce1b79"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Event::MotionEvent::MotionEvent </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="_n_r_e___buttons_8hpp.php#a3117cef30b4eed21ee57db72bd9d3ef8">ButtonCode</a>&#160;</td>
          <td class="paramname"><em>c</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Math::Point2D&lt; unsigned int &gt; const &amp;&#160;</td>
          <td class="paramname"><em>pos</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct the event </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">c</td><td>the button code </td></tr>
    <tr><td class="paramname">pos</td><td>the curosr position </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a32b1458e3203426a60f90e29a5b146be"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Event::MotionEvent::MotionEvent </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_event_1_1_motion_event.php">MotionEvent</a> const &amp;&#160;</td>
          <td class="paramname"><em>e</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy e into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">e</td><td>the motion event to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="aebcaa6b769249662b962bacf2329ffed"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Event::MotionEvent::MotionEvent </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_event_1_1_motion_event.php">MotionEvent</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>e</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move e into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">e</td><td>the motion event to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a7e9611d5a255a13b806da69e7a4eb4b5"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Event::MotionEvent::~MotionEvent </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_event_1_1_motion_event.php" title="Manage a controller motion event. ">MotionEvent</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a635696b185c15a978cb7d0443a50549d"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="_n_r_e___buttons_8hpp.php#a3117cef30b4eed21ee57db72bd9d3ef8">ButtonCode</a> NRE::Event::MotionEvent::getCode </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the button's code </dd></dl>

</div>
</div>
<a class="anchor" id="af96a0a6eee49ee320313e6d134c5dcbb"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">Math::Point2D&lt;unsigned int&gt; const&amp; NRE::Event::MotionEvent::getPosition </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the cursor position </dd></dl>

</div>
</div>
<a class="anchor" id="a8270a0f73eb36d36b183afb02581c2ae"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">bool NRE::Event::MotionEvent::isCode </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="_n_r_e___buttons_8hpp.php#a3117cef30b4eed21ee57db72bd9d3ef8">ButtonCode</a>&#160;</td>
          <td class="paramname"><em>c</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Compare the event code to the given one </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">c</td><td>a button code </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the test's result </dd></dl>

</div>
</div>
<a class="anchor" id="a2160634a53f34dca907062cd08574f24"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_event_1_1_motion_event.php">MotionEvent</a>&amp; NRE::Event::MotionEvent::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_event_1_1_motion_event.php">MotionEvent</a> const &amp;&#160;</td>
          <td class="paramname"><em>e</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy e into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">e</td><td>the object to copy into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a25343307a5f9e574691a4a9518f1e05e"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_event_1_1_motion_event.php">MotionEvent</a>&amp; NRE::Event::MotionEvent::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_event_1_1_motion_event.php">MotionEvent</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>e</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy e into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">e</td><td>the object to copy into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a32948df1cec46edbe33ec82dd5d4ce9b"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">bool NRE::Event::MotionEvent::operator== </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_event_1_1_motion_event.php">MotionEvent</a> const &amp;&#160;</td>
          <td class="paramname"><em>e</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Equality test between this and an object </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">e</td><td>the other object </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the test result </dd></dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Event/Event/Motion/<a class="el" href="_n_r_e___motion_event_8hpp_source.php">NRE_MotionEvent.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
