<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: DevApplication Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_dev_application-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">DevApplication Class Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="dynheader">
Inheritance diagram for DevApplication:</div>
<div class="dyncontent">
 <div class="center">
  <img src="class_dev_application.png" usemap="#DevApplication_map" alt=""/>
  <map id="DevApplication_map" name="DevApplication_map">
<area href="class_n_r_e_1_1_system_1_1_application.php" title="Manage an user application. " alt="NRE::System::Application" shape="rect" coords="0,0,152,24"/>
</map>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a9e2481d2ae9ec56c07230690c18218e0"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_dev_application.php#a9e2481d2ae9ec56c07230690c18218e0">create</a> () override</td></tr>
<tr class="separator:a9e2481d2ae9ec56c07230690c18218e0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae6f34c5c8f81903c448ffba296fa005d"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_dev_application.php#ae6f34c5c8f81903c448ffba296fa005d">update</a> () override</td></tr>
<tr class="separator:ae6f34c5c8f81903c448ffba296fa005d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1723ab47f59a1d0205b03795a52a530c"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_dev_application.php#a1723ab47f59a1d0205b03795a52a530c">render</a> () override</td></tr>
<tr class="separator:a1723ab47f59a1d0205b03795a52a530c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:adf819436e1c2ad1b76ae0d57322f3817"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_dev_application.php#adf819436e1c2ad1b76ae0d57322f3817">destroy</a> () override</td></tr>
<tr class="separator:adf819436e1c2ad1b76ae0d57322f3817"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_methods_class_n_r_e_1_1_system_1_1_application"><td colspan="2" onclick="javascript:toggleInherit('pub_methods_class_n_r_e_1_1_system_1_1_application')"><img src="closed.png" alt="-"/>&#160;Public Member Functions inherited from <a class="el" href="class_n_r_e_1_1_system_1_1_application.php">NRE::System::Application</a></td></tr>
<tr class="memitem:a7e91b3d4219b340ff9d92e3f95c24e57 inherit pub_methods_class_n_r_e_1_1_system_1_1_application"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_application.php#a7e91b3d4219b340ff9d92e3f95c24e57">Application</a> ()=delete</td></tr>
<tr class="separator:a7e91b3d4219b340ff9d92e3f95c24e57 inherit pub_methods_class_n_r_e_1_1_system_1_1_application"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2b7e38709a8d9ab78e93f0fca2fa9a12 inherit pub_methods_class_n_r_e_1_1_system_1_1_application"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_application.php#a2b7e38709a8d9ab78e93f0fca2fa9a12">Application</a> (Utility::String const &amp;title, Math::Point2D&lt; unsigned int &gt; const &amp;position, Math::Vector2D&lt; unsigned int &gt; const &amp;size, unsigned int style, <a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">Graphics::ContextAttributes</a> const &amp;attr=<a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">Graphics::ContextAttributes</a>())</td></tr>
<tr class="separator:a2b7e38709a8d9ab78e93f0fca2fa9a12 inherit pub_methods_class_n_r_e_1_1_system_1_1_application"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:add8202c6e0befe8f09f2ad4dfc072898 inherit pub_methods_class_n_r_e_1_1_system_1_1_application"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_application.php#add8202c6e0befe8f09f2ad4dfc072898">Application</a> (Utility::String const &amp;title, Math::Vector2D&lt; unsigned int &gt; const &amp;size, unsigned int style, <a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">Graphics::ContextAttributes</a> const &amp;attr=<a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">Graphics::ContextAttributes</a>())</td></tr>
<tr class="separator:add8202c6e0befe8f09f2ad4dfc072898 inherit pub_methods_class_n_r_e_1_1_system_1_1_application"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad6bf28c20609905b63ee4ad13e7acdf6 inherit pub_methods_class_n_r_e_1_1_system_1_1_application"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_application.php#ad6bf28c20609905b63ee4ad13e7acdf6">Application</a> (<a class="el" href="class_n_r_e_1_1_system_1_1_application.php">Application</a> const &amp;app)=delete</td></tr>
<tr class="separator:ad6bf28c20609905b63ee4ad13e7acdf6 inherit pub_methods_class_n_r_e_1_1_system_1_1_application"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a41c56934497f4c5d5ef321e6b979b488 inherit pub_methods_class_n_r_e_1_1_system_1_1_application"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_application.php#a41c56934497f4c5d5ef321e6b979b488">Application</a> (<a class="el" href="class_n_r_e_1_1_system_1_1_application.php">Application</a> &amp;&amp;app)=delete</td></tr>
<tr class="separator:a41c56934497f4c5d5ef321e6b979b488 inherit pub_methods_class_n_r_e_1_1_system_1_1_application"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9fcb9646e9736afa161f41ca11581835 inherit pub_methods_class_n_r_e_1_1_system_1_1_application"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_application.php#a9fcb9646e9736afa161f41ca11581835">~Application</a> ()</td></tr>
<tr class="separator:a9fcb9646e9736afa161f41ca11581835 inherit pub_methods_class_n_r_e_1_1_system_1_1_application"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6f7a8eb37b949821baac564f043760d1 inherit pub_methods_class_n_r_e_1_1_system_1_1_application"><td class="memTemplParams" colspan="2">template&lt;class T &gt; </td></tr>
<tr class="memitem:a6f7a8eb37b949821baac564f043760d1 inherit pub_methods_class_n_r_e_1_1_system_1_1_application"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_application.php#a6f7a8eb37b949821baac564f043760d1">addHandler</a> (typename <a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php">Event::EventHandler</a>&lt; T &gt;::Handler &amp;&amp;handler)</td></tr>
<tr class="separator:a6f7a8eb37b949821baac564f043760d1 inherit pub_methods_class_n_r_e_1_1_system_1_1_application"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3f0bcb146c0f1f64155718618f6c9dce inherit pub_methods_class_n_r_e_1_1_system_1_1_application"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_application.php#a3f0bcb146c0f1f64155718618f6c9dce">NREmain</a> ()</td></tr>
<tr class="separator:a3f0bcb146c0f1f64155718618f6c9dce inherit pub_methods_class_n_r_e_1_1_system_1_1_application"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a91a31e944a7767fe6c75579370dc9fda inherit pub_methods_class_n_r_e_1_1_system_1_1_application"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_system_1_1_application.php">Application</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_application.php#a91a31e944a7767fe6c75579370dc9fda">operator=</a> (<a class="el" href="class_n_r_e_1_1_system_1_1_application.php">Application</a> const &amp;app)=delete</td></tr>
<tr class="separator:a91a31e944a7767fe6c75579370dc9fda inherit pub_methods_class_n_r_e_1_1_system_1_1_application"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad7e2fff6d6858524305a44526b213398 inherit pub_methods_class_n_r_e_1_1_system_1_1_application"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_system_1_1_application.php">Application</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_application.php#ad7e2fff6d6858524305a44526b213398">operator=</a> (<a class="el" href="class_n_r_e_1_1_system_1_1_application.php">Application</a> &amp;&amp;app)=delete</td></tr>
<tr class="separator:ad7e2fff6d6858524305a44526b213398 inherit pub_methods_class_n_r_e_1_1_system_1_1_application"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a9e2481d2ae9ec56c07230690c18218e0"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void DevApplication::create </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span><span class="mlabel">override</span><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Called at the application's creation </p>

<p>Implements <a class="el" href="class_n_r_e_1_1_system_1_1_application.php#ae260cd0edfb36c05366f227de079e986">NRE::System::Application</a>.</p>

</div>
</div>
<a class="anchor" id="adf819436e1c2ad1b76ae0d57322f3817"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void DevApplication::destroy </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span><span class="mlabel">override</span><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Called at application's destruction </p>

<p>Implements <a class="el" href="class_n_r_e_1_1_system_1_1_application.php#add0eae3e71241478586e6781d6ddd327">NRE::System::Application</a>.</p>

</div>
</div>
<a class="anchor" id="a1723ab47f59a1d0205b03795a52a530c"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void DevApplication::render </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span><span class="mlabel">override</span><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Called after application's update, every frame </p>

<p>Implements <a class="el" href="class_n_r_e_1_1_system_1_1_application.php#ae538f4a0b860650369a8af2af5135e9e">NRE::System::Application</a>.</p>

</div>
</div>
<a class="anchor" id="ae6f34c5c8f81903c448ffba296fa005d"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void DevApplication::update </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span><span class="mlabel">override</span><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Called before application's render, every frame </p>

<p>Implements <a class="el" href="class_n_r_e_1_1_system_1_1_application.php#a99093f5efe59dab4c5be09df98b42481">NRE::System::Application</a>.</p>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/<a class="el" href="_n_r_e___main_8cpp.php">NRE_Main.cpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
