<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: NRE::Event::KeyEvent Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Event</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_event_1_1_key_event.php">KeyEvent</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_event_1_1_key_event-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Event::KeyEvent Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Manage a key event.  
 <a href="class_n_r_e_1_1_event_1_1_key_event.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___key_event_8hpp_source.php">NRE_KeyEvent.hpp</a>&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a3293927d97fd74f66849c2bffa92c3b2"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_key_event.php#a3293927d97fd74f66849c2bffa92c3b2">KeyEvent</a> ()=delete</td></tr>
<tr class="separator:a3293927d97fd74f66849c2bffa92c3b2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad595c8589e3a9ab2aaf45e3fd7f4b86c"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_key_event.php#ad595c8589e3a9ab2aaf45e3fd7f4b86c">KeyEvent</a> (<a class="el" href="_n_r_e___keys_8hpp.php#aad0b5de9f5c32805861bae5dda36d501">KeyCode</a> c)</td></tr>
<tr class="separator:ad595c8589e3a9ab2aaf45e3fd7f4b86c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a328972b874fd61129b5dcf24bfe03a7d"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_key_event.php#a328972b874fd61129b5dcf24bfe03a7d">KeyEvent</a> (<a class="el" href="class_n_r_e_1_1_event_1_1_key_event.php">KeyEvent</a> const &amp;e)=default</td></tr>
<tr class="separator:a328972b874fd61129b5dcf24bfe03a7d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3579b468391a881e7f2090f0aa9f9339"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_key_event.php#a3579b468391a881e7f2090f0aa9f9339">KeyEvent</a> (<a class="el" href="class_n_r_e_1_1_event_1_1_key_event.php">KeyEvent</a> &amp;&amp;e)=default</td></tr>
<tr class="separator:a3579b468391a881e7f2090f0aa9f9339"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9a66427aa3ecd3164045effe16b8af9b"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_key_event.php#a9a66427aa3ecd3164045effe16b8af9b">~KeyEvent</a> ()=default</td></tr>
<tr class="separator:a9a66427aa3ecd3164045effe16b8af9b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aee6a39224443d71b48c315cb4620cc18"><td class="memItemLeft" align="right" valign="top"><a class="el" href="_n_r_e___keys_8hpp.php#aad0b5de9f5c32805861bae5dda36d501">KeyCode</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_key_event.php#aee6a39224443d71b48c315cb4620cc18">getCode</a> () const </td></tr>
<tr class="separator:aee6a39224443d71b48c315cb4620cc18"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a11b37ea31b6c81d85da5197db900d02b"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_key_event.php#a11b37ea31b6c81d85da5197db900d02b">isCode</a> (<a class="el" href="_n_r_e___keys_8hpp.php#aad0b5de9f5c32805861bae5dda36d501">KeyCode</a> c) const </td></tr>
<tr class="separator:a11b37ea31b6c81d85da5197db900d02b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac57ca1e1ee589079867f0d623f24660c"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_event_1_1_key_event.php">KeyEvent</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_key_event.php#ac57ca1e1ee589079867f0d623f24660c">operator=</a> (<a class="el" href="class_n_r_e_1_1_event_1_1_key_event.php">KeyEvent</a> const &amp;e)=default</td></tr>
<tr class="separator:ac57ca1e1ee589079867f0d623f24660c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a20e02d34f3c439a5062f79b540176bf0"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_event_1_1_key_event.php">KeyEvent</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_key_event.php#a20e02d34f3c439a5062f79b540176bf0">operator=</a> (<a class="el" href="class_n_r_e_1_1_event_1_1_key_event.php">KeyEvent</a> &amp;&amp;e)=default</td></tr>
<tr class="separator:a20e02d34f3c439a5062f79b540176bf0"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Manage a key event. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a3293927d97fd74f66849c2bffa92c3b2"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Event::KeyEvent::KeyEvent </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Default constructor </p>

</div>
</div>
<a class="anchor" id="ad595c8589e3a9ab2aaf45e3fd7f4b86c"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Event::KeyEvent::KeyEvent </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="_n_r_e___keys_8hpp.php#aad0b5de9f5c32805861bae5dda36d501">KeyCode</a>&#160;</td>
          <td class="paramname"><em>c</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct the event from the key code </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">c</td><td>the key code </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a328972b874fd61129b5dcf24bfe03a7d"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Event::KeyEvent::KeyEvent </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_event_1_1_key_event.php">KeyEvent</a> const &amp;&#160;</td>
          <td class="paramname"><em>e</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy e into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">e</td><td>the key event to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a3579b468391a881e7f2090f0aa9f9339"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Event::KeyEvent::KeyEvent </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_event_1_1_key_event.php">KeyEvent</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>e</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move e into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">e</td><td>the key event to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a9a66427aa3ecd3164045effe16b8af9b"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Event::KeyEvent::~KeyEvent </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_event_1_1_key_event.php" title="Manage a key event. ">KeyEvent</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="aee6a39224443d71b48c315cb4620cc18"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="_n_r_e___keys_8hpp.php#aad0b5de9f5c32805861bae5dda36d501">KeyCode</a> NRE::Event::KeyEvent::getCode </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the key's code </dd></dl>

</div>
</div>
<a class="anchor" id="a11b37ea31b6c81d85da5197db900d02b"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">bool NRE::Event::KeyEvent::isCode </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="_n_r_e___keys_8hpp.php#aad0b5de9f5c32805861bae5dda36d501">KeyCode</a>&#160;</td>
          <td class="paramname"><em>c</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Compare the event code to the given one </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">c</td><td>a key code </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the test's result </dd></dl>

</div>
</div>
<a class="anchor" id="ac57ca1e1ee589079867f0d623f24660c"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_event_1_1_key_event.php">KeyEvent</a>&amp; NRE::Event::KeyEvent::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_event_1_1_key_event.php">KeyEvent</a> const &amp;&#160;</td>
          <td class="paramname"><em>e</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy e into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">e</td><td>the object to copy into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a20e02d34f3c439a5062f79b540176bf0"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_event_1_1_key_event.php">KeyEvent</a>&amp; NRE::Event::KeyEvent::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_event_1_1_key_event.php">KeyEvent</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>e</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy e into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">e</td><td>the object to copy into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Event/Event/Key/<a class="el" href="_n_r_e___key_event_8hpp_source.php">NRE_KeyEvent.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
