<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: NRE::System::CpuID Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>System</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_system_1_1_cpu_i_d.php">CpuID</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_system_1_1_cpu_i_d-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::System::CpuID Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Allow access to the cpuid intrinsic command for all system.  
 <a href="class_n_r_e_1_1_system_1_1_cpu_i_d.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___cpu_i_d_8hpp_source.php">NRE_CpuID.hpp</a>&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:ac04fc36f36ff255faec57c2fdfc83967"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_cpu_i_d.php#ac04fc36f36ff255faec57c2fdfc83967">CpuID</a> ()=delete</td></tr>
<tr class="separator:ac04fc36f36ff255faec57c2fdfc83967"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a11d80169526aaf00d13f3528fc07e489"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_cpu_i_d.php#a11d80169526aaf00d13f3528fc07e489">CpuID</a> (unsigned int i)</td></tr>
<tr class="separator:a11d80169526aaf00d13f3528fc07e489"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab26379e14f22509c390fc3673586948c"><td class="memItemLeft" align="right" valign="top">Register const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_cpu_i_d.php#ab26379e14f22509c390fc3673586948c">getRegister</a> (unsigned int index) const </td></tr>
<tr class="separator:ab26379e14f22509c390fc3673586948c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a31efb1583c0414b452c53ac1ef492ca7"><td class="memItemLeft" align="right" valign="top">const Register *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_cpu_i_d.php#a31efb1583c0414b452c53ac1ef492ca7">getRegisters</a> () const </td></tr>
<tr class="separator:a31efb1583c0414b452c53ac1ef492ca7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1a64ffdf0efa46aa56d0254381340c6f"><td class="memItemLeft" align="right" valign="top">std::size_t&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_cpu_i_d.php#a1a64ffdf0efa46aa56d0254381340c6f">getRegistersSize</a> () const </td></tr>
<tr class="separator:a1a64ffdf0efa46aa56d0254381340c6f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac1be8d5bd47c4cda2620d4fd1cb38553"><td class="memItemLeft" align="right" valign="top">Register const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_cpu_i_d.php#ac1be8d5bd47c4cda2620d4fd1cb38553">getEax</a> () const </td></tr>
<tr class="separator:ac1be8d5bd47c4cda2620d4fd1cb38553"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2d2fa8cf048b38bc030c0eac79d170e8"><td class="memItemLeft" align="right" valign="top">Register const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_cpu_i_d.php#a2d2fa8cf048b38bc030c0eac79d170e8">getEbx</a> () const </td></tr>
<tr class="separator:a2d2fa8cf048b38bc030c0eac79d170e8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:abbee77878bf7de86d330240e764cd794"><td class="memItemLeft" align="right" valign="top">Register const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_cpu_i_d.php#abbee77878bf7de86d330240e764cd794">getEcx</a> () const </td></tr>
<tr class="separator:abbee77878bf7de86d330240e764cd794"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad33f62f073225b2969b30b4eb4157858"><td class="memItemLeft" align="right" valign="top">Register const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_cpu_i_d.php#ad33f62f073225b2969b30b4eb4157858">getEdx</a> () const </td></tr>
<tr class="separator:ad33f62f073225b2969b30b4eb4157858"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a27333c4dc4c2360f695f24349360995a"><td class="memItemLeft" align="right" valign="top">Register const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_cpu_i_d.php#a27333c4dc4c2360f695f24349360995a">operator[]</a> (unsigned int index) const </td></tr>
<tr class="separator:a27333c4dc4c2360f695f24349360995a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a75be230e4136a130352e51a9d7e5215d"><td class="memItemLeft" align="right" valign="top">Utility::String&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_cpu_i_d.php#a75be230e4136a130352e51a9d7e5215d">toString</a> () const </td></tr>
<tr class="separator:a75be230e4136a130352e51a9d7e5215d"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Allow access to the cpuid intrinsic command for all system. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="ac04fc36f36ff255faec57c2fdfc83967"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::System::CpuID::CpuID </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>No default constructor; </p>

</div>
</div>
<a class="anchor" id="a11d80169526aaf00d13f3528fc07e489"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">NRE::System::CpuID::CpuID </td>
          <td>(</td>
          <td class="paramtype">unsigned int&#160;</td>
          <td class="paramname"><em>i</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct the command </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">i</td><td>the parameter to get from the command </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="ac1be8d5bd47c4cda2620d4fd1cb38553"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">Register const&amp; NRE::System::CpuID::getEax </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the eax register, equivalent to getRegister(0) </dd></dl>

</div>
</div>
<a class="anchor" id="a2d2fa8cf048b38bc030c0eac79d170e8"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">Register const&amp; NRE::System::CpuID::getEbx </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the ebx register, equivalent to getRegister(1) </dd></dl>

</div>
</div>
<a class="anchor" id="abbee77878bf7de86d330240e764cd794"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">Register const&amp; NRE::System::CpuID::getEcx </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the ecx register, equivalent to getRegister(2) </dd></dl>

</div>
</div>
<a class="anchor" id="ad33f62f073225b2969b30b4eb4157858"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">Register const&amp; NRE::System::CpuID::getEdx </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the edx register, equivalent to getRegister(3) </dd></dl>

</div>
</div>
<a class="anchor" id="ab26379e14f22509c390fc3673586948c"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">Register const&amp; NRE::System::CpuID::getRegister </td>
          <td>(</td>
          <td class="paramtype">unsigned int&#160;</td>
          <td class="paramname"><em>index</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Return a specific register </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">index</td><td>the register index </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the corresponding register </dd></dl>

</div>
</div>
<a class="anchor" id="a31efb1583c0414b452c53ac1ef492ca7"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">const Register* NRE::System::CpuID::getRegisters </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>all registers </dd></dl>

</div>
</div>
<a class="anchor" id="a1a64ffdf0efa46aa56d0254381340c6f"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::size_t NRE::System::CpuID::getRegistersSize </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>registers size </dd></dl>

</div>
</div>
<a class="anchor" id="a27333c4dc4c2360f695f24349360995a"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">Register const&amp; NRE::System::CpuID::operator[] </td>
          <td>(</td>
          <td class="paramtype">unsigned int&#160;</td>
          <td class="paramname"><em>index</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Return a const-reference on the index's register, don't check the index range </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">index</td><td>the point's object index </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>a const-reference on the index's register </dd></dl>

</div>
</div>
<a class="anchor" id="a75be230e4136a130352e51a9d7e5215d"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">String NRE::System::CpuID::toString </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Convert the registers into a string </p><dl class="section return"><dt>Returns</dt><dd>the converted registers </dd></dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/CpuID/<a class="el" href="_n_r_e___cpu_i_d_8hpp_source.php">NRE_CpuID.hpp</a></li>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/CpuID/<a class="el" href="_n_r_e___cpu_i_d_8cpp.php">NRE_CpuID.cpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
