<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: NRE::Event::WindowCloseEvent Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Event</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_event_1_1_window_close_event.php">WindowCloseEvent</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_event_1_1_window_close_event-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Event::WindowCloseEvent Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Manage a window close event.  
 <a href="class_n_r_e_1_1_event_1_1_window_close_event.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___window_close_event_8hpp_source.php">NRE_WindowCloseEvent.hpp</a>&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a2759c3c712c3d7e9e6c583fe706a2cd6"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_window_close_event.php#a2759c3c712c3d7e9e6c583fe706a2cd6">WindowCloseEvent</a> ()=delete</td></tr>
<tr class="separator:a2759c3c712c3d7e9e6c583fe706a2cd6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa35b0479ee7cfc000ff9e612269feaf1"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_window_close_event.php#aa35b0479ee7cfc000ff9e612269feaf1">WindowCloseEvent</a> (Graphics::Id id)</td></tr>
<tr class="separator:aa35b0479ee7cfc000ff9e612269feaf1"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8555b825dc5e6ed4325b257db67668cd"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_window_close_event.php#a8555b825dc5e6ed4325b257db67668cd">WindowCloseEvent</a> (<a class="el" href="class_n_r_e_1_1_event_1_1_window_close_event.php">WindowCloseEvent</a> const &amp;e)=default</td></tr>
<tr class="separator:a8555b825dc5e6ed4325b257db67668cd"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0b841fc3d187fc6b01fe90f2865b07e7"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_window_close_event.php#a0b841fc3d187fc6b01fe90f2865b07e7">WindowCloseEvent</a> (<a class="el" href="class_n_r_e_1_1_event_1_1_window_close_event.php">WindowCloseEvent</a> &amp;&amp;e)=default</td></tr>
<tr class="separator:a0b841fc3d187fc6b01fe90f2865b07e7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3ae6eb0fca74ff8c6c2e81f596d14450"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_window_close_event.php#a3ae6eb0fca74ff8c6c2e81f596d14450">~WindowCloseEvent</a> ()=default</td></tr>
<tr class="separator:a3ae6eb0fca74ff8c6c2e81f596d14450"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a15a5d5c151d0bc1f171d38f9dda35dc9"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php">Graphics::Window</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_window_close_event.php#a15a5d5c151d0bc1f171d38f9dda35dc9">getWindow</a> ()</td></tr>
<tr class="separator:a15a5d5c151d0bc1f171d38f9dda35dc9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0c1b0db8bb171b67be3e49055ab66e7d"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_event_1_1_window_close_event.php">WindowCloseEvent</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_window_close_event.php#a0c1b0db8bb171b67be3e49055ab66e7d">operator=</a> (<a class="el" href="class_n_r_e_1_1_event_1_1_window_close_event.php">WindowCloseEvent</a> const &amp;e)=default</td></tr>
<tr class="separator:a0c1b0db8bb171b67be3e49055ab66e7d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae96d8b56e3ff9ec6b11aa49c35064bae"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_event_1_1_window_close_event.php">WindowCloseEvent</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_window_close_event.php#ae96d8b56e3ff9ec6b11aa49c35064bae">operator=</a> (<a class="el" href="class_n_r_e_1_1_event_1_1_window_close_event.php">WindowCloseEvent</a> &amp;&amp;e)=default</td></tr>
<tr class="separator:ae96d8b56e3ff9ec6b11aa49c35064bae"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Manage a window close event. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a2759c3c712c3d7e9e6c583fe706a2cd6"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Event::WindowCloseEvent::WindowCloseEvent </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Default constructor </p>

</div>
</div>
<a class="anchor" id="aa35b0479ee7cfc000ff9e612269feaf1"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Event::WindowCloseEvent::WindowCloseEvent </td>
          <td>(</td>
          <td class="paramtype">Graphics::Id&#160;</td>
          <td class="paramname"><em>id</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct the event from the if of the closing window </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">id</td><td>the closing window </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a8555b825dc5e6ed4325b257db67668cd"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Event::WindowCloseEvent::WindowCloseEvent </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_event_1_1_window_close_event.php">WindowCloseEvent</a> const &amp;&#160;</td>
          <td class="paramname"><em>e</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy e into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">e</td><td>the window close event to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a0b841fc3d187fc6b01fe90f2865b07e7"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Event::WindowCloseEvent::WindowCloseEvent </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_event_1_1_window_close_event.php">WindowCloseEvent</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>e</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move e into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">e</td><td>the window close event to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a3ae6eb0fca74ff8c6c2e81f596d14450"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Event::WindowCloseEvent::~WindowCloseEvent </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_event_1_1_window_close_event.php" title="Manage a window close event. ">WindowCloseEvent</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a15a5d5c151d0bc1f171d38f9dda35dc9"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php">Graphics::Window</a>&amp; NRE::Event::WindowCloseEvent::getWindow </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the closing window </dd></dl>

</div>
</div>
<a class="anchor" id="a0c1b0db8bb171b67be3e49055ab66e7d"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_event_1_1_window_close_event.php">WindowCloseEvent</a>&amp; NRE::Event::WindowCloseEvent::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_event_1_1_window_close_event.php">WindowCloseEvent</a> const &amp;&#160;</td>
          <td class="paramname"><em>e</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy e into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">e</td><td>the object to copy into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="ae96d8b56e3ff9ec6b11aa49c35064bae"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_event_1_1_window_close_event.php">WindowCloseEvent</a>&amp; NRE::Event::WindowCloseEvent::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_event_1_1_window_close_event.php">WindowCloseEvent</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>e</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy e into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">e</td><td>the object to copy into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Event/Event/Window/<a class="el" href="_n_r_e___window_close_event_8hpp_source.php">NRE_WindowCloseEvent.hpp</a></li>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Event/Event/Window/<a class="el" href="_n_r_e___window_close_event_8cpp.php">NRE_WindowCloseEvent.cpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
