<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: NRE::Event::AbstractEventEmitter Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Event</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_event_1_1_abstract_event_emitter.php">AbstractEventEmitter</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-types">Public Types</a> &#124;
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pub-static-attribs">Static Public Attributes</a> &#124;
<a href="class_n_r_e_1_1_event_1_1_abstract_event_emitter-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Event::AbstractEventEmitter Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Abstract class for specialized event emission.  
 <a href="class_n_r_e_1_1_event_1_1_abstract_event_emitter.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___abstract_event_emitter_8hpp_source.php">NRE_AbstractEventEmitter.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for NRE::Event::AbstractEventEmitter:</div>
<div class="dyncontent">
 <div class="center">
  <img src="class_n_r_e_1_1_event_1_1_abstract_event_emitter.png" usemap="#NRE::Event::AbstractEventEmitter_map" alt=""/>
  <map id="NRE::Event::AbstractEventEmitter_map" name="NRE::Event::AbstractEventEmitter_map">
<area href="class_n_r_e_1_1_event_1_1_event_emitter.php" title="Manage event emission to all listener. " alt="NRE::Event::EventEmitter&lt; T &gt;" shape="rect" coords="0,112,198,136"/>
</map>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-types"></a>
Public Types</h2></td></tr>
<tr class="memitem:a6e164be684cf1aabb1fe66d5a64b1f1f"><td class="memItemLeft" align="right" valign="top">typedef std::size_t&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_abstract_event_emitter.php#a6e164be684cf1aabb1fe66d5a64b1f1f">Category</a></td></tr>
<tr class="separator:a6e164be684cf1aabb1fe66d5a64b1f1f"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:adb38e168906f12e942e4d1dfa2eac39a"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_abstract_event_emitter.php#adb38e168906f12e942e4d1dfa2eac39a">AbstractEventEmitter</a> ()=default</td></tr>
<tr class="separator:adb38e168906f12e942e4d1dfa2eac39a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1aae34c87f150cedafec61b87e92d8f2"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_abstract_event_emitter.php#a1aae34c87f150cedafec61b87e92d8f2">AbstractEventEmitter</a> (<a class="el" href="class_n_r_e_1_1_event_1_1_abstract_event_emitter.php">AbstractEventEmitter</a> const &amp;e)=default</td></tr>
<tr class="separator:a1aae34c87f150cedafec61b87e92d8f2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2ea6fc75868a233f9000d5e40aa7208c"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_abstract_event_emitter.php#a2ea6fc75868a233f9000d5e40aa7208c">AbstractEventEmitter</a> (<a class="el" href="class_n_r_e_1_1_event_1_1_abstract_event_emitter.php">AbstractEventEmitter</a> &amp;&amp;e)=default</td></tr>
<tr class="separator:a2ea6fc75868a233f9000d5e40aa7208c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af21e926e910d1a05ac82da783e833c0f"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_abstract_event_emitter.php#af21e926e910d1a05ac82da783e833c0f">~AbstractEventEmitter</a> ()=default</td></tr>
<tr class="separator:af21e926e910d1a05ac82da783e833c0f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afd90cd7556f3d07711b37f15a51640cc"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_abstract_event_emitter.php#afd90cd7556f3d07711b37f15a51640cc">isConsumed</a> () const </td></tr>
<tr class="separator:afd90cd7556f3d07711b37f15a51640cc"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a61c5e87e19799557ba980e4b6ddc6b1b"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_abstract_event_emitter.php#a61c5e87e19799557ba980e4b6ddc6b1b">setConsumed</a> (bool state)</td></tr>
<tr class="separator:a61c5e87e19799557ba980e4b6ddc6b1b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9449334881d89c077e8e73ff16912b54"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_event_1_1_abstract_event_emitter.php">AbstractEventEmitter</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_abstract_event_emitter.php#a9449334881d89c077e8e73ff16912b54">operator=</a> (<a class="el" href="class_n_r_e_1_1_event_1_1_abstract_event_emitter.php">AbstractEventEmitter</a> const &amp;e)=default</td></tr>
<tr class="separator:a9449334881d89c077e8e73ff16912b54"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acc39469ae10f5f1c437e2bb4fd913f84"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_event_1_1_abstract_event_emitter.php">AbstractEventEmitter</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_abstract_event_emitter.php#acc39469ae10f5f1c437e2bb4fd913f84">operator=</a> (<a class="el" href="class_n_r_e_1_1_event_1_1_abstract_event_emitter.php">AbstractEventEmitter</a> &amp;&amp;e)=default</td></tr>
<tr class="separator:acc39469ae10f5f1c437e2bb4fd913f84"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-static-attribs"></a>
Static Public Attributes</h2></td></tr>
<tr class="memitem:afffc04ff4a4626985e294b46e5ae2bfa"><td class="memItemLeft" align="right" valign="top">static <a class="el" href="class_n_r_e_1_1_event_1_1_abstract_event_emitter.php#a6e164be684cf1aabb1fe66d5a64b1f1f">Category</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_abstract_event_emitter.php#afffc04ff4a4626985e294b46e5ae2bfa">counter</a> = 0</td></tr>
<tr class="separator:afffc04ff4a4626985e294b46e5ae2bfa"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Abstract class for specialized event emission. </p>
</div><h2 class="groupheader">Member Typedef Documentation</h2>
<a class="anchor" id="a6e164be684cf1aabb1fe66d5a64b1f1f"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">typedef std::size_t <a class="el" href="class_n_r_e_1_1_event_1_1_abstract_event_emitter.php#a6e164be684cf1aabb1fe66d5a64b1f1f">NRE::Event::AbstractEventEmitter::Category</a></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>&lt; Shortcut to hide the Category type </p>

</div>
</div>
<h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="adb38e168906f12e942e4d1dfa2eac39a"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Event::AbstractEventEmitter::AbstractEventEmitter </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Construct the emitter </p>

</div>
</div>
<a class="anchor" id="a1aae34c87f150cedafec61b87e92d8f2"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Event::AbstractEventEmitter::AbstractEventEmitter </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_event_1_1_abstract_event_emitter.php">AbstractEventEmitter</a> const &amp;&#160;</td>
          <td class="paramname"><em>e</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy e into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">e</td><td>the event emitter to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a2ea6fc75868a233f9000d5e40aa7208c"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Event::AbstractEventEmitter::AbstractEventEmitter </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_event_1_1_abstract_event_emitter.php">AbstractEventEmitter</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>e</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move e into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">e</td><td>the event emitter to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="af21e926e910d1a05ac82da783e833c0f"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual NRE::Event::AbstractEventEmitter::~AbstractEventEmitter </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">virtual</span><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_event_1_1_abstract_event_emitter.php" title="Abstract class for specialized event emission. ">AbstractEventEmitter</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="afd90cd7556f3d07711b37f15a51640cc"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">bool NRE::Event::AbstractEventEmitter::isConsumed </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the consuemed state </dd></dl>

</div>
</div>
<a class="anchor" id="a9449334881d89c077e8e73ff16912b54"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_event_1_1_abstract_event_emitter.php">AbstractEventEmitter</a>&amp; NRE::Event::AbstractEventEmitter::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_event_1_1_abstract_event_emitter.php">AbstractEventEmitter</a> const &amp;&#160;</td>
          <td class="paramname"><em>e</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy e into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">e</td><td>the object to copy into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="acc39469ae10f5f1c437e2bb4fd913f84"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_event_1_1_abstract_event_emitter.php">AbstractEventEmitter</a>&amp; NRE::Event::AbstractEventEmitter::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_event_1_1_abstract_event_emitter.php">AbstractEventEmitter</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>e</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move e into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">e</td><td>the object to move into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a61c5e87e19799557ba980e4b6ddc6b1b"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Event::AbstractEventEmitter::setConsumed </td>
          <td>(</td>
          <td class="paramtype">bool&#160;</td>
          <td class="paramname"><em>state</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Set the consumed state </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">state</td><td>the new consumed state </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<h2 class="groupheader">Member Data Documentation</h2>
<a class="anchor" id="afffc04ff4a4626985e294b46e5ae2bfa"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_event_1_1_abstract_event_emitter.php#a6e164be684cf1aabb1fe66d5a64b1f1f">AbstractEventEmitter::Category</a> NRE::Event::AbstractEventEmitter::counter = 0</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>The category counter </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Event/Emitter/<a class="el" href="_n_r_e___abstract_event_emitter_8hpp_source.php">NRE_AbstractEventEmitter.hpp</a></li>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Event/Emitter/<a class="el" href="_n_r_e___abstract_event_emitter_8cpp.php">NRE_AbstractEventEmitter.cpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
