<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: NRE::Graphics::InternalWindow Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Graphics</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_graphics_1_1_internal_window.php">InternalWindow</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_graphics_1_1_internal_window-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Graphics::InternalWindow Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Manage the internal os-dependant graphics window.  
 <a href="class_n_r_e_1_1_graphics_1_1_internal_window.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___internal_window_8hpp_source.php">NRE_InternalWindow.hpp</a>&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a09412c723df75e0e2880508fefa9ee42"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_internal_window.php#a09412c723df75e0e2880508fefa9ee42">InternalWindow</a> ()=delete</td></tr>
<tr class="separator:a09412c723df75e0e2880508fefa9ee42"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ace87c75ae4cf8e55cf984b583e10cb32"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_internal_window.php#ace87c75ae4cf8e55cf984b583e10cb32">InternalWindow</a> (Id i, Utility::String const &amp;title, Math::Point2D&lt; unsigned int &gt; const &amp;position, Math::Vector2D&lt; unsigned int &gt; const &amp;size, <a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a> const &amp;style)</td></tr>
<tr class="separator:ace87c75ae4cf8e55cf984b583e10cb32"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a681d57178c89d31af8346a9e2f5ad980"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_internal_window.php#a681d57178c89d31af8346a9e2f5ad980">InternalWindow</a> (Id i, Utility::String const &amp;title, Math::Vector2D&lt; unsigned int &gt; const &amp;size, <a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a> const &amp;style)</td></tr>
<tr class="separator:a681d57178c89d31af8346a9e2f5ad980"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a28fbe219923ec0c0a2a94ffcc76a11c9"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_internal_window.php#a28fbe219923ec0c0a2a94ffcc76a11c9">InternalWindow</a> (<a class="el" href="class_n_r_e_1_1_graphics_1_1_internal_window.php">InternalWindow</a> const &amp;inl)=delete</td></tr>
<tr class="separator:a28fbe219923ec0c0a2a94ffcc76a11c9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a23ab8dd6c70214b344fed65eaca7958f"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_internal_window.php#a23ab8dd6c70214b344fed65eaca7958f">InternalWindow</a> (<a class="el" href="class_n_r_e_1_1_graphics_1_1_internal_window.php">InternalWindow</a> &amp;&amp;inl)=delete</td></tr>
<tr class="separator:a23ab8dd6c70214b344fed65eaca7958f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3d3b2f97a886a89af1212aad0388de8e"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_internal_window.php#a3d3b2f97a886a89af1212aad0388de8e">~InternalWindow</a> ()=default</td></tr>
<tr class="separator:a3d3b2f97a886a89af1212aad0388de8e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa67ab3f27e5e59f59af9dc27fcd6143b"><td class="memItemLeft" align="right" valign="top">Math::Point2D&lt; unsigned int &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_internal_window.php#aa67ab3f27e5e59f59af9dc27fcd6143b">getPosition</a> () const </td></tr>
<tr class="separator:aa67ab3f27e5e59f59af9dc27fcd6143b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0fa836b27b2b03d6d21fb0b3f74d4ad6"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_internal_window.php#a0fa836b27b2b03d6d21fb0b3f74d4ad6">close</a> ()</td></tr>
<tr class="separator:a0fa836b27b2b03d6d21fb0b3f74d4ad6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9fc19becfaf28bfac2932bbf46df293b"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_internal_window.php#a9fc19becfaf28bfac2932bbf46df293b">toggleFullscreen</a> (bool inFullscreen)</td></tr>
<tr class="separator:a9fc19becfaf28bfac2932bbf46df293b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:adb9d577cf68a3f203b2269b6db2dd461"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_internal_window.php#adb9d577cf68a3f203b2269b6db2dd461">refresh</a> ()</td></tr>
<tr class="separator:adb9d577cf68a3f203b2269b6db2dd461"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a01f7b7a02ae1fa7c5915ebf31097896a"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_graphics_1_1_internal_window.php">InternalWindow</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_internal_window.php#a01f7b7a02ae1fa7c5915ebf31097896a">operator=</a> (<a class="el" href="class_n_r_e_1_1_graphics_1_1_internal_window.php">InternalWindow</a> const &amp;inl)=delete</td></tr>
<tr class="separator:a01f7b7a02ae1fa7c5915ebf31097896a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af42f895e2b5caaaf83eeda0c92f1cdbb"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_graphics_1_1_internal_window.php">InternalWindow</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_internal_window.php#af42f895e2b5caaaf83eeda0c92f1cdbb">operator=</a> (<a class="el" href="class_n_r_e_1_1_graphics_1_1_internal_window.php">InternalWindow</a> &amp;&amp;inl)=delete</td></tr>
<tr class="separator:af42f895e2b5caaaf83eeda0c92f1cdbb"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Manage the internal os-dependant graphics window. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a09412c723df75e0e2880508fefa9ee42"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Graphics::InternalWindow::InternalWindow </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>No default constructor </p>

</div>
</div>
<a class="anchor" id="ace87c75ae4cf8e55cf984b583e10cb32"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Graphics::InternalWindow::InternalWindow </td>
          <td>(</td>
          <td class="paramtype">Id&#160;</td>
          <td class="paramname"><em>i</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Utility::String const &amp;&#160;</td>
          <td class="paramname"><em>title</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Math::Point2D&lt; unsigned int &gt; const &amp;&#160;</td>
          <td class="paramname"><em>position</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Math::Vector2D&lt; unsigned int &gt; const &amp;&#160;</td>
          <td class="paramname"><em>size</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a> const &amp;&#160;</td>
          <td class="paramname"><em>style</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct the internal window </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">i</td><td>the window id </td></tr>
    <tr><td class="paramname">title</td><td>the window title </td></tr>
    <tr><td class="paramname">position</td><td>the window top-left corner position </td></tr>
    <tr><td class="paramname">size</td><td>the window size </td></tr>
    <tr><td class="paramname">style</td><td>the window style </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a681d57178c89d31af8346a9e2f5ad980"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Graphics::InternalWindow::InternalWindow </td>
          <td>(</td>
          <td class="paramtype">Id&#160;</td>
          <td class="paramname"><em>i</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Utility::String const &amp;&#160;</td>
          <td class="paramname"><em>title</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Math::Vector2D&lt; unsigned int &gt; const &amp;&#160;</td>
          <td class="paramname"><em>size</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a> const &amp;&#160;</td>
          <td class="paramname"><em>style</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct the internal window with centered position </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">i</td><td>the window id </td></tr>
    <tr><td class="paramname">title</td><td>the window title </td></tr>
    <tr><td class="paramname">size</td><td>the window size </td></tr>
    <tr><td class="paramname">style</td><td>the window style </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a28fbe219923ec0c0a2a94ffcc76a11c9"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Graphics::InternalWindow::InternalWindow </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_internal_window.php">InternalWindow</a> const &amp;&#160;</td>
          <td class="paramname"><em>inl</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">inl</td><td>the internal window to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a23ab8dd6c70214b344fed65eaca7958f"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Graphics::InternalWindow::InternalWindow </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_internal_window.php">InternalWindow</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>inl</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">inl</td><td>the internal window to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a3d3b2f97a886a89af1212aad0388de8e"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Graphics::InternalWindow::~InternalWindow </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_graphics_1_1_internal_window.php" title="Manage the internal os-dependant graphics window. ">InternalWindow</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a0fa836b27b2b03d6d21fb0b3f74d4ad6"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Graphics::InternalWindow::close </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Close the internal window </p>

</div>
</div>
<a class="anchor" id="aa67ab3f27e5e59f59af9dc27fcd6143b"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">Math::Point2D&lt;unsigned int&gt; NRE::Graphics::InternalWindow::getPosition </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the window top-left corner position </dd></dl>

</div>
</div>
<a class="anchor" id="a01f7b7a02ae1fa7c5915ebf31097896a"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_graphics_1_1_internal_window.php">InternalWindow</a>&amp; NRE::Graphics::InternalWindow::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_internal_window.php">InternalWindow</a> const &amp;&#160;</td>
          <td class="paramname"><em>inl</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">inl</td><td>the object to copy into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="af42f895e2b5caaaf83eeda0c92f1cdbb"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_graphics_1_1_internal_window.php">InternalWindow</a>&amp; NRE::Graphics::InternalWindow::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_internal_window.php">InternalWindow</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>inl</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">inl</td><td>the object to move into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="adb9d577cf68a3f203b2269b6db2dd461"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Graphics::InternalWindow::refresh </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Refresh the window </p>

</div>
</div>
<a class="anchor" id="a9fc19becfaf28bfac2932bbf46df293b"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Graphics::InternalWindow::toggleFullscreen </td>
          <td>(</td>
          <td class="paramtype">bool&#160;</td>
          <td class="paramname"><em>inFullscreen</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Toggle between fullscreen and windowed mode </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Graphics/Window/Internal/<a class="el" href="_n_r_e___internal_window_8hpp_source.php">NRE_InternalWindow.hpp</a></li>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/OS/Linux/Graphics/Window/Internal/<a class="el" href="_n_r_e___linux_internal_window_8cpp.php">NRE_LinuxInternalWindow.cpp</a></li>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/OS/Windows/Graphics/Window/Internal/<a class="el" href="_n_r_e___windows_internal_window_8cpp.php">NRE_WindowsInternalWindow.cpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
