<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: NRE::Graphics::Context Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Graphics</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context.php">Context</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_graphics_1_1_context-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Graphics::Context Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Describe an OpenGL <a class="el" href="class_n_r_e_1_1_graphics_1_1_context.php" title="Describe an OpenGL Context with a set of attributes. ">Context</a> with a set of attributes.  
 <a href="class_n_r_e_1_1_graphics_1_1_context.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___context_8hpp_source.php">NRE_Context.hpp</a>&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a36d866316c088e60ed9771e24ba6df84"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context.php#a36d866316c088e60ed9771e24ba6df84">Context</a> (<a class="el" href="class_n_r_e_1_1_graphics_1_1_internal_window.php">InternalWindow</a> &amp;window, <a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">ContextAttributes</a> const &amp;attr)</td></tr>
<tr class="separator:a36d866316c088e60ed9771e24ba6df84"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a722fd8cbc9de2a713943a10150bae6b3"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context.php#a722fd8cbc9de2a713943a10150bae6b3">Context</a> (<a class="el" href="class_n_r_e_1_1_graphics_1_1_context.php">Context</a> const &amp;ctx)=delete</td></tr>
<tr class="separator:a722fd8cbc9de2a713943a10150bae6b3"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a456ad4b026ea36e78091e4a8dc4362f6"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context.php#a456ad4b026ea36e78091e4a8dc4362f6">Context</a> (<a class="el" href="class_n_r_e_1_1_graphics_1_1_context.php">Context</a> &amp;&amp;ctx)=delete</td></tr>
<tr class="separator:a456ad4b026ea36e78091e4a8dc4362f6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a59e9025d012689438fda98ecb309910f"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context.php#a59e9025d012689438fda98ecb309910f">~Context</a> ()</td></tr>
<tr class="separator:a59e9025d012689438fda98ecb309910f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a19a97623f714c0a58cfb97fd9f775bc9"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context.php#a19a97623f714c0a58cfb97fd9f775bc9">release</a> ()</td></tr>
<tr class="separator:a19a97623f714c0a58cfb97fd9f775bc9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae69f36da5074b4b37661a282d187e101"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context.php">Context</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context.php#ae69f36da5074b4b37661a282d187e101">operator=</a> (<a class="el" href="class_n_r_e_1_1_graphics_1_1_context.php">Context</a> const &amp;ctx)=delete</td></tr>
<tr class="separator:ae69f36da5074b4b37661a282d187e101"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae72e5a0f98d59d9ee173ac7744c88471"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context.php">Context</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context.php#ae72e5a0f98d59d9ee173ac7744c88471">operator=</a> (<a class="el" href="class_n_r_e_1_1_graphics_1_1_context.php">Context</a> &amp;&amp;ctx)=delete</td></tr>
<tr class="separator:ae72e5a0f98d59d9ee173ac7744c88471"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Describe an OpenGL <a class="el" href="class_n_r_e_1_1_graphics_1_1_context.php" title="Describe an OpenGL Context with a set of attributes. ">Context</a> with a set of attributes. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a36d866316c088e60ed9771e24ba6df84"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Graphics::Context::Context </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_internal_window.php">InternalWindow</a> &amp;&#160;</td>
          <td class="paramname"><em>window</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">ContextAttributes</a> const &amp;&#160;</td>
          <td class="paramname"><em>attr</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct the context using the target window and desired attributes </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">window</td><td>the window to create the context </td></tr>
    <tr><td class="paramname">attr</td><td>the context attributes </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a722fd8cbc9de2a713943a10150bae6b3"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Graphics::Context::Context </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context.php">Context</a> const &amp;&#160;</td>
          <td class="paramname"><em>ctx</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">ctx</td><td>the context to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a456ad4b026ea36e78091e4a8dc4362f6"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Graphics::Context::Context </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context.php">Context</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>ctx</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">ctx</td><td>the context to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a59e9025d012689438fda98ecb309910f"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Graphics::Context::~Context </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_graphics_1_1_context.php" title="Describe an OpenGL Context with a set of attributes. ">Context</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="ae69f36da5074b4b37661a282d187e101"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context.php">Context</a>&amp; NRE::Graphics::Context::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context.php">Context</a> const &amp;&#160;</td>
          <td class="paramname"><em>ctx</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">ctx</td><td>the object to copy into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="ae72e5a0f98d59d9ee173ac7744c88471"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context.php">Context</a>&amp; NRE::Graphics::Context::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context.php">Context</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>ctx</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">ctx</td><td>the object to move into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a19a97623f714c0a58cfb97fd9f775bc9"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Graphics::Context::release </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Release the context </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Graphics/Driver/Context/<a class="el" href="_n_r_e___context_8hpp_source.php">NRE_Context.hpp</a></li>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/OS/Linux/Graphics/Driver/Context/<a class="el" href="_n_r_e___linux_context_8cpp.php">NRE_LinuxContext.cpp</a></li>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/OS/Windows/Graphics/Driver/Context/<a class="el" href="_n_r_e___windows_context_8cpp.php">NRE_WindowsContext.cpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
