<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: NRE::Graphics::WindowStyle Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Graphics</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pub-static-attribs">Static Public Attributes</a> &#124;
<a href="class_n_r_e_1_1_graphics_1_1_window_style-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Graphics::WindowStyle Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Manage a window style.  
 <a href="class_n_r_e_1_1_graphics_1_1_window_style.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___window_style_8hpp_source.php">NRE_WindowStyle.hpp</a>&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:abd3b517579efdd1b7fb3b0fa9c7221c4"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php#abd3b517579efdd1b7fb3b0fa9c7221c4">WindowStyle</a> (unsigned int s=<a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php#a5926ee9e0b531a0ff3118a576d78b374">BASIC</a>)</td></tr>
<tr class="separator:abd3b517579efdd1b7fb3b0fa9c7221c4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a33cfa2a025595ef080ed2687ab2eb913"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php#a33cfa2a025595ef080ed2687ab2eb913">WindowStyle</a> (<a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a> const &amp;ws)=default</td></tr>
<tr class="separator:a33cfa2a025595ef080ed2687ab2eb913"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a66f37dce24f8655daa77ede3ac289633"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php#a66f37dce24f8655daa77ede3ac289633">WindowStyle</a> (<a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a> &amp;&amp;ws)=default</td></tr>
<tr class="separator:a66f37dce24f8655daa77ede3ac289633"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a18360d5c69c3ae20624ac0fb2a312b65"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php#a18360d5c69c3ae20624ac0fb2a312b65">~WindowStyle</a> ()=default</td></tr>
<tr class="separator:a18360d5c69c3ae20624ac0fb2a312b65"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2ef6bba5ff5e4f062713c12a12a14a1f"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php#a2ef6bba5ff5e4f062713c12a12a14a1f">operator=</a> (<a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a> const &amp;ws)=default</td></tr>
<tr class="separator:a2ef6bba5ff5e4f062713c12a12a14a1f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4ddbc792d3bf210cbbb7c4c183492ee0"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php#a4ddbc792d3bf210cbbb7c4c183492ee0">operator=</a> (<a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a> &amp;&amp;ws)=default</td></tr>
<tr class="separator:a4ddbc792d3bf210cbbb7c4c183492ee0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a70a5510030cb277349ba4e4ec1a52ac3"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php#a70a5510030cb277349ba4e4ec1a52ac3">operator|=</a> (<a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a> const &amp;ws)</td></tr>
<tr class="separator:a70a5510030cb277349ba4e4ec1a52ac3"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a700de39ee28aaf2cacb0acced6988925"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php#a700de39ee28aaf2cacb0acced6988925">operator|</a> (<a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a> const &amp;ws) const </td></tr>
<tr class="separator:a700de39ee28aaf2cacb0acced6988925"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9138844bf5232283fec196a69a678390"><td class="memItemLeft" align="right" valign="top">unsigned int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php#a9138844bf5232283fec196a69a678390">operator&amp;</a> (unsigned int ws) const </td></tr>
<tr class="separator:a9138844bf5232283fec196a69a678390"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-static-attribs"></a>
Static Public Attributes</h2></td></tr>
<tr class="memitem:a5926ee9e0b531a0ff3118a576d78b374"><td class="memItemLeft" align="right" valign="top">static constexpr unsigned int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php#a5926ee9e0b531a0ff3118a576d78b374">BASIC</a> = 0b000</td></tr>
<tr class="separator:a5926ee9e0b531a0ff3118a576d78b374"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa256a85a03ac8c3c2a88b90e1db72c77"><td class="memItemLeft" align="right" valign="top">static constexpr unsigned int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php#aa256a85a03ac8c3c2a88b90e1db72c77">CLOSEABLE</a> = 0b001</td></tr>
<tr class="separator:aa256a85a03ac8c3c2a88b90e1db72c77"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a04ecda3096b6634ac17dad385ce3b876"><td class="memItemLeft" align="right" valign="top">static constexpr unsigned int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php#a04ecda3096b6634ac17dad385ce3b876">RESIZEABLE</a> = 0b010</td></tr>
<tr class="separator:a04ecda3096b6634ac17dad385ce3b876"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a77500dc9eeaa013d8173993859713b7a"><td class="memItemLeft" align="right" valign="top">static constexpr unsigned int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php#a77500dc9eeaa013d8173993859713b7a">FULLSCREEN</a> = 0b100</td></tr>
<tr class="separator:a77500dc9eeaa013d8173993859713b7a"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Manage a window style. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="abd3b517579efdd1b7fb3b0fa9c7221c4"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Graphics::WindowStyle::WindowStyle </td>
          <td>(</td>
          <td class="paramtype">unsigned int&#160;</td>
          <td class="paramname"><em>s</em> = <code><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php#a5926ee9e0b531a0ff3118a576d78b374">BASIC</a></code></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Construct the window style </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">s</td><td>the style value </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a33cfa2a025595ef080ed2687ab2eb913"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Graphics::WindowStyle::WindowStyle </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a> const &amp;&#160;</td>
          <td class="paramname"><em>ws</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy the window style into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">ws</td><td>the window style to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a66f37dce24f8655daa77ede3ac289633"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Graphics::WindowStyle::WindowStyle </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>ws</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move the window style into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">ws</td><td>the window style to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a18360d5c69c3ae20624ac0fb2a312b65"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Graphics::WindowStyle::~WindowStyle </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php" title="Manage a window style. ">WindowStyle</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a9138844bf5232283fec196a69a678390"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">unsigned int NRE::Graphics::WindowStyle::operator&amp; </td>
          <td>(</td>
          <td class="paramtype">unsigned int&#160;</td>
          <td class="paramname"><em>ws</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Compute the style value resulting in the bitwize AND with this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">ws</td><td>the other style </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the computed style value </dd></dl>

</div>
</div>
<a class="anchor" id="a2ef6bba5ff5e4f062713c12a12a14a1f"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a>&amp; NRE::Graphics::WindowStyle::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a> const &amp;&#160;</td>
          <td class="paramname"><em>ws</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy the window style into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">ws</td><td>the object to copy into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a4ddbc792d3bf210cbbb7c4c183492ee0"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a>&amp; NRE::Graphics::WindowStyle::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>ws</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move the window style into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">ws</td><td>the object to move into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a700de39ee28aaf2cacb0acced6988925"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a> NRE::Graphics::WindowStyle::operator| </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a> const &amp;&#160;</td>
          <td class="paramname"><em>ws</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Compute the style resulting in the bitwize OR with this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">ws</td><td>the other style </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the computed style </dd></dl>

</div>
</div>
<a class="anchor" id="a70a5510030cb277349ba4e4ec1a52ac3"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a> &amp; NRE::Graphics::WindowStyle::operator|= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a> const &amp;&#160;</td>
          <td class="paramname"><em>ws</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Perform a bitwise OR with this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">ws</td><td>the other style </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<h2 class="groupheader">Member Data Documentation</h2>
<a class="anchor" id="a5926ee9e0b531a0ff3118a576d78b374"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">constexpr unsigned int NRE::Graphics::WindowStyle::BASIC = 0b000</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>A basic window with no close button and which can't be resized </p>

</div>
</div>
<a class="anchor" id="aa256a85a03ac8c3c2a88b90e1db72c77"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">constexpr unsigned int NRE::Graphics::WindowStyle::CLOSEABLE = 0b001</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Add a close button to the window </p>

</div>
</div>
<a class="anchor" id="a77500dc9eeaa013d8173993859713b7a"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">constexpr unsigned int NRE::Graphics::WindowStyle::FULLSCREEN = 0b100</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>The window start in fullscreen mode </p>

</div>
</div>
<a class="anchor" id="a04ecda3096b6634ac17dad385ce3b876"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">constexpr unsigned int NRE::Graphics::WindowStyle::RESIZEABLE = 0b010</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>The window can be resized </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Graphics/Window/Style/<a class="el" href="_n_r_e___window_style_8hpp_source.php">NRE_WindowStyle.hpp</a></li>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Graphics/Window/Style/<a class="el" href="_n_r_e___window_style_8cpp.php">NRE_WindowStyle.cpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
