<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: NRE::Graphics::WindowAttributes Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Graphics</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_attributes.php">WindowAttributes</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_graphics_1_1_window_attributes-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Graphics::WindowAttributes Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Manage a window attributes.  
 <a href="class_n_r_e_1_1_graphics_1_1_window_attributes.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___window_attributes_8hpp_source.php">NRE_WindowAttributes.hpp</a>&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a548bc75cf3c588d1d96586c85ce24cd7"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_attributes.php#a548bc75cf3c588d1d96586c85ce24cd7">WindowAttributes</a> ()=delete</td></tr>
<tr class="separator:a548bc75cf3c588d1d96586c85ce24cd7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a55cc8f3d2402e564e90987103d5dad38"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_attributes.php#a55cc8f3d2402e564e90987103d5dad38">WindowAttributes</a> (Utility::String const &amp;t, Math::Point2D&lt; unsigned int &gt; const &amp;pos, Math::Vector2D&lt; unsigned int &gt; const &amp;s)</td></tr>
<tr class="separator:a55cc8f3d2402e564e90987103d5dad38"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae00bafe751a8dab2d5d1ed4dd28406ac"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_attributes.php#ae00bafe751a8dab2d5d1ed4dd28406ac">WindowAttributes</a> (Utility::String const &amp;t, Math::Vector2D&lt; unsigned int &gt; const &amp;s)</td></tr>
<tr class="separator:ae00bafe751a8dab2d5d1ed4dd28406ac"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac82cd35d5966f8c47886a15b30ed0ab7"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_attributes.php#ac82cd35d5966f8c47886a15b30ed0ab7">WindowAttributes</a> (<a class="el" href="class_n_r_e_1_1_graphics_1_1_window_attributes.php">WindowAttributes</a> const &amp;attr)=default</td></tr>
<tr class="separator:ac82cd35d5966f8c47886a15b30ed0ab7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aaaf7d105bc358ffb10ff1e5da9a693cb"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_attributes.php#aaaf7d105bc358ffb10ff1e5da9a693cb">WindowAttributes</a> (<a class="el" href="class_n_r_e_1_1_graphics_1_1_window_attributes.php">WindowAttributes</a> &amp;&amp;attr)=default</td></tr>
<tr class="separator:aaaf7d105bc358ffb10ff1e5da9a693cb"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3d6c60d2661cea4603628dfb28f0d090"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_attributes.php#a3d6c60d2661cea4603628dfb28f0d090">~WindowAttributes</a> ()=default</td></tr>
<tr class="separator:a3d6c60d2661cea4603628dfb28f0d090"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:accdfba6b43172d59cd2d7bd3f69dea7a"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_attributes.php#accdfba6b43172d59cd2d7bd3f69dea7a">setPosition</a> (Math::Point2D&lt; unsigned int &gt; const &amp;pos)</td></tr>
<tr class="separator:accdfba6b43172d59cd2d7bd3f69dea7a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5a0f6a0c53e01d858809314d2e761838"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_attributes.php">WindowAttributes</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_attributes.php#a5a0f6a0c53e01d858809314d2e761838">operator=</a> (<a class="el" href="class_n_r_e_1_1_graphics_1_1_window_attributes.php">WindowAttributes</a> const &amp;attr)=default</td></tr>
<tr class="separator:a5a0f6a0c53e01d858809314d2e761838"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a83e81827d9deadba18e381f38f391ae5"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_attributes.php">WindowAttributes</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_attributes.php#a83e81827d9deadba18e381f38f391ae5">operator=</a> (<a class="el" href="class_n_r_e_1_1_graphics_1_1_window_attributes.php">WindowAttributes</a> &amp;&amp;attr)=default</td></tr>
<tr class="separator:a83e81827d9deadba18e381f38f391ae5"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6ae94a6a4084f7b8fce079dce8d50b48"><td class="memItemLeft" align="right" valign="top">Utility::String&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_attributes.php#a6ae94a6a4084f7b8fce079dce8d50b48">toString</a> () const </td></tr>
<tr class="separator:a6ae94a6a4084f7b8fce079dce8d50b48"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Manage a window attributes. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a548bc75cf3c588d1d96586c85ce24cd7"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Graphics::WindowAttributes::WindowAttributes </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>No default constructor </p>

</div>
</div>
<a class="anchor" id="a55cc8f3d2402e564e90987103d5dad38"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Graphics::WindowAttributes::WindowAttributes </td>
          <td>(</td>
          <td class="paramtype">Utility::String const &amp;&#160;</td>
          <td class="paramname"><em>t</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Math::Point2D&lt; unsigned int &gt; const &amp;&#160;</td>
          <td class="paramname"><em>pos</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Math::Vector2D&lt; unsigned int &gt; const &amp;&#160;</td>
          <td class="paramname"><em>s</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct the window attributes </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">t</td><td>the window title </td></tr>
    <tr><td class="paramname">pos</td><td>the window top-left corner position </td></tr>
    <tr><td class="paramname">s</td><td>the window size </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="ae00bafe751a8dab2d5d1ed4dd28406ac"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Graphics::WindowAttributes::WindowAttributes </td>
          <td>(</td>
          <td class="paramtype">Utility::String const &amp;&#160;</td>
          <td class="paramname"><em>t</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Math::Vector2D&lt; unsigned int &gt; const &amp;&#160;</td>
          <td class="paramname"><em>s</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct the window attributes </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">t</td><td>the window title </td></tr>
    <tr><td class="paramname">s</td><td>the window size </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="ac82cd35d5966f8c47886a15b30ed0ab7"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Graphics::WindowAttributes::WindowAttributes </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_attributes.php">WindowAttributes</a> const &amp;&#160;</td>
          <td class="paramname"><em>attr</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy the window attributes into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">attr</td><td>the window attributes to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="aaaf7d105bc358ffb10ff1e5da9a693cb"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Graphics::WindowAttributes::WindowAttributes </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_attributes.php">WindowAttributes</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>attr</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move the window attributes into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">attr</td><td>the window attributes to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a3d6c60d2661cea4603628dfb28f0d090"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Graphics::WindowAttributes::~WindowAttributes </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_attributes.php" title="Manage a window attributes. ">WindowAttributes</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a5a0f6a0c53e01d858809314d2e761838"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_attributes.php">WindowAttributes</a>&amp; NRE::Graphics::WindowAttributes::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_attributes.php">WindowAttributes</a> const &amp;&#160;</td>
          <td class="paramname"><em>attr</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy the window attributes into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">attr</td><td>the object to copy into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a83e81827d9deadba18e381f38f391ae5"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_attributes.php">WindowAttributes</a>&amp; NRE::Graphics::WindowAttributes::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_attributes.php">WindowAttributes</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>attr</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move the window attributes into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">attr</td><td>the object to move into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="accdfba6b43172d59cd2d7bd3f69dea7a"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Graphics::WindowAttributes::setPosition </td>
          <td>(</td>
          <td class="paramtype">Math::Point2D&lt; unsigned int &gt; const &amp;&#160;</td>
          <td class="paramname"><em>pos</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Set the window position attribute </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">pos</td><td>the new window position </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a6ae94a6a4084f7b8fce079dce8d50b48"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">Utility::String NRE::Graphics::WindowAttributes::toString </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Convert the window attributes into a string </p><dl class="section return"><dt>Returns</dt><dd>the converted window attributes </dd></dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Graphics/Window/Attributes/<a class="el" href="_n_r_e___window_attributes_8hpp_source.php">NRE_WindowAttributes.hpp</a></li>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Graphics/Window/Attributes/<a class="el" href="_n_r_e___window_attributes_8cpp.php">NRE_WindowAttributes.cpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
