<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: NRE::Event::KeyTranslater Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Event</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_event_1_1_key_translater.php">KeyTranslater</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#nested-classes">Classes</a> &#124;
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_event_1_1_key_translater-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Event::KeyTranslater Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Manage the translation of native key.  
 <a href="class_n_r_e_1_1_event_1_1_key_translater.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___linux_key_translater_8hpp_source.php">NRE_LinuxKeyTranslater.hpp</a>&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a587811f551124bd0e41d7dc53b3af602"><td class="memItemLeft" align="right" valign="top"><a class="el" href="_n_r_e___keys_8hpp.php#aad0b5de9f5c32805861bae5dda36d501">KeyCode</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_key_translater.php#a587811f551124bd0e41d7dc53b3af602">translateKey</a> (XKeyEvent const &amp;keyEvent) const </td></tr>
<tr class="separator:a587811f551124bd0e41d7dc53b3af602"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad8f2bcca6a0d9e25e87c95fd1d267ad1"><td class="memItemLeft" align="right" valign="top"><a class="el" href="_n_r_e___keys_8hpp.php#aad0b5de9f5c32805861bae5dda36d501">KeyCode</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_key_translater.php#ad8f2bcca6a0d9e25e87c95fd1d267ad1">translateKey</a> (WPARAM wParam, LPARAM lParam) const </td></tr>
<tr class="separator:ad8f2bcca6a0d9e25e87c95fd1d267ad1"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Manage the translation of native key. </p>
</div><h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a587811f551124bd0e41d7dc53b3af602"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="_n_r_e___keys_8hpp.php#aad0b5de9f5c32805861bae5dda36d501">KeyCode</a> NRE::Event::KeyTranslater::translateKey </td>
          <td>(</td>
          <td class="paramtype">XKeyEvent const &amp;&#160;</td>
          <td class="paramname"><em>keyEvent</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Translate a native key code into an <a class="el" href="namespace_n_r_e.php" title="The NearlyRealEngine&#39;s global namespace. ">NRE</a> key </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">keyEvent</td><td>the native key press event </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the translated key </dd></dl>

</div>
</div>
<a class="anchor" id="ad8f2bcca6a0d9e25e87c95fd1d267ad1"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="_n_r_e___keys_8hpp.php#aad0b5de9f5c32805861bae5dda36d501">KeyCode</a> NRE::Event::KeyTranslater::translateKey </td>
          <td>(</td>
          <td class="paramtype">WPARAM&#160;</td>
          <td class="paramname"><em>wParam</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">LPARAM&#160;</td>
          <td class="paramname"><em>lParam</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Translate a native key code into an <a class="el" href="namespace_n_r_e.php" title="The NearlyRealEngine&#39;s global namespace. ">NRE</a> key </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">wParam</td><td>additionnal message-specific information </td></tr>
    <tr><td class="paramname">lParam</td><td>additionnal message-specific information </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the translated key </dd></dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/OS/Linux/Event/Input/Keys/<a class="el" href="_n_r_e___linux_key_translater_8hpp_source.php">NRE_LinuxKeyTranslater.hpp</a></li>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/OS/Windows/Event/Input/Keys/<a class="el" href="_n_r_e___windows_key_translater_8hpp_source.php">NRE_WindowsKeyTranslater.hpp</a></li>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/OS/Linux/Event/Input/Keys/<a class="el" href="_n_r_e___linux_key_translater_8cpp.php">NRE_LinuxKeyTranslater.cpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
