<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: NRE::Event::InputManager Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Event</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_event_1_1_input_manager.php">InputManager</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_event_1_1_input_manager-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Event::InputManager Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Manage the process of native input.  
 <a href="class_n_r_e_1_1_event_1_1_input_manager.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___input_manager_8hpp_source.php">NRE_InputManager.hpp</a>&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:aa8d6f2d0d14b9b1fde715c9a0e496656"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_input_manager.php#aa8d6f2d0d14b9b1fde715c9a0e496656">isKeyPressed</a> (<a class="el" href="_n_r_e___keys_8hpp.php#aad0b5de9f5c32805861bae5dda36d501">KeyCode</a> code) const </td></tr>
<tr class="separator:aa8d6f2d0d14b9b1fde715c9a0e496656"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af27a0330fff81319a4a19fe1b5dfb627"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_input_manager.php#af27a0330fff81319a4a19fe1b5dfb627">isButtonPressed</a> (<a class="el" href="_n_r_e___buttons_8hpp.php#a3117cef30b4eed21ee57db72bd9d3ef8">ButtonCode</a> code) const </td></tr>
<tr class="separator:af27a0330fff81319a4a19fe1b5dfb627"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8c79605377604bc1921c94b815ce1156"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_input_manager.php#a8c79605377604bc1921c94b815ce1156">processPressedKey</a> (<a class="el" href="_n_r_e___keys_8hpp.php#aad0b5de9f5c32805861bae5dda36d501">KeyCode</a> key)</td></tr>
<tr class="separator:a8c79605377604bc1921c94b815ce1156"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a49c78dd73cf5b5eae6daec89030e09dc"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_input_manager.php#a49c78dd73cf5b5eae6daec89030e09dc">processPressedButton</a> (<a class="el" href="class_n_r_e_1_1_event_1_1_button_event.php">ButtonEventData</a> const &amp;buttonData)</td></tr>
<tr class="separator:a49c78dd73cf5b5eae6daec89030e09dc"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a50c021dddab878c05e26511485438a2b"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_input_manager.php#a50c021dddab878c05e26511485438a2b">processReleasedKey</a> (<a class="el" href="_n_r_e___keys_8hpp.php#aad0b5de9f5c32805861bae5dda36d501">KeyCode</a> key)</td></tr>
<tr class="separator:a50c021dddab878c05e26511485438a2b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a49c2c4284cf3eda4c74e2026dde5be74"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_input_manager.php#a49c2c4284cf3eda4c74e2026dde5be74">processReleasedButton</a> (<a class="el" href="class_n_r_e_1_1_event_1_1_button_event.php">ButtonEventData</a> const &amp;buttonData)</td></tr>
<tr class="separator:a49c2c4284cf3eda4c74e2026dde5be74"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad30e5d64bd4823311de1612c4b7520f1"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_input_manager.php#ad30e5d64bd4823311de1612c4b7520f1">update</a> ()</td></tr>
<tr class="separator:ad30e5d64bd4823311de1612c4b7520f1"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7799ede2c90932658c79a0674a3fa0a0"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_event_1_1_input_manager.php#a7799ede2c90932658c79a0674a3fa0a0">updateButtonEventData</a> (<a class="el" href="class_n_r_e_1_1_event_1_1_button_event.php">ButtonEventData</a> const &amp;buttonData)</td></tr>
<tr class="separator:a7799ede2c90932658c79a0674a3fa0a0"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Manage the process of native input. </p>
</div><h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="af27a0330fff81319a4a19fe1b5dfb627"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">bool NRE::Event::InputManager::isButtonPressed </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="_n_r_e___buttons_8hpp.php#a3117cef30b4eed21ee57db72bd9d3ef8">ButtonCode</a>&#160;</td>
          <td class="paramname"><em>code</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Tell if a button is currently pressed </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">code</td><td>the button code </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>if the button is pressed </dd></dl>

</div>
</div>
<a class="anchor" id="aa8d6f2d0d14b9b1fde715c9a0e496656"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">bool NRE::Event::InputManager::isKeyPressed </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="_n_r_e___keys_8hpp.php#aad0b5de9f5c32805861bae5dda36d501">KeyCode</a>&#160;</td>
          <td class="paramname"><em>code</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Tell if a key is currently pressed </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">code</td><td>the key code </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>if the key is pressed </dd></dl>

</div>
</div>
<a class="anchor" id="a49c78dd73cf5b5eae6daec89030e09dc"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Event::InputManager::processPressedButton </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_event_1_1_button_event.php">ButtonEventData</a> const &amp;&#160;</td>
          <td class="paramname"><em>buttonData</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Process a pressed button event </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">buttonData</td><td>the pressed button data </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a8c79605377604bc1921c94b815ce1156"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Event::InputManager::processPressedKey </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="_n_r_e___keys_8hpp.php#aad0b5de9f5c32805861bae5dda36d501">KeyCode</a>&#160;</td>
          <td class="paramname"><em>key</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Process a pressed key event </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">key</td><td>the pressed key </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a49c2c4284cf3eda4c74e2026dde5be74"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Event::InputManager::processReleasedButton </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_event_1_1_button_event.php">ButtonEventData</a> const &amp;&#160;</td>
          <td class="paramname"><em>buttonData</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Process a released button event </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">buttonData</td><td>the pressed button data </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a50c021dddab878c05e26511485438a2b"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Event::InputManager::processReleasedKey </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="_n_r_e___keys_8hpp.php#aad0b5de9f5c32805861bae5dda36d501">KeyCode</a>&#160;</td>
          <td class="paramname"><em>key</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Process a released key event </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">key</td><td>the released key </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="ad30e5d64bd4823311de1612c4b7520f1"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Event::InputManager::update </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Process active keys and buttons </p>

</div>
</div>
<a class="anchor" id="a7799ede2c90932658c79a0674a3fa0a0"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Event::InputManager::updateButtonEventData </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_event_1_1_button_event.php">ButtonEventData</a> const &amp;&#160;</td>
          <td class="paramname"><em>buttonData</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Update a button event data </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">buttonData</td><td>the new data </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Event/Input/<a class="el" href="_n_r_e___input_manager_8hpp_source.php">NRE_InputManager.hpp</a></li>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Event/Input/<a class="el" href="_n_r_e___input_manager_8cpp.php">NRE_InputManager.cpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
