<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: NRE::System::SystemInfo Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>System</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_system_1_1_system_info.php">SystemInfo</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_system_1_1_system_info-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::System::SystemInfo Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Represent all informations from the user system.  
 <a href="class_n_r_e_1_1_system_1_1_system_info.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___system_info_8hpp_source.php">NRE_SystemInfo.hpp</a>&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:acf7fa1fdd456441e427ec4057385f097"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_system_info.php#acf7fa1fdd456441e427ec4057385f097">SystemInfo</a> ()</td></tr>
<tr class="separator:acf7fa1fdd456441e427ec4057385f097"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:accf4044376d402e48eb79e6ebba6b329"><td class="memItemLeft" align="right" valign="top">Utility::String const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_system_info.php#accf4044376d402e48eb79e6ebba6b329">getCPUName</a> () const </td></tr>
<tr class="separator:accf4044376d402e48eb79e6ebba6b329"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a646d882c712b19344bb9cfef2cef018a"><td class="memItemLeft" align="right" valign="top">Utility::String const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_system_info.php#a646d882c712b19344bb9cfef2cef018a">getArchitecture</a> () const </td></tr>
<tr class="separator:a646d882c712b19344bb9cfef2cef018a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a60eee75af32e24cb32ce33521b654587"><td class="memItemLeft" align="right" valign="top">std::size_t&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_system_info.php#a60eee75af32e24cb32ce33521b654587">getNbProcessors</a> () const </td></tr>
<tr class="separator:a60eee75af32e24cb32ce33521b654587"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a04b218dae88cfd421e53fee946d6a637"><td class="memItemLeft" align="right" valign="top">std::size_t&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_system_info.php#a04b218dae88cfd421e53fee946d6a637">getMemorySize</a> () const </td></tr>
<tr class="separator:a04b218dae88cfd421e53fee946d6a637"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a293ad706965abc2a3b6c28c56998071c"><td class="memItemLeft" align="right" valign="top">std::size_t&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_system_info.php#a293ad706965abc2a3b6c28c56998071c">getMemoryUsed</a> () const </td></tr>
<tr class="separator:a293ad706965abc2a3b6c28c56998071c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a32964d022a3401740d477e5ea9a33551"><td class="memItemLeft" align="right" valign="top">std::size_t&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_system_info.php#a32964d022a3401740d477e5ea9a33551">getMemoryUsedByProcess</a> () const </td></tr>
<tr class="separator:a32964d022a3401740d477e5ea9a33551"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ada33a1d288fa42bb0fdac2bef90acebc"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_system_info.php#ada33a1d288fa42bb0fdac2bef90acebc">setCPUName</a> (Utility::String const &amp;name)</td></tr>
<tr class="separator:ada33a1d288fa42bb0fdac2bef90acebc"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a13b3aa6a7244d2d29357ccb30be835ab"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_system_info.php#a13b3aa6a7244d2d29357ccb30be835ab">setArchitecture</a> (Utility::String const &amp;arc)</td></tr>
<tr class="separator:a13b3aa6a7244d2d29357ccb30be835ab"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad5fb151aaa2834cc454d601a31d45efa"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_system_info.php#ad5fb151aaa2834cc454d601a31d45efa">setNbProcessors</a> (std::size_t nb)</td></tr>
<tr class="separator:ad5fb151aaa2834cc454d601a31d45efa"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afe7ce0708b0339b81cb7586367f682ea"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_system_info.php#afe7ce0708b0339b81cb7586367f682ea">setMemorySize</a> (std::size_t size)</td></tr>
<tr class="separator:afe7ce0708b0339b81cb7586367f682ea"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af4bca6d2b59fc2d5346b73197cf0b037"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_system_info.php#af4bca6d2b59fc2d5346b73197cf0b037">setMemoryUsed</a> (std::size_t used)</td></tr>
<tr class="separator:af4bca6d2b59fc2d5346b73197cf0b037"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab53617d75fd7e5ba0ce5b79887a153ef"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_system_info.php#ab53617d75fd7e5ba0ce5b79887a153ef">setMemoryUsedByProcess</a> (std::size_t used)</td></tr>
<tr class="separator:ab53617d75fd7e5ba0ce5b79887a153ef"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa83c461a28eff672246ab2448c7fd54c"><td class="memItemLeft" align="right" valign="top">Utility::String&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_system_info.php#aa83c461a28eff672246ab2448c7fd54c">toString</a> () const </td></tr>
<tr class="separator:aa83c461a28eff672246ab2448c7fd54c"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Represent all informations from the user system. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="acf7fa1fdd456441e427ec4057385f097"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">NRE::System::SystemInfo::SystemInfo </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct an empty system information set </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a646d882c712b19344bb9cfef2cef018a"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">Utility::String const&amp; NRE::System::SystemInfo::getArchitecture </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the <a class="el" href="class_n_r_e_1_1_system_1_1_system.php" title="Represent the System abstraction layer. ">System</a> Architecture </dd></dl>

</div>
</div>
<a class="anchor" id="accf4044376d402e48eb79e6ebba6b329"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">Utility::String const&amp; NRE::System::SystemInfo::getCPUName </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the CPU's name </dd></dl>

</div>
</div>
<a class="anchor" id="a04b218dae88cfd421e53fee946d6a637"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::size_t NRE::System::SystemInfo::getMemorySize </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the memory size </dd></dl>

</div>
</div>
<a class="anchor" id="a293ad706965abc2a3b6c28c56998071c"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::size_t NRE::System::SystemInfo::getMemoryUsed </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the memory used </dd></dl>

</div>
</div>
<a class="anchor" id="a32964d022a3401740d477e5ea9a33551"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::size_t NRE::System::SystemInfo::getMemoryUsedByProcess </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the memory used by the current process </dd></dl>

</div>
</div>
<a class="anchor" id="a60eee75af32e24cb32ce33521b654587"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::size_t NRE::System::SystemInfo::getNbProcessors </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the number of CPU </dd></dl>

</div>
</div>
<a class="anchor" id="a13b3aa6a7244d2d29357ccb30be835ab"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::System::SystemInfo::setArchitecture </td>
          <td>(</td>
          <td class="paramtype">Utility::String const &amp;&#160;</td>
          <td class="paramname"><em>arc</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Set the architecture value </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">arc</td><td>the new architecture value </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="ada33a1d288fa42bb0fdac2bef90acebc"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::System::SystemInfo::setCPUName </td>
          <td>(</td>
          <td class="paramtype">Utility::String const &amp;&#160;</td>
          <td class="paramname"><em>name</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Set the cpu name value </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">name</td><td>the new cpu's name </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="afe7ce0708b0339b81cb7586367f682ea"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::System::SystemInfo::setMemorySize </td>
          <td>(</td>
          <td class="paramtype">std::size_t&#160;</td>
          <td class="paramname"><em>size</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Set the memory size </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">size</td><td>the new memory size </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="af4bca6d2b59fc2d5346b73197cf0b037"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::System::SystemInfo::setMemoryUsed </td>
          <td>(</td>
          <td class="paramtype">std::size_t&#160;</td>
          <td class="paramname"><em>used</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Set the memory used size </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">used</td><td>the new memory used </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="ab53617d75fd7e5ba0ce5b79887a153ef"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::System::SystemInfo::setMemoryUsedByProcess </td>
          <td>(</td>
          <td class="paramtype">std::size_t&#160;</td>
          <td class="paramname"><em>used</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Set the memory used by this process value </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">used</td><td>the new memory used by process </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="ad5fb151aaa2834cc454d601a31d45efa"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::System::SystemInfo::setNbProcessors </td>
          <td>(</td>
          <td class="paramtype">std::size_t&#160;</td>
          <td class="paramname"><em>nb</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Set the number of processors </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">nb</td><td>the new number of processors </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="aa83c461a28eff672246ab2448c7fd54c"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">String NRE::System::SystemInfo::toString </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Convert the system info into a string </p><dl class="section return"><dt>Returns</dt><dd>the converted system info </dd></dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Info/<a class="el" href="_n_r_e___system_info_8hpp_source.php">NRE_SystemInfo.hpp</a></li>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Info/<a class="el" href="_n_r_e___system_info_8cpp.php">NRE_SystemInfo.cpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
