<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: NRE::Graphics::Window Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Graphics</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php">Window</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_graphics_1_1_window-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Graphics::Window Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Manage a graphics window.  
 <a href="class_n_r_e_1_1_graphics_1_1_window.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___window_8hpp_source.php">NRE_Window.hpp</a>&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:afb4a3ec6654693a69a77fdef0618a300"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php#afb4a3ec6654693a69a77fdef0618a300">Window</a> ()=delete</td></tr>
<tr class="separator:afb4a3ec6654693a69a77fdef0618a300"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8bdcdacc145f7bfd51e08ccb728ad1b9"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php#a8bdcdacc145f7bfd51e08ccb728ad1b9">Window</a> (Id const &amp;i, Utility::String const &amp;t, Math::Point2D&lt; unsigned int &gt; const &amp;pos, Math::Vector2D&lt; unsigned int &gt; const &amp;s, <a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a> const &amp;ws, <a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">ContextAttributes</a> const &amp;attr)</td></tr>
<tr class="separator:a8bdcdacc145f7bfd51e08ccb728ad1b9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab5fbeecb632d205ae5d6e8ff93d04f79"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php#ab5fbeecb632d205ae5d6e8ff93d04f79">Window</a> (Id const &amp;i, Utility::String const &amp;t, Math::Vector2D&lt; unsigned int &gt; const &amp;s, <a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a> const &amp;ws, <a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">ContextAttributes</a> const &amp;attr)</td></tr>
<tr class="separator:ab5fbeecb632d205ae5d6e8ff93d04f79"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a82addea35e5f30949ca5128836703509"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php#a82addea35e5f30949ca5128836703509">Window</a> (<a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php">Window</a> const &amp;w)=delete</td></tr>
<tr class="separator:a82addea35e5f30949ca5128836703509"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8eb5380913c81ba9030de6766f7bf31f"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php#a8eb5380913c81ba9030de6766f7bf31f">Window</a> (<a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php">Window</a> &amp;&amp;w)=delete</td></tr>
<tr class="separator:a8eb5380913c81ba9030de6766f7bf31f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a578cc889485c2db6e2b7c00cb01268a8"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php#a578cc889485c2db6e2b7c00cb01268a8">~Window</a> ()</td></tr>
<tr class="separator:a578cc889485c2db6e2b7c00cb01268a8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a75d09fcf9899e97ab4729aec113551fe"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php#a75d09fcf9899e97ab4729aec113551fe">isRunning</a> () const </td></tr>
<tr class="separator:a75d09fcf9899e97ab4729aec113551fe"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1a8c28f36a398d0e10bd4c7b1cf89ac4"><td class="memItemLeft" align="right" valign="top">Id&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php#a1a8c28f36a398d0e10bd4c7b1cf89ac4">getId</a> () const </td></tr>
<tr class="separator:a1a8c28f36a398d0e10bd4c7b1cf89ac4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2a5f32f300a87565e5db94f459dbf963"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php#a2a5f32f300a87565e5db94f459dbf963">close</a> (bool removeFromSystem=true)</td></tr>
<tr class="separator:a2a5f32f300a87565e5db94f459dbf963"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac255a15a9f8b13961d6103ebc273a280"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php#ac255a15a9f8b13961d6103ebc273a280">refresh</a> ()</td></tr>
<tr class="separator:ac255a15a9f8b13961d6103ebc273a280"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a31b91ff88d0cc953df075840e4a7d7f8"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php">Window</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php#a31b91ff88d0cc953df075840e4a7d7f8">operator=</a> (<a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php">Window</a> const &amp;w)=delete</td></tr>
<tr class="separator:a31b91ff88d0cc953df075840e4a7d7f8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a280bdd579559cf42a48983e127d863f6"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php">Window</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php#a280bdd579559cf42a48983e127d863f6">operator=</a> (<a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php">Window</a> &amp;&amp;w)=delete</td></tr>
<tr class="separator:a280bdd579559cf42a48983e127d863f6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5ac753c6a5f4126e47190159cd3a8c9b"><td class="memItemLeft" align="right" valign="top">Utility::String&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php#a5ac753c6a5f4126e47190159cd3a8c9b">toString</a> () const </td></tr>
<tr class="separator:a5ac753c6a5f4126e47190159cd3a8c9b"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Manage a graphics window. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="afb4a3ec6654693a69a77fdef0618a300"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Graphics::Window::Window </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>No default constructor </p>

</div>
</div>
<a class="anchor" id="a8bdcdacc145f7bfd51e08ccb728ad1b9"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Graphics::Window::Window </td>
          <td>(</td>
          <td class="paramtype">Id const &amp;&#160;</td>
          <td class="paramname"><em>i</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Utility::String const &amp;&#160;</td>
          <td class="paramname"><em>t</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Math::Point2D&lt; unsigned int &gt; const &amp;&#160;</td>
          <td class="paramname"><em>pos</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Math::Vector2D&lt; unsigned int &gt; const &amp;&#160;</td>
          <td class="paramname"><em>s</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a> const &amp;&#160;</td>
          <td class="paramname"><em>ws</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">ContextAttributes</a> const &amp;&#160;</td>
          <td class="paramname"><em>attr</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct the window </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">i</td><td>the window id </td></tr>
    <tr><td class="paramname">t</td><td>the window title </td></tr>
    <tr><td class="paramname">pos</td><td>the window top-left corner position </td></tr>
    <tr><td class="paramname">s</td><td>the window size </td></tr>
    <tr><td class="paramname">ws</td><td>the window style value </td></tr>
    <tr><td class="paramname">attr</td><td>the window context attributes </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="ab5fbeecb632d205ae5d6e8ff93d04f79"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Graphics::Window::Window </td>
          <td>(</td>
          <td class="paramtype">Id const &amp;&#160;</td>
          <td class="paramname"><em>i</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Utility::String const &amp;&#160;</td>
          <td class="paramname"><em>t</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Math::Vector2D&lt; unsigned int &gt; const &amp;&#160;</td>
          <td class="paramname"><em>s</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a> const &amp;&#160;</td>
          <td class="paramname"><em>ws</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">ContextAttributes</a> const &amp;&#160;</td>
          <td class="paramname"><em>attr</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct the window with centered position </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">i</td><td>the window id </td></tr>
    <tr><td class="paramname">t</td><td>the window title </td></tr>
    <tr><td class="paramname">s</td><td>the window size </td></tr>
    <tr><td class="paramname">ws</td><td>the window style value </td></tr>
    <tr><td class="paramname">attr</td><td>the window context attributes </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a82addea35e5f30949ca5128836703509"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Graphics::Window::Window </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php">Window</a> const &amp;&#160;</td>
          <td class="paramname"><em>w</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">w</td><td>the window to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a8eb5380913c81ba9030de6766f7bf31f"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Graphics::Window::Window </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php">Window</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>w</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">w</td><td>the window to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a578cc889485c2db6e2b7c00cb01268a8"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Graphics::Window::~Window </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php" title="Manage a graphics window. ">Window</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a2a5f32f300a87565e5db94f459dbf963"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Graphics::Window::close </td>
          <td>(</td>
          <td class="paramtype">bool&#160;</td>
          <td class="paramname"><em>removeFromSystem</em> = <code>true</code></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Close the window and free all resources, don't use it after this operation </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">removeFromSystem</td><td>tell if the window has to be removed from the graphics system </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a1a8c28f36a398d0e10bd4c7b1cf89ac4"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">Id NRE::Graphics::Window::getId </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the window id </dd></dl>

</div>
</div>
<a class="anchor" id="a75d09fcf9899e97ab4729aec113551fe"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">bool NRE::Graphics::Window::isRunning </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>if the window is running </dd></dl>

</div>
</div>
<a class="anchor" id="a31b91ff88d0cc953df075840e4a7d7f8"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php">Window</a>&amp; NRE::Graphics::Window::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php">Window</a> const &amp;&#160;</td>
          <td class="paramname"><em>w</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">w</td><td>the object to copy into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a280bdd579559cf42a48983e127d863f6"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php">Window</a>&amp; NRE::Graphics::Window::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php">Window</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>w</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">w</td><td>the object to move into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="ac255a15a9f8b13961d6103ebc273a280"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Graphics::Window::refresh </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Refresh the window screen </p>

</div>
</div>
<a class="anchor" id="a5ac753c6a5f4126e47190159cd3a8c9b"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">String NRE::Graphics::Window::toString </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Convert the window into a string </p><dl class="section return"><dt>Returns</dt><dd>the converted window </dd></dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Graphics/Window/<a class="el" href="_n_r_e___window_8hpp_source.php">NRE_Window.hpp</a></li>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Graphics/Window/<a class="el" href="_n_r_e___window_8cpp.php">NRE_Window.cpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
