<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: NRE::Graphics::GraphicsDriver Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Graphics</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_graphics_1_1_graphics_driver.php">GraphicsDriver</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_graphics_1_1_graphics_driver-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Graphics::GraphicsDriver Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Manage the os-dependant graphics driver.  
 <a href="class_n_r_e_1_1_graphics_1_1_graphics_driver.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___graphics_driver_8hpp_source.php">NRE_GraphicsDriver.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for NRE::Graphics::GraphicsDriver:</div>
<div class="dyncontent">
 <div class="center">
  <img src="class_n_r_e_1_1_graphics_1_1_graphics_driver.png" usemap="#NRE::Graphics::GraphicsDriver_map" alt=""/>
  <map id="NRE::Graphics::GraphicsDriver_map" name="NRE::Graphics::GraphicsDriver_map">
</map>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:aca47f0b1940f67a28068208bd90665ed"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_graphics_driver.php#aca47f0b1940f67a28068208bd90665ed">GraphicsDriver</a> (<a class="el" href="class_n_r_e_1_1_graphics_1_1_graphics_driver.php">GraphicsDriver</a> &amp;&amp;drv)=delete</td></tr>
<tr class="separator:aca47f0b1940f67a28068208bd90665ed"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a065c6b942cdb7747fd4b0f397fbe2976"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_graphics_driver.php#a065c6b942cdb7747fd4b0f397fbe2976">~GraphicsDriver</a> ()</td></tr>
<tr class="separator:a065c6b942cdb7747fd4b0f397fbe2976"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a30b763db26e35abbffd65764c13c6e63"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_graphics_driver.php#a30b763db26e35abbffd65764c13c6e63">registerWindow</a> (NativeWindowType window, Id id)</td></tr>
<tr class="separator:a30b763db26e35abbffd65764c13c6e63"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a28629d3a2e0025ff360cea6a0578f7a9"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_graphics_driver.php#a28629d3a2e0025ff360cea6a0578f7a9">unregisterWindow</a> (NativeWindowType window)</td></tr>
<tr class="separator:a28629d3a2e0025ff360cea6a0578f7a9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a030f91488049870b404df084c671a80a"><td class="memItemLeft" align="right" valign="top">Id&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_graphics_driver.php#a030f91488049870b404df084c671a80a">findId</a> (NativeWindowType window) const </td></tr>
<tr class="separator:a030f91488049870b404df084c671a80a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acccee0609eae30ac095fbe27d6598136"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_graphics_1_1_graphics_driver.php">GraphicsDriver</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_graphics_1_1_graphics_driver.php#acccee0609eae30ac095fbe27d6598136">operator=</a> (<a class="el" href="class_n_r_e_1_1_graphics_1_1_graphics_driver.php">GraphicsDriver</a> &amp;&amp;drv)=delete</td></tr>
<tr class="separator:acccee0609eae30ac095fbe27d6598136"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Manage the os-dependant graphics driver. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="aca47f0b1940f67a28068208bd90665ed"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Graphics::GraphicsDriver::GraphicsDriver </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_graphics_driver.php">GraphicsDriver</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>drv</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">drv</td><td>the graphics driver to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a065c6b942cdb7747fd4b0f397fbe2976"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Graphics::GraphicsDriver::~GraphicsDriver </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_graphics_1_1_graphics_driver.php" title="Manage the os-dependant graphics driver. ">GraphicsDriver</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a030f91488049870b404df084c671a80a"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">Id NRE::Graphics::GraphicsDriver::findId </td>
          <td>(</td>
          <td class="paramtype">NativeWindowType&#160;</td>
          <td class="paramname"><em>window</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Find the window id associated with the given window </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">window</td><td>the window to retrive the id </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the corresponding id </dd></dl>

</div>
</div>
<a class="anchor" id="acccee0609eae30ac095fbe27d6598136"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_graphics_1_1_graphics_driver.php">GraphicsDriver</a>&amp; NRE::Graphics::GraphicsDriver::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_graphics_driver.php">GraphicsDriver</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>drv</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">drv</td><td>the object to move into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a30b763db26e35abbffd65764c13c6e63"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Graphics::GraphicsDriver::registerWindow </td>
          <td>(</td>
          <td class="paramtype">NativeWindowType&#160;</td>
          <td class="paramname"><em>window</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Id&#160;</td>
          <td class="paramname"><em>id</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Register a window into the driver </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">window</td><td>the window to store </td></tr>
    <tr><td class="paramname">id</td><td>the window id </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a28629d3a2e0025ff360cea6a0578f7a9"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Graphics::GraphicsDriver::unregisterWindow </td>
          <td>(</td>
          <td class="paramtype">NativeWindowType&#160;</td>
          <td class="paramname"><em>window</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Unregister a window from the driver </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">window</td><td>the window to remove </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Graphics/Driver/<a class="el" href="_n_r_e___graphics_driver_8hpp_source.php">NRE_GraphicsDriver.hpp</a></li>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Graphics/Driver/<a class="el" href="_n_r_e___graphics_driver_8cpp.php">NRE_GraphicsDriver.cpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
