<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: NRE::System::EventSystem Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>System</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_system_1_1_event_system.php">EventSystem</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_system_1_1_event_system-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::System::EventSystem Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Manage the event sub system.  
 <a href="class_n_r_e_1_1_system_1_1_event_system.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___event_system_8hpp_source.php">NRE_EventSystem.hpp</a>&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:ab3bf40a7947f3b651cbe9254590625fe"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_event_system.php#ab3bf40a7947f3b651cbe9254590625fe">EventSystem</a> ()</td></tr>
<tr class="separator:ab3bf40a7947f3b651cbe9254590625fe"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af1dcd070da03d10f23ae1636cc54effa"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_event_system.php#af1dcd070da03d10f23ae1636cc54effa">EventSystem</a> (<a class="el" href="class_n_r_e_1_1_system_1_1_event_system.php">EventSystem</a> const &amp;sys)=delete</td></tr>
<tr class="separator:af1dcd070da03d10f23ae1636cc54effa"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a135502cfc778940383dbef36deed5d16"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_event_system.php#a135502cfc778940383dbef36deed5d16">EventSystem</a> (<a class="el" href="class_n_r_e_1_1_system_1_1_event_system.php">EventSystem</a> &amp;&amp;sys)=delete</td></tr>
<tr class="separator:a135502cfc778940383dbef36deed5d16"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aafaaefc1339e527dbf2d1e3597081d20"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_event_system.php#aafaaefc1339e527dbf2d1e3597081d20">~EventSystem</a> ()=default</td></tr>
<tr class="separator:aafaaefc1339e527dbf2d1e3597081d20"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:adfa9246b3c4eec397e788d5220183599"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_event_system.php#adfa9246b3c4eec397e788d5220183599">update</a> ()</td></tr>
<tr class="separator:adfa9246b3c4eec397e788d5220183599"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac14dbb8c4e7fefd76d5b961337b621e3"><td class="memTemplParams" colspan="2">template&lt;class T , class... Args&gt; </td></tr>
<tr class="memitem:ac14dbb8c4e7fefd76d5b961337b621e3"><td class="memTemplItemLeft" align="right" valign="top">bool&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_event_system.php#ac14dbb8c4e7fefd76d5b961337b621e3">emit</a> (Args &amp;&amp;...args)</td></tr>
<tr class="separator:ac14dbb8c4e7fefd76d5b961337b621e3"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa540cdc7aacb0b572c16590f24db62cc"><td class="memTemplParams" colspan="2">template&lt;class T &gt; </td></tr>
<tr class="memitem:aa540cdc7aacb0b572c16590f24db62cc"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_event_system.php#aa540cdc7aacb0b572c16590f24db62cc">addHandler</a> (<a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php">Event::EventHandler</a>&lt; T &gt; *handler)</td></tr>
<tr class="separator:aa540cdc7aacb0b572c16590f24db62cc"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a843dec23d4c6b7196577120d031513c7"><td class="memTemplParams" colspan="2">template&lt;class T &gt; </td></tr>
<tr class="memitem:a843dec23d4c6b7196577120d031513c7"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_event_system.php#a843dec23d4c6b7196577120d031513c7">removeHandler</a> (<a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php">Event::EventHandler</a>&lt; T &gt; *handler)</td></tr>
<tr class="separator:a843dec23d4c6b7196577120d031513c7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0f6de0f3f684c9486dee59b032423950"><td class="memTemplParams" colspan="2">template&lt;class T &gt; </td></tr>
<tr class="memitem:a0f6de0f3f684c9486dee59b032423950"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_event_system.php#a0f6de0f3f684c9486dee59b032423950">registerEvent</a> ()</td></tr>
<tr class="separator:a0f6de0f3f684c9486dee59b032423950"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aadb5c6bb24595201ce407e05b2684c2b"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_system_1_1_event_system.php">EventSystem</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_event_system.php#aadb5c6bb24595201ce407e05b2684c2b">operator=</a> (<a class="el" href="class_n_r_e_1_1_system_1_1_event_system.php">EventSystem</a> const &amp;sys)=delete</td></tr>
<tr class="separator:aadb5c6bb24595201ce407e05b2684c2b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acf26a9212cbdb323301e7a83ff816aa5"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_system_1_1_event_system.php">EventSystem</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_event_system.php#acf26a9212cbdb323301e7a83ff816aa5">operator=</a> (<a class="el" href="class_n_r_e_1_1_system_1_1_event_system.php">EventSystem</a> &amp;&amp;sys)=delete</td></tr>
<tr class="separator:acf26a9212cbdb323301e7a83ff816aa5"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Manage the event sub system. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="ab3bf40a7947f3b651cbe9254590625fe"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">NRE::System::EventSystem::EventSystem </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct the sub system </p>

</div>
</div>
<a class="anchor" id="af1dcd070da03d10f23ae1636cc54effa"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::System::EventSystem::EventSystem </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_system_1_1_event_system.php">EventSystem</a> const &amp;&#160;</td>
          <td class="paramname"><em>sys</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">sys</td><td>the event system to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a135502cfc778940383dbef36deed5d16"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::System::EventSystem::EventSystem </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_system_1_1_event_system.php">EventSystem</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>sys</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">sys</td><td>the event system to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="aafaaefc1339e527dbf2d1e3597081d20"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::System::EventSystem::~EventSystem </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_system_1_1_event_system.php" title="Manage the event sub system. ">EventSystem</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="aa540cdc7aacb0b572c16590f24db62cc"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void NRE::System::EventSystem::addHandler </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php">Event::EventHandler</a>&lt; T &gt; *&#160;</td>
          <td class="paramname"><em>handler</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Add an event handler </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">handler</td><td>the handler to add </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="ac14dbb8c4e7fefd76d5b961337b621e3"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class... Args&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">bool NRE::System::EventSystem::emit </td>
          <td>(</td>
          <td class="paramtype">Args &amp;&amp;...&#160;</td>
          <td class="paramname"><em>args</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Emit a T event by the corresponding emitter </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">args</td><td>pack of parameter forwarded to the emitters </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>if the emitted event has been consumed </dd></dl>

</div>
</div>
<a class="anchor" id="aadb5c6bb24595201ce407e05b2684c2b"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_system_1_1_event_system.php">EventSystem</a>&amp; NRE::System::EventSystem::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_system_1_1_event_system.php">EventSystem</a> const &amp;&#160;</td>
          <td class="paramname"><em>sys</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">sys</td><td>the object to copy into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="acf26a9212cbdb323301e7a83ff816aa5"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_system_1_1_event_system.php">EventSystem</a>&amp; NRE::System::EventSystem::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_system_1_1_event_system.php">EventSystem</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>sys</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">sys</td><td>the object to move into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a0f6de0f3f684c9486dee59b032423950"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void NRE::System::EventSystem::registerEvent </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Register an event to be supported by the system </p>

</div>
</div>
<a class="anchor" id="a843dec23d4c6b7196577120d031513c7"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void NRE::System::EventSystem::removeHandler </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php">Event::EventHandler</a>&lt; T &gt; *&#160;</td>
          <td class="paramname"><em>handler</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Remove an event handler </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">handler</td><td>the handler to remove </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="adfa9246b3c4eec397e788d5220183599"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::System::EventSystem::update </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Update the event system and dispatch event </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Event/<a class="el" href="_n_r_e___event_system_8hpp_source.php">NRE_EventSystem.hpp</a></li>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/OS/Linux/Event/<a class="el" href="_n_r_e___linux_event_system_8cpp.php">NRE_LinuxEventSystem.cpp</a></li>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/OS/Windows/Event/<a class="el" href="_n_r_e___windows_event_system_8cpp.php">NRE_WindowsEventSystem.cpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
