<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: NRE::System::GraphicsSystem Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>System</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_system_1_1_graphics_system.php">GraphicsSystem</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_system_1_1_graphics_system-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::System::GraphicsSystem Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Manage the graphics sub system.  
 <a href="class_n_r_e_1_1_system_1_1_graphics_system.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___graphics_system_8hpp_source.php">NRE_GraphicsSystem.hpp</a>&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a21c1ed2d8e7e7749616afa84c0c99dc1"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_graphics_system.php#a21c1ed2d8e7e7749616afa84c0c99dc1">GraphicsSystem</a> ()</td></tr>
<tr class="separator:a21c1ed2d8e7e7749616afa84c0c99dc1"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac2fe2146d857045f46f72a13c83de34c"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_graphics_system.php#ac2fe2146d857045f46f72a13c83de34c">GraphicsSystem</a> (<a class="el" href="class_n_r_e_1_1_system_1_1_graphics_system.php">GraphicsSystem</a> const &amp;sys)=delete</td></tr>
<tr class="separator:ac2fe2146d857045f46f72a13c83de34c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa66c608cf9a7877e2e2a68f7b97b85e3"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_graphics_system.php#aa66c608cf9a7877e2e2a68f7b97b85e3">GraphicsSystem</a> (<a class="el" href="class_n_r_e_1_1_system_1_1_graphics_system.php">GraphicsSystem</a> &amp;&amp;sys)=delete</td></tr>
<tr class="separator:aa66c608cf9a7877e2e2a68f7b97b85e3"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a14000797c1edf260675cf16a70276df5"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_graphics_system.php#a14000797c1edf260675cf16a70276df5">~GraphicsSystem</a> ()</td></tr>
<tr class="separator:a14000797c1edf260675cf16a70276df5"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac856987f85e1c7f3ceb17075b9fa0845"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php">Graphics::Window</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_graphics_system.php#ac856987f85e1c7f3ceb17075b9fa0845">getWindow</a> (Graphics::Id id)</td></tr>
<tr class="separator:ac856987f85e1c7f3ceb17075b9fa0845"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a10e0a93d4f756515711c309550ee4099"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_graphics_system.php#a10e0a93d4f756515711c309550ee4099">closeWindow</a> (Graphics::Id id)</td></tr>
<tr class="separator:a10e0a93d4f756515711c309550ee4099"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae73e6260470cf6d4afac187cba4e431c"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_graphics_system.php#ae73e6260470cf6d4afac187cba4e431c">isRunning</a> () const </td></tr>
<tr class="separator:ae73e6260470cf6d4afac187cba4e431c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4f3eafe115b1516f039e8a537caf83b0"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php">Graphics::Window</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_graphics_system.php#a4f3eafe115b1516f039e8a537caf83b0">createWindow</a> (Utility::String const &amp;title, Math::Point2D&lt; unsigned int &gt; const &amp;position, Math::Vector2D&lt; unsigned int &gt; const &amp;size, unsigned int style, <a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">Graphics::ContextAttributes</a> const &amp;attr)</td></tr>
<tr class="separator:a4f3eafe115b1516f039e8a537caf83b0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2e274df8691b22084899eeba83781994"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php">Graphics::Window</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_graphics_system.php#a2e274df8691b22084899eeba83781994">createWindow</a> (Utility::String const &amp;title, Math::Vector2D&lt; unsigned int &gt; const &amp;size, unsigned int style, <a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">Graphics::ContextAttributes</a> const &amp;attr)</td></tr>
<tr class="separator:a2e274df8691b22084899eeba83781994"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8a743aa5637475cf7203cba2c6621d49"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_graphics_system.php#a8a743aa5637475cf7203cba2c6621d49">removeWindow</a> (Graphics::Id const &amp;id)</td></tr>
<tr class="separator:a8a743aa5637475cf7203cba2c6621d49"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a90ef417cfe165ad559a7cdcbfb333b25"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_system_1_1_graphics_system.php">GraphicsSystem</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_graphics_system.php#a90ef417cfe165ad559a7cdcbfb333b25">operator=</a> (<a class="el" href="class_n_r_e_1_1_system_1_1_graphics_system.php">GraphicsSystem</a> const &amp;sys)=delete</td></tr>
<tr class="separator:a90ef417cfe165ad559a7cdcbfb333b25"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac7d82e856e369d86e7413cac40f3c4de"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_system_1_1_graphics_system.php">GraphicsSystem</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_system_1_1_graphics_system.php#ac7d82e856e369d86e7413cac40f3c4de">operator=</a> (<a class="el" href="class_n_r_e_1_1_system_1_1_graphics_system.php">GraphicsSystem</a> &amp;&amp;sys)=delete</td></tr>
<tr class="separator:ac7d82e856e369d86e7413cac40f3c4de"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Manage the graphics sub system. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a21c1ed2d8e7e7749616afa84c0c99dc1"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">NRE::System::GraphicsSystem::GraphicsSystem </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct the sub system </p>

</div>
</div>
<a class="anchor" id="ac2fe2146d857045f46f72a13c83de34c"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::System::GraphicsSystem::GraphicsSystem </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_system_1_1_graphics_system.php">GraphicsSystem</a> const &amp;&#160;</td>
          <td class="paramname"><em>sys</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">sys</td><td>the graphics system to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="aa66c608cf9a7877e2e2a68f7b97b85e3"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::System::GraphicsSystem::GraphicsSystem </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_system_1_1_graphics_system.php">GraphicsSystem</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>sys</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">sys</td><td>the graphics system to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a14000797c1edf260675cf16a70276df5"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">NRE::System::GraphicsSystem::~GraphicsSystem </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_system_1_1_graphics_system.php" title="Manage the graphics sub system. ">GraphicsSystem</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a10e0a93d4f756515711c309550ee4099"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::System::GraphicsSystem::closeWindow </td>
          <td>(</td>
          <td class="paramtype">Graphics::Id&#160;</td>
          <td class="paramname"><em>id</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Close a specific window </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">id</td><td>the window id </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a4f3eafe115b1516f039e8a537caf83b0"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php">Graphics::Window</a>&amp; NRE::System::GraphicsSystem::createWindow </td>
          <td>(</td>
          <td class="paramtype">Utility::String const &amp;&#160;</td>
          <td class="paramname"><em>title</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Math::Point2D&lt; unsigned int &gt; const &amp;&#160;</td>
          <td class="paramname"><em>position</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Math::Vector2D&lt; unsigned int &gt; const &amp;&#160;</td>
          <td class="paramname"><em>size</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">unsigned int&#160;</td>
          <td class="paramname"><em>style</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">Graphics::ContextAttributes</a> const &amp;&#160;</td>
          <td class="paramname"><em>attr</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Create a window and register it in the system </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">title</td><td>the window title </td></tr>
    <tr><td class="paramname">position</td><td>the window top-left corner position </td></tr>
    <tr><td class="paramname">size</td><td>the window size </td></tr>
    <tr><td class="paramname">style</td><td>the window style </td></tr>
    <tr><td class="paramname">attr</td><td>the window context attributes </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the created window </dd></dl>

</div>
</div>
<a class="anchor" id="a2e274df8691b22084899eeba83781994"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php">Graphics::Window</a>&amp; NRE::System::GraphicsSystem::createWindow </td>
          <td>(</td>
          <td class="paramtype">Utility::String const &amp;&#160;</td>
          <td class="paramname"><em>title</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Math::Vector2D&lt; unsigned int &gt; const &amp;&#160;</td>
          <td class="paramname"><em>size</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">unsigned int&#160;</td>
          <td class="paramname"><em>style</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php">Graphics::ContextAttributes</a> const &amp;&#160;</td>
          <td class="paramname"><em>attr</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Create a window and register it in the system </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">title</td><td>the window title </td></tr>
    <tr><td class="paramname">size</td><td>the window size </td></tr>
    <tr><td class="paramname">style</td><td>the window style </td></tr>
    <tr><td class="paramname">attr</td><td>the window context attributes </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the created window </dd></dl>

</div>
</div>
<a class="anchor" id="ac856987f85e1c7f3ceb17075b9fa0845"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php">Graphics::Window</a>&amp; NRE::System::GraphicsSystem::getWindow </td>
          <td>(</td>
          <td class="paramtype">Graphics::Id&#160;</td>
          <td class="paramname"><em>id</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Query a specific window </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">id</td><td>the window id </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the corresponding window </dd></dl>

</div>
</div>
<a class="anchor" id="ae73e6260470cf6d4afac187cba4e431c"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">bool NRE::System::GraphicsSystem::isRunning </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>if at least one window is opened </dd></dl>

</div>
</div>
<a class="anchor" id="a90ef417cfe165ad559a7cdcbfb333b25"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_system_1_1_graphics_system.php">GraphicsSystem</a>&amp; NRE::System::GraphicsSystem::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_system_1_1_graphics_system.php">GraphicsSystem</a> const &amp;&#160;</td>
          <td class="paramname"><em>sys</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">sys</td><td>the object to copy into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="ac7d82e856e369d86e7413cac40f3c4de"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_system_1_1_graphics_system.php">GraphicsSystem</a>&amp; NRE::System::GraphicsSystem::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_system_1_1_graphics_system.php">GraphicsSystem</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>sys</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">sys</td><td>the object to move into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a8a743aa5637475cf7203cba2c6621d49"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::System::GraphicsSystem::removeWindow </td>
          <td>(</td>
          <td class="paramtype">Graphics::Id const &amp;&#160;</td>
          <td class="paramname"><em>id</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Remove the window corresponding to the given id </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">id</td><td>the window to remove </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Graphics/<a class="el" href="_n_r_e___graphics_system_8hpp_source.php">NRE_GraphicsSystem.hpp</a></li>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-System/src/System/Graphics/<a class="el" href="_n_r_e___graphics_system_8cpp.php">NRE_GraphicsSystem.cpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
