<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: Member List</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Graphics</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">WindowStyle</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE::Graphics::WindowStyle Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">NRE::Graphics::WindowStyle</a>, including all inherited members.</p>
<table class="directory">
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php#a5926ee9e0b531a0ff3118a576d78b374">BASIC</a></td><td class="entry"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">NRE::Graphics::WindowStyle</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php#aa256a85a03ac8c3c2a88b90e1db72c77">CLOSEABLE</a></td><td class="entry"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">NRE::Graphics::WindowStyle</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php#a77500dc9eeaa013d8173993859713b7a">FULLSCREEN</a></td><td class="entry"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">NRE::Graphics::WindowStyle</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php#a9138844bf5232283fec196a69a678390">operator&amp;</a>(unsigned int ws) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">NRE::Graphics::WindowStyle</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php#a2ef6bba5ff5e4f062713c12a12a14a1f">operator=</a>(WindowStyle const &amp;ws)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">NRE::Graphics::WindowStyle</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php#a4ddbc792d3bf210cbbb7c4c183492ee0">operator=</a>(WindowStyle &amp;&amp;ws)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">NRE::Graphics::WindowStyle</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php#a700de39ee28aaf2cacb0acced6988925">operator|</a>(WindowStyle const &amp;ws) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">NRE::Graphics::WindowStyle</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php#a70a5510030cb277349ba4e4ec1a52ac3">operator|=</a>(WindowStyle const &amp;ws)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">NRE::Graphics::WindowStyle</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php#a04ecda3096b6634ac17dad385ce3b876">RESIZEABLE</a></td><td class="entry"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">NRE::Graphics::WindowStyle</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php#abd3b517579efdd1b7fb3b0fa9c7221c4">WindowStyle</a>(unsigned int s=BASIC)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">NRE::Graphics::WindowStyle</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php#a33cfa2a025595ef080ed2687ab2eb913">WindowStyle</a>(WindowStyle const &amp;ws)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">NRE::Graphics::WindowStyle</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php#a66f37dce24f8655daa77ede3ac289633">WindowStyle</a>(WindowStyle &amp;&amp;ws)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">NRE::Graphics::WindowStyle</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php#a18360d5c69c3ae20624ac0fb2a312b65">~WindowStyle</a>()=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php">NRE::Graphics::WindowStyle</a></td><td class="entry"></td></tr>
</table></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
