<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: Class Members</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li class="current"><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
  <div id="navrow3" class="tabs2">
    <ul class="tablist">
      <li class="current"><a href="functions.php"><span>All</span></a></li>
      <li><a href="functions_func.php"><span>Functions</span></a></li>
      <li><a href="functions_vars.php"><span>Variables</span></a></li>
      <li><a href="functions_type.php"><span>Typedefs</span></a></li>
      <li><a href="functions_rela.php"><span>Related&#160;Functions</span></a></li>
    </ul>
  </div>
  <div id="navrow4" class="tabs3">
    <ul class="tablist">
      <li><a href="functions.php#index_a"><span>a</span></a></li>
      <li><a href="functions_b.php#index_b"><span>b</span></a></li>
      <li><a href="functions_c.php#index_c"><span>c</span></a></li>
      <li><a href="functions_d.php#index_d"><span>d</span></a></li>
      <li><a href="functions_e.php#index_e"><span>e</span></a></li>
      <li><a href="functions_f.php#index_f"><span>f</span></a></li>
      <li><a href="functions_g.php#index_g"><span>g</span></a></li>
      <li><a href="functions_h.php#index_h"><span>h</span></a></li>
      <li><a href="functions_i.php#index_i"><span>i</span></a></li>
      <li><a href="functions_k.php#index_k"><span>k</span></a></li>
      <li><a href="functions_m.php#index_m"><span>m</span></a></li>
      <li><a href="functions_n.php#index_n"><span>n</span></a></li>
      <li><a href="functions_o.php#index_o"><span>o</span></a></li>
      <li><a href="functions_p.php#index_p"><span>p</span></a></li>
      <li><a href="functions_q.php#index_q"><span>q</span></a></li>
      <li><a href="functions_r.php#index_r"><span>r</span></a></li>
      <li class="current"><a href="functions_s.php#index_s"><span>s</span></a></li>
      <li><a href="functions_t.php#index_t"><span>t</span></a></li>
      <li><a href="functions_u.php#index_u"><span>u</span></a></li>
      <li><a href="functions_w.php#index_w"><span>w</span></a></li>
      <li><a href="functions_0x7e.php#index_0x7e"><span>~</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
<div class="textblock">Here is a list of all documented class members with links to the class documentation for each member:</div>

<h3><a class="anchor" id="index_s"></a>- s -</h3><ul>
<li>setArchitecture()
: <a class="el" href="class_n_r_e_1_1_system_1_1_system_info.php#a13b3aa6a7244d2d29357ccb30be835ab">NRE::System::SystemInfo</a>
</li>
<li>setClosed()
: <a class="el" href="class_n_r_e_1_1_graphics_1_1_window_status.php#a96bd10aa2cb54cd70ecb8c3c480c16e7">NRE::Graphics::WindowStatus</a>
</li>
<li>setConsumed()
: <a class="el" href="class_n_r_e_1_1_event_1_1_abstract_event_emitter.php#a61c5e87e19799557ba980e4b6ddc6b1b">NRE::Event::AbstractEventEmitter</a>
</li>
<li>setCPUName()
: <a class="el" href="class_n_r_e_1_1_system_1_1_system_info.php#ada33a1d288fa42bb0fdac2bef90acebc">NRE::System::SystemInfo</a>
</li>
<li>setFullscreen()
: <a class="el" href="class_n_r_e_1_1_graphics_1_1_window_status.php#aada6a41a88391b418d962e3407d08e52">NRE::Graphics::WindowStatus</a>
</li>
<li>setMemorySize()
: <a class="el" href="class_n_r_e_1_1_system_1_1_system_info.php#afe7ce0708b0339b81cb7586367f682ea">NRE::System::SystemInfo</a>
</li>
<li>setMemoryUsed()
: <a class="el" href="class_n_r_e_1_1_system_1_1_system_info.php#af4bca6d2b59fc2d5346b73197cf0b037">NRE::System::SystemInfo</a>
</li>
<li>setMemoryUsedByProcess()
: <a class="el" href="class_n_r_e_1_1_system_1_1_system_info.php#ab53617d75fd7e5ba0ce5b79887a153ef">NRE::System::SystemInfo</a>
</li>
<li>setNbProcessors()
: <a class="el" href="class_n_r_e_1_1_system_1_1_system_info.php#ad5fb151aaa2834cc454d601a31d45efa">NRE::System::SystemInfo</a>
</li>
<li>setPosition()
: <a class="el" href="class_n_r_e_1_1_graphics_1_1_window_attributes.php#accdfba6b43172d59cd2d7bd3f69dea7a">NRE::Graphics::WindowAttributes</a>
</li>
<li>showFPS()
: <a class="el" href="class_n_r_e_1_1_time_1_1_clock.php#a15fbdd1027cbb859d5cdb88f67ee9d5d">NRE::Time::Clock</a>
</li>
<li>sleep()
: <a class="el" href="class_n_r_e_1_1_time_1_1_clock.php#ad38ac4031cc4c65a0eb7ef1f350fac4b">NRE::Time::Clock</a>
</li>
<li>System()
: <a class="el" href="class_n_r_e_1_1_system_1_1_system.php#a071e220861b0cf5005f79d817bf63775">NRE::System::System</a>
</li>
<li>SystemException()
: <a class="el" href="class_n_r_e_1_1_exception_1_1_system_exception.php#a370c054e92c620b304a9ba1905cd5629">NRE::Exception::SystemException</a>
</li>
<li>SystemInfo()
: <a class="el" href="class_n_r_e_1_1_system_1_1_system_info.php#acf7fa1fdd456441e427ec4057385f097">NRE::System::SystemInfo</a>
</li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
