<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: Class Members - Functions</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li class="current"><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
  <div id="navrow3" class="tabs2">
    <ul class="tablist">
      <li><a href="functions.php"><span>All</span></a></li>
      <li class="current"><a href="functions_func.php"><span>Functions</span></a></li>
      <li><a href="functions_vars.php"><span>Variables</span></a></li>
      <li><a href="functions_type.php"><span>Typedefs</span></a></li>
      <li><a href="functions_rela.php"><span>Related&#160;Functions</span></a></li>
    </ul>
  </div>
  <div id="navrow4" class="tabs3">
    <ul class="tablist">
      <li><a href="functions_func.php#index_a"><span>a</span></a></li>
      <li><a href="functions_func_b.php#index_b"><span>b</span></a></li>
      <li><a href="functions_func_c.php#index_c"><span>c</span></a></li>
      <li><a href="functions_func_d.php#index_d"><span>d</span></a></li>
      <li><a href="functions_func_e.php#index_e"><span>e</span></a></li>
      <li><a href="functions_func_f.php#index_f"><span>f</span></a></li>
      <li class="current"><a href="functions_func_g.php#index_g"><span>g</span></a></li>
      <li><a href="functions_func_h.php#index_h"><span>h</span></a></li>
      <li><a href="functions_func_i.php#index_i"><span>i</span></a></li>
      <li><a href="functions_func_k.php#index_k"><span>k</span></a></li>
      <li><a href="functions_func_m.php#index_m"><span>m</span></a></li>
      <li><a href="functions_func_n.php#index_n"><span>n</span></a></li>
      <li><a href="functions_func_o.php#index_o"><span>o</span></a></li>
      <li><a href="functions_func_p.php#index_p"><span>p</span></a></li>
      <li><a href="functions_func_q.php#index_q"><span>q</span></a></li>
      <li><a href="functions_func_r.php#index_r"><span>r</span></a></li>
      <li><a href="functions_func_s.php#index_s"><span>s</span></a></li>
      <li><a href="functions_func_t.php#index_t"><span>t</span></a></li>
      <li><a href="functions_func_u.php#index_u"><span>u</span></a></li>
      <li><a href="functions_func_w.php#index_w"><span>w</span></a></li>
      <li><a href="functions_func_0x7e.php#index_0x7e"><span>~</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
&#160;

<h3><a class="anchor" id="index_g"></a>- g -</h3><ul>
<li>getArchitecture()
: <a class="el" href="class_n_r_e_1_1_system_1_1_system_info.php#a646d882c712b19344bb9cfef2cef018a">NRE::System::SystemInfo</a>
</li>
<li>getCategory()
: <a class="el" href="class_n_r_e_1_1_event_1_1_event_emitter.php#a3ab6af1ae3a6d22b627f5c5a38643bc8">NRE::Event::EventEmitter&lt; T &gt;</a>
</li>
<li>getClock()
: <a class="el" href="class_n_r_e_1_1_system_1_1_system.php#ac895939d8863dae1dbed70855a07ec4a">NRE::System::System</a>
</li>
<li>getCode()
: <a class="el" href="class_n_r_e_1_1_event_1_1_button_event.php#a9be1f65a106e9efa1c74fc9b9e127c93">NRE::Event::ButtonEvent</a>
, <a class="el" href="class_n_r_e_1_1_event_1_1_key_event.php#aee6a39224443d71b48c315cb4620cc18">NRE::Event::KeyEvent</a>
, <a class="el" href="class_n_r_e_1_1_event_1_1_motion_event.php#a635696b185c15a978cb7d0443a50549d">NRE::Event::MotionEvent</a>
</li>
<li>getCPUName()
: <a class="el" href="class_n_r_e_1_1_system_1_1_system_info.php#accf4044376d402e48eb79e6ebba6b329">NRE::System::SystemInfo</a>
</li>
<li>getDelta()
: <a class="el" href="class_n_r_e_1_1_time_1_1_clock.php#aab40084fb604b17969006b707208e015">NRE::Time::Clock</a>
</li>
<li>getEax()
: <a class="el" href="class_n_r_e_1_1_system_1_1_cpu_i_d.php#ac1be8d5bd47c4cda2620d4fd1cb38553">NRE::System::CpuID</a>
</li>
<li>getEbx()
: <a class="el" href="class_n_r_e_1_1_system_1_1_cpu_i_d.php#a2d2fa8cf048b38bc030c0eac79d170e8">NRE::System::CpuID</a>
</li>
<li>getEcx()
: <a class="el" href="class_n_r_e_1_1_system_1_1_cpu_i_d.php#abbee77878bf7de86d330240e764cd794">NRE::System::CpuID</a>
</li>
<li>getEdx()
: <a class="el" href="class_n_r_e_1_1_system_1_1_cpu_i_d.php#ad33f62f073225b2969b30b4eb4157858">NRE::System::CpuID</a>
</li>
<li>getEventSystem()
: <a class="el" href="class_n_r_e_1_1_system_1_1_system.php#aa247ee0adb3423e34af2859b0145c8ed">NRE::System::System</a>
</li>
<li>getGraphicsSystem()
: <a class="el" href="class_n_r_e_1_1_system_1_1_system.php#aaacfbb3bdc568117a97814127f9d2b37">NRE::System::System</a>
</li>
<li>getId()
: <a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php#a1a8c28f36a398d0e10bd4c7b1cf89ac4">NRE::Graphics::Window</a>
</li>
<li>getMemorySize()
: <a class="el" href="class_n_r_e_1_1_system_1_1_system_info.php#a04b218dae88cfd421e53fee946d6a637">NRE::System::SystemInfo</a>
</li>
<li>getMemoryUsed()
: <a class="el" href="class_n_r_e_1_1_system_1_1_system_info.php#a293ad706965abc2a3b6c28c56998071c">NRE::System::SystemInfo</a>
</li>
<li>getMemoryUsedByProcess()
: <a class="el" href="class_n_r_e_1_1_system_1_1_system_info.php#a32964d022a3401740d477e5ea9a33551">NRE::System::SystemInfo</a>
</li>
<li>getNbProcessors()
: <a class="el" href="class_n_r_e_1_1_system_1_1_system_info.php#a60eee75af32e24cb32ce33521b654587">NRE::System::SystemInfo</a>
</li>
<li>getPosition()
: <a class="el" href="class_n_r_e_1_1_event_1_1_button_event.php#a95f64672b15258e2a75d989024c5d5cf">NRE::Event::ButtonEvent</a>
, <a class="el" href="class_n_r_e_1_1_event_1_1_motion_event.php#af96a0a6eee49ee320313e6d134c5dcbb">NRE::Event::MotionEvent</a>
, <a class="el" href="class_n_r_e_1_1_graphics_1_1_internal_window.php#aa67ab3f27e5e59f59af9dc27fcd6143b">NRE::Graphics::InternalWindow</a>
</li>
<li>getRegister()
: <a class="el" href="class_n_r_e_1_1_system_1_1_cpu_i_d.php#ab26379e14f22509c390fc3673586948c">NRE::System::CpuID</a>
</li>
<li>getRegisters()
: <a class="el" href="class_n_r_e_1_1_system_1_1_cpu_i_d.php#a31efb1583c0414b452c53ac1ef492ca7">NRE::System::CpuID</a>
</li>
<li>getRegistersSize()
: <a class="el" href="class_n_r_e_1_1_system_1_1_cpu_i_d.php#a1a64ffdf0efa46aa56d0254381340c6f">NRE::System::CpuID</a>
</li>
<li>getSystemInfo()
: <a class="el" href="class_n_r_e_1_1_system_1_1_system.php#aec6231860ffa5d7bd5b4967bc924ae47">NRE::System::System</a>
</li>
<li>getSystemName()
: <a class="el" href="class_n_r_e_1_1_system_1_1_system.php#a9ec11b369f76b5a3c28848214d537a2a">NRE::System::System</a>
</li>
<li>getTimestep()
: <a class="el" href="class_n_r_e_1_1_time_1_1_clock.php#ac5b2dec3b35c168d02a1433ce4e5c64e">NRE::Time::Clock</a>
</li>
<li>getWindow()
: <a class="el" href="class_n_r_e_1_1_event_1_1_window_close_event.php#a15a5d5c151d0bc1f171d38f9dda35dc9">NRE::Event::WindowCloseEvent</a>
, <a class="el" href="class_n_r_e_1_1_system_1_1_graphics_system.php#ac856987f85e1c7f3ceb17075b9fa0845">NRE::System::GraphicsSystem</a>
</li>
<li>GlewException()
: <a class="el" href="class_n_r_e_1_1_exception_1_1_glew_exception.php#aca19215fa429d7cd224b5a1922b3140c">NRE::Exception::GlewException</a>
</li>
<li>GLXException()
: <a class="el" href="class_n_r_e_1_1_exception_1_1_g_l_x_exception.php#add848ab5aa58455ea5df8d9517a2754b">NRE::Exception::GLXException</a>
</li>
<li>GraphicsDriver()
: <a class="el" href="class_n_r_e_1_1_graphics_1_1_graphics_driver.php#aca47f0b1940f67a28068208bd90665ed">NRE::Graphics::GraphicsDriver</a>
</li>
<li>GraphicsSystem()
: <a class="el" href="class_n_r_e_1_1_system_1_1_graphics_system.php#a21c1ed2d8e7e7749616afa84c0c99dc1">NRE::System::GraphicsSystem</a>
</li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
