<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: Class Members - Functions</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li class="current"><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
  <div id="navrow3" class="tabs2">
    <ul class="tablist">
      <li><a href="functions.php"><span>All</span></a></li>
      <li class="current"><a href="functions_func.php"><span>Functions</span></a></li>
      <li><a href="functions_vars.php"><span>Variables</span></a></li>
      <li><a href="functions_type.php"><span>Typedefs</span></a></li>
      <li><a href="functions_rela.php"><span>Related&#160;Functions</span></a></li>
    </ul>
  </div>
  <div id="navrow4" class="tabs3">
    <ul class="tablist">
      <li><a href="functions_func.php#index_a"><span>a</span></a></li>
      <li><a href="functions_func_b.php#index_b"><span>b</span></a></li>
      <li><a href="functions_func_c.php#index_c"><span>c</span></a></li>
      <li><a href="functions_func_d.php#index_d"><span>d</span></a></li>
      <li><a href="functions_func_e.php#index_e"><span>e</span></a></li>
      <li><a href="functions_func_f.php#index_f"><span>f</span></a></li>
      <li><a href="functions_func_g.php#index_g"><span>g</span></a></li>
      <li><a href="functions_func_h.php#index_h"><span>h</span></a></li>
      <li><a href="functions_func_i.php#index_i"><span>i</span></a></li>
      <li><a href="functions_func_k.php#index_k"><span>k</span></a></li>
      <li><a href="functions_func_m.php#index_m"><span>m</span></a></li>
      <li><a href="functions_func_n.php#index_n"><span>n</span></a></li>
      <li class="current"><a href="functions_func_o.php#index_o"><span>o</span></a></li>
      <li><a href="functions_func_p.php#index_p"><span>p</span></a></li>
      <li><a href="functions_func_q.php#index_q"><span>q</span></a></li>
      <li><a href="functions_func_r.php#index_r"><span>r</span></a></li>
      <li><a href="functions_func_s.php#index_s"><span>s</span></a></li>
      <li><a href="functions_func_t.php#index_t"><span>t</span></a></li>
      <li><a href="functions_func_u.php#index_u"><span>u</span></a></li>
      <li><a href="functions_func_w.php#index_w"><span>w</span></a></li>
      <li><a href="functions_func_0x7e.php#index_0x7e"><span>~</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
&#160;

<h3><a class="anchor" id="index_o"></a>- o -</h3><ul>
<li>operator&amp;()
: <a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php#a9138844bf5232283fec196a69a678390">NRE::Graphics::WindowStyle</a>
</li>
<li>operator=()
: <a class="el" href="class_n_r_e_1_1_event_1_1_abstract_event_emitter.php#a9449334881d89c077e8e73ff16912b54">NRE::Event::AbstractEventEmitter</a>
, <a class="el" href="class_n_r_e_1_1_event_1_1_button_event.php#a096ac30c61997b412801ce35a00f9544">NRE::Event::ButtonEvent</a>
, <a class="el" href="class_n_r_e_1_1_event_1_1_event_emitter.php#ac65d88fe595a6f4f2c05431213cc9f4e">NRE::Event::EventEmitter&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php#a4d86b6a4273b93f0381fa7dab7b6abe4">NRE::Event::EventHandler&lt; T &gt;</a>
, <a class="el" href="class_n_r_e_1_1_event_1_1_key_event.php#ac57ca1e1ee589079867f0d623f24660c">NRE::Event::KeyEvent</a>
, <a class="el" href="class_n_r_e_1_1_event_1_1_motion_event.php#a2160634a53f34dca907062cd08574f24">NRE::Event::MotionEvent</a>
, <a class="el" href="class_n_r_e_1_1_event_1_1_window_close_event.php#a0c1b0db8bb171b67be3e49055ab66e7d">NRE::Event::WindowCloseEvent</a>
, <a class="el" href="class_n_r_e_1_1_graphics_1_1_context.php#ae69f36da5074b4b37661a282d187e101">NRE::Graphics::Context</a>
, <a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php#ae1f8e2d48ffba31a7a99ad659bb7c58e">NRE::Graphics::ContextAttributes</a>
, <a class="el" href="class_n_r_e_1_1_graphics_1_1_graphics_driver.php#acccee0609eae30ac095fbe27d6598136">NRE::Graphics::GraphicsDriver</a>
, <a class="el" href="class_n_r_e_1_1_graphics_1_1_internal_window.php#a01f7b7a02ae1fa7c5915ebf31097896a">NRE::Graphics::InternalWindow</a>
, <a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php#a280bdd579559cf42a48983e127d863f6">NRE::Graphics::Window</a>
, <a class="el" href="class_n_r_e_1_1_graphics_1_1_window_attributes.php#a5a0f6a0c53e01d858809314d2e761838">NRE::Graphics::WindowAttributes</a>
, <a class="el" href="class_n_r_e_1_1_graphics_1_1_window_status.php#a9eb71c79a7702dffb7e1e9f9029ef80d">NRE::Graphics::WindowStatus</a>
, <a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php#a4ddbc792d3bf210cbbb7c4c183492ee0">NRE::Graphics::WindowStyle</a>
, <a class="el" href="class_n_r_e_1_1_system_1_1_application.php#a91a31e944a7767fe6c75579370dc9fda">NRE::System::Application</a>
, <a class="el" href="class_n_r_e_1_1_system_1_1_event_system.php#aadb5c6bb24595201ce407e05b2684c2b">NRE::System::EventSystem</a>
, <a class="el" href="class_n_r_e_1_1_system_1_1_graphics_system.php#a90ef417cfe165ad559a7cdcbfb333b25">NRE::System::GraphicsSystem</a>
, <a class="el" href="class_n_r_e_1_1_system_1_1_system.php#a5e81c9c5f2f7808cb1498f211155925c">NRE::System::System</a>
, <a class="el" href="class_n_r_e_1_1_time_1_1_clock.php#acd00e63510ebba422ace06a2d452928e">NRE::Time::Clock</a>
</li>
<li>operator==()
: <a class="el" href="class_n_r_e_1_1_event_1_1_button_event.php#a27372075885045c427d151529d249f23">NRE::Event::ButtonEvent</a>
, <a class="el" href="class_n_r_e_1_1_event_1_1_motion_event.php#a32948df1cec46edbe33ec82dd5d4ce9b">NRE::Event::MotionEvent</a>
</li>
<li>operator[]()
: <a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php#a3f541ea3c370c76148f4b1ecf4fae608">NRE::Graphics::ContextAttributes</a>
, <a class="el" href="class_n_r_e_1_1_system_1_1_cpu_i_d.php#a27333c4dc4c2360f695f24349360995a">NRE::System::CpuID</a>
</li>
<li>operator|()
: <a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php#a700de39ee28aaf2cacb0acced6988925">NRE::Graphics::WindowStyle</a>
</li>
<li>operator|=()
: <a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php#a70a5510030cb277349ba4e4ec1a52ac3">NRE::Graphics::WindowStyle</a>
</li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
