<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-System: Class Hierarchy</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li class="current"><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">Class Hierarchy</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock">This inheritance list is sorted roughly, but not completely, alphabetically:</div><div class="directory">
<div class="levels">[detail level <span onclick="javascript:toggleLevel(1);">1</span><span onclick="javascript:toggleLevel(2);">2</span><span onclick="javascript:toggleLevel(3);">3</span>]</div><table class="directory">
<tr id="row_0_" class="even"><td class="entry"><span style="width:0px;display:inline-block;">&#160;</span><span id="arr_0_" class="arrow" onclick="toggleFolder('0_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_system_1_1_application.php" target="_self">NRE::System::Application</a></td><td class="desc">Manage an user application </td></tr>
<tr id="row_0_0_"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_dev_application.php" target="_self">DevApplication</a></td><td class="desc"></td></tr>
<tr id="row_1_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_event_1_1_button_event.php" target="_self">NRE::Event::ButtonEvent</a></td><td class="desc">Manage a button event </td></tr>
<tr id="row_2_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_time_1_1_clock.php" target="_self">NRE::Time::Clock</a></td><td class="desc">Manage timing and program pause </td></tr>
<tr id="row_3_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_graphics_1_1_context.php" target="_self">NRE::Graphics::Context</a></td><td class="desc">Describe an OpenGL <a class="el" href="class_n_r_e_1_1_graphics_1_1_context.php" title="Describe an OpenGL Context with a set of attributes. ">Context</a> with a set of attributes </td></tr>
<tr id="row_4_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_graphics_1_1_context_attributes.php" target="_self">NRE::Graphics::ContextAttributes</a></td><td class="desc">Regroup all attributes needed in a GL context, should be modified before creation </td></tr>
<tr id="row_5_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_system_1_1_cpu_i_d.php" target="_self">NRE::System::CpuID</a></td><td class="desc">Allow access to the cpuid intrinsic command for all system </td></tr>
<tr id="row_6_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_system_1_1_event_system.php" target="_self">NRE::System::EventSystem</a></td><td class="desc">Manage the event sub system </td></tr>
<tr id="row_7_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_system_1_1_graphics_system.php" target="_self">NRE::System::GraphicsSystem</a></td><td class="desc">Manage the graphics sub system </td></tr>
<tr id="row_8_"><td class="entry"><span style="width:0px;display:inline-block;">&#160;</span><span id="arr_8_" class="arrow" onclick="toggleFolder('8_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><b>IException</b></td><td class="desc"></td></tr>
<tr id="row_8_0_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span id="arr_8_0_" class="arrow" onclick="toggleFolder('8_0_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_exception_1_1_system_exception.php" target="_self">NRE::Exception::SystemException</a></td><td class="desc">An exception thrown by system operation </td></tr>
<tr id="row_8_0_0_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_exception_1_1_glew_exception.php" target="_self">NRE::Exception::GlewException</a></td><td class="desc">An exception thrown by glew operation </td></tr>
<tr id="row_8_0_1_" class="even"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_exception_1_1_g_l_x_exception.php" target="_self">NRE::Exception::GLXException</a></td><td class="desc">An exception thrown by glx operation </td></tr>
<tr id="row_8_0_2_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_exception_1_1_w_g_l_exception.php" target="_self">NRE::Exception::WGLException</a></td><td class="desc">An exception thrown by wgl operation </td></tr>
<tr id="row_9_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_event_1_1_input_manager.php" target="_self">NRE::Event::InputManager</a></td><td class="desc">Manage the process of native input </td></tr>
<tr id="row_10_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_graphics_1_1_internal_window.php" target="_self">NRE::Graphics::InternalWindow</a></td><td class="desc">Manage the internal os-dependant graphics window </td></tr>
<tr id="row_11_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_event_1_1_key_event.php" target="_self">NRE::Event::KeyEvent</a></td><td class="desc">Manage a key event </td></tr>
<tr id="row_12_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_event_1_1_key_translater.php" target="_self">NRE::Event::KeyTranslater</a></td><td class="desc">Manage the translation of native key </td></tr>
<tr id="row_13_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_event_1_1_motion_event.php" target="_self">NRE::Event::MotionEvent</a></td><td class="desc">Manage a controller motion event </td></tr>
<tr id="row_14_"><td class="entry"><span style="width:0px;display:inline-block;">&#160;</span><span id="arr_14_" class="arrow" onclick="toggleFolder('14_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><b>Observable</b></td><td class="desc"></td></tr>
<tr id="row_14_0_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span id="arr_14_0_" class="arrow" onclick="toggleFolder('14_0_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_event_1_1_abstract_event_emitter.php" target="_self">NRE::Event::AbstractEventEmitter</a></td><td class="desc">Abstract class for specialized event emission </td></tr>
<tr id="row_14_0_0_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_event_1_1_event_emitter.php" target="_self">NRE::Event::EventEmitter&lt; T &gt;</a></td><td class="desc">Manage event emission to all listener </td></tr>
<tr id="row_15_" class="even"><td class="entry"><span style="width:0px;display:inline-block;">&#160;</span><span id="arr_15_" class="arrow" onclick="toggleFolder('15_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><b>Observer</b></td><td class="desc"></td></tr>
<tr id="row_15_0_"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_event_1_1_event_handler.php" target="_self">NRE::Event::EventHandler&lt; T &gt;</a></td><td class="desc">Manage an event handler for a special type </td></tr>
<tr id="row_16_" class="even"><td class="entry"><span style="width:0px;display:inline-block;">&#160;</span><span id="arr_16_" class="arrow" onclick="toggleFolder('16_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><b>Singleton</b></td><td class="desc"></td></tr>
<tr id="row_16_0_"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_graphics_1_1_graphics_driver.php" target="_self">NRE::Graphics::GraphicsDriver</a></td><td class="desc">Manage the os-dependant graphics driver </td></tr>
<tr id="row_16_1_" class="even"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_system_1_1_system.php" target="_self">NRE::System::System</a></td><td class="desc">Represent the <a class="el" href="class_n_r_e_1_1_system_1_1_system.php" title="Represent the System abstraction layer. ">System</a> abstraction layer </td></tr>
<tr id="row_17_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_system_1_1_system_info.php" target="_self">NRE::System::SystemInfo</a></td><td class="desc">Represent all informations from the user system </td></tr>
<tr id="row_18_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_graphics_1_1_window.php" target="_self">NRE::Graphics::Window</a></td><td class="desc">Manage a graphics window </td></tr>
<tr id="row_19_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_attributes.php" target="_self">NRE::Graphics::WindowAttributes</a></td><td class="desc">Manage a window attributes </td></tr>
<tr id="row_20_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_event_1_1_window_close_event.php" target="_self">NRE::Event::WindowCloseEvent</a></td><td class="desc">Manage a window close event </td></tr>
<tr id="row_21_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_status.php" target="_self">NRE::Graphics::WindowStatus</a></td><td class="desc">Manage a window status </td></tr>
<tr id="row_22_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="class_n_r_e_1_1_graphics_1_1_window_style.php" target="_self">NRE::Graphics::WindowStyle</a></td><td class="desc">Manage a window style </td></tr>
</table>
</div><!-- directory -->
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
